;;
;; $Id: sound-transformation-rulebase.lisp,v 1.2 2009/10/12 16:05:46 kbarker Exp $
;;

(unless (find-package :km) (make-package :km))
(in-package :km)
(setq *using-km-package* t)

;;;;====================================================================
;;;;====================================================================
;;;; FILE: transformation-rules.lisp
;;;;====================================================================
;;;;====================================================================

;;;=====================================================================
;;;=====================================================================
;;; Domain neutral transformations we've enumerated from our upper 
;;; ontology.
;;;=====================================================================
;;;=====================================================================
(defparameter *domain-neutral-transformations*  '(

	;;===============================================================
	;; Handle related-to transformations.
	;;===============================================================
	((((|Thing| . 1)  |related-to| 		(|Thing| . 2))
   	  ((|Thing| . 2)  |related-to| 		(|Thing| . 3)))
  	 (((|Thing| . 1)  |related-to| 		(|Thing| . 3))))

	;;===============================================================
	;;===============================================================
	;; Transformations for Events.
	;;===============================================================
	;;=============================================================== 
 	((((|Event| . 1)  |causes| 		(|Event| . 2))
   	  ((|Event| . 2)  |causes| 		(|Event| . 3)))
  	 (((|Event| . 1)  |causes| 		(|Event| . 3))))
 	((((|Event| . 1)  |causes| 		(|Event| . 2))
   	  ((|Event| . 2)  |subevent| 		(|Event| . 3)))
	 (((|Event| . 1)  |causes| 		(|Event| . 3))))
 	((((|Event| . 1)  |causes| 		(|Event| . 2))
	  ((|Event| . 2)  |resulting-state| 	(|State| . 3)))
	 (((|Event| . 1)  |causes| 		(|State| . 3))))
 	((((|Event| . 1)  |caused-by| 		(|Event| . 2))
 	  ((|Event| . 2)  |subevent-of| 	(|Event| . 3)))
 	 (((|Event| . 1)  |caused-by| 		(|Event| . 3))))
 	((((|Event| . 1)  |caused-by| 		(|Event| . 2))
 	  ((|Event| . 2)  |resulting-state-of| 	(|Event| . 3)))
 	 (((|Event| . 1)  |caused-by| 		(|Event| . 3))))
 	((((|State| . 1)  |defeated-by| 	(|Action| . 2))
 	  ((|Action| . 2) |caused-by| 		(|Event| . 3)))
 	 (((|State| . 1)  |defeated-by| 	(|Event| . 3))))
	((((|State| . 1)  |defeated-by| 	(|Action| . 2))
 	  ((|Action| . 2) |subevent-of| 	(|Event| . 3)))
 	 (((|State| . 1)  |defeated-by| 	(|Event| . 3))))

	((((|Event| . 1)  |enables| 		(|Event| . 2))
 	  ((|Event| . 2)  |enables| 		(|Event| . 3)))
 	 (((|Event| . 1)  |enables| 		(|Event| . 3))))
 	((((|Event| . 1)  |enables| 		(|Event| . 2))
 	  ((|Event| . 2)  |causes| 		(|Event| . 3)))
 	 (((|Event| . 1)  |enables| 		(|Event| . 3))))
 	((((|Event| . 1)  |enables| 		(|Event| . 2))
 	  ((|Event| . 2)  |resulting-state| 	(|State| . 3)))
 	 (((|Event| . 1)  |enables| 		(|State| . 3))))
 	((((|Event| . 1)  |enables| 		(|Event| . 2))
 	  ((|Event| . 2)  |subevent| 		(|Event| . 3)))
 	 (((|Event| . 1)  |enables| 		(|Event| . 3))))
 	((((|Event| . 1)  |enables| 		(|Event| . 2))		;; <- ??
 	  ((|Event| . 2)  |subevent-of| 	(|Event| . 3)))
 	 (((|Event| . 1)  |enables| 		(|Event| . 3))))
 	((((|Event| . 1)  |enabled-by| 		(|Event| . 2))
 	  ((|Event| . 2)  |caused-by| 		(|Event| . 3)))
 	 (((|Event| . 1)  |enabled-by| 		(|Event| . 3))))
 	((((|Event| . 1)  |enabled-by| 		(|Event| . 2))
 	  ((|Event| . 2)  |resulting-state-of| 	(|Event| . 3)))
 	 (((|Event| . 1)  |enabled-by| 		(|Event| . 3))))
 	((((|Event| . 1)  |enabled-by| 		(|Event| . 2))
 	  ((|Event| . 2)  |subevent-of| 	(|Event| . 3)))
 	 (((|Event| . 1)  |enabled-by| 		(|Event| . 3))))

 	((((|Event| . 1)  |inhibits| 		(|Event| . 2))
 	  ((|Event| . 2)  |subevent-of| 	(|Event| . 3)))
 	 (((|Event| . 1)  |inhibits| 		(|Event| . 3))))
 	((((|Event| . 1)  |inhibits| 		(|Event| . 2))
 	  ((|Event| . 2)  |resulting-state| 	(|State| . 3)))
 	 (((|Event| . 1)  |inhibits| 		(|State| . 3))))
 	((((|Event| . 1)  |inhibited-by| 	(|Event| . 2))
 	  ((|Event| . 2)  |subevent-of| 	(|Event| . 3)))
 	 (((|Event| . 1)  |inhibited-by|	(|Event| . 3))))
 	((((|Event| . 1)  |inhibited-by| 	(|Event| . 2))
 	  ((|Event| . 2)  |caused-by| 		(|Event| . 3)))
 	 (((|Event| . 1)  |inhibited-by| 	(|Event| . 3))))
 	((((|Event| . 1)  |inhibited-by| 	(|Event| . 2))
  	  ((|Event| . 2)  |resulting-state-of| 	(|Event| . 3)))
 	 (((|Event| . 1)  |inhibited-by| 	(|Event| . 3))))

 	((((|Event| . 1)  |by-means-of| 	(|Event| . 2))
 	  ((|Event| . 2)  |by-means-of| 	(|Event| . 3)))
 	 (((|Event| . 1)  |by-means-of| 	(|Event| . 3))))

 	((((|Event| . 1)  |prevents| 		(|Event| . 2))
 	  ((|Event| . 2)  |subevent-of| 	(|Event| . 3)))
 	 (((|Event| . 1)  |prevents| 		(|Event| . 3))))
 	((((|Event| . 1)  |prevented-by| 	(|Event| . 2))
 	  ((|Event| . 2)  |subevent-of| 	(|Event| . 3)))
 	 (((|Event| . 1)  |prevented-by| 	(|Event| . 3))))
 	((((|Event| . 1)  |prevented-by| 	(|Event| . 2))
 	  ((|Event| . 2)  |caused-by| 		(|Event| . 3)))
 	 (((|Event| . 1)  |prevented-by| 	(|Event| . 3))))
 	((((|Event| . 1)  |prevented-by| 	(|Event| . 2))
 	  ((|Event| . 2)  |resulting-state-of| 	(|Event| . 3)))
 	 (((|Event| . 1)  |prevented-by| 	(|Event| . 3))))
 
	((((|Event| . 1)  |subevent| 		(|Event| . 2))
 	  ((|Event| . 2)  |subevent| 		(|Event| . 3)))
 	 (((|Event| . 1)  |subevent| 		(|Event| . 3))))

	;;===============================================================
	;;===============================================================
	;; Transformations for case roles.
	;;===============================================================
	;;===============================================================
 	((((|Event| . 1) 		|away-from| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|has-part| 	(|Entity| . 3)))
 	 (((|Event| . 1) 		|away-from| 	(|Entity| . 3))))
 	((((|Event| . 1) 		|away-from| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|has-region| 	(|Spatial-Entity| . 3)))
 	 (((|Event| . 1) 		|away-from| 	(|Spatial-Entity| . 3))))
 	((((|Event| . 1) 		|away-from| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|location| 	(|Place| . 3)))
 	 (((|Event| . 1) 		|away-from| 	(|Place| . 3))))
 	((((|Event| . 1) 		|away-from| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|location-of| 	(|Spatial-Entity| . 3)))
 	 (((|Event| . 1) 		|away-from| 	(|Spatial-Entity| . 3))))
	((((|Event| . 1) 		|away-from| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|is-at| 	(|Spatial-Entity| . 3)))
 	 (((|Event| . 1) 		|away-from| 	(|Spatial-Entity| . 3))))

 	((((|Event| . 1) 		|base| 		(|Entity| . 2))
 	  ((|Entity| . 2) 		|is-part-of| 	(|Entity| . 3)))
 	 (((|Event| . 1) 		|base| 		(|Entity| . 3))))
 	((((|Event| . 1) 		|base| 		(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|is-region-of| 	(|Tangible-Entity| . 3)))
 	 (((|Event| . 1) 		|base| 		(|Tangible-Entity| . 3))))
 	((((|Event| . 1) 		|base| 		(|Event| . 2))
 	  ((|Event| . 2) 		|subevent-of| 	(|Event| . 3)))
 	 (((|Event| . 1) 		|base| 		(|Event| . 3))))

 	((((|Event| . 1) 		|beneficiary| 	(|Entity| . 2))
 	  ((|Entity| . 2) 		|is-part-of| 	(|Entity| . 3)))
 	 (((|Event| . 1) 		|beneficiary| 	(|Entity| . 3))))
 	((((|Event| . 1) 		|beneficiary| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|is-region-of| 	(|Tangible-Entity| . 3)))
 	 (((|Event| . 1) 		|beneficiary| 	(|Tangible-Entity| . 3))))
 	((((|Event| . 1) 		|beneficiary| 	(|Aggregate| . 2))
 	  ((|Aggregate| . 2) 		|element| 	(|Entity| . 3)))
 	 (((|Event| . 1) 		|beneficiary| 	(|Entity| . 3))))

 	((((|Event| . 1) 		|destination| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|location| 	(|Place| . 3)))
 	 (((|Event| . 1) 		|destination| 	(|Place| . 3))))
 	((((|Event| . 1) 		|destination| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|location-of| 	(|Spatial-Entity| . 3)))
 	 (((|Event| . 1) 		|destination| 	(|Spatial-Entity| . 3))))
 	((((|Event| . 1) 		|destination| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|is-part-of| 	(|Spatial-Entity| . 3)))
 	 (((|Event| . 1) 		|destination| 	(|Spatial-Entity| . 3))))
 	((((|Event| . 1) 		|destination| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|is-region-of| 	(|Tangible-Entity| . 3)))
 	 (((|Event| . 1) 		|destination| 	(|Tangible-Entity| . 3))))
 	((((|Event| . 1) 		|destination| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|is-at| 	(|Spatial-Entity| . 3)))
 	 (((|Event| . 1) 		|destination| 	(|Spatial-Entity| . 3))))
 	((((|Event| . 1) 		|destination| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|is-inside| 	(|Spatial-Entity| . 3)))
 	 (((|Event| . 1) 		|destination| 	(|Spatial-Entity| . 3))))

 	((((|Event| . 1) 		|instrument| 	(|Entity| . 2))
 	  ((|Entity| . 2) 		|is-part-of| 	(|Entity| . 3)))
 	 (((|Event| . 1) 		|instrument| 	(|Entity| . 3))))

 	((((|Thing| . 1) 		|location| 	(|Place| . 2))
 	  ((|Place| . 2) 		|is-region-of| 	(|Tangible-Entity| . 3)))
 	 (((|Thing| . 1) 		|location| 	(|Tangible-Entity| . 3))))
 	((((|Place| . 1) 		|location-of| 	(|Event| . 2))
 	  ((|Event| . 2) 		|subevent| 	(|Event| . 3)))
 	 (((|Place| . 1) 		|location-of| 	(|Event| . 3))))

 	((((|Event| . 1) 		|object| 	(|Entity| . 2))
 	  ((|Entity| . 2) 		|is-part-of| 	(|Entity| . 3)))
 	 (((|Event| . 1) 		|object| 	(|Entity| . 3))))
 	((((|Event| . 1) 		|object| 	(|Entity| . 2))
 	  ((|Entity| . 2) 		|is-region-of| 	(|Tangible-Entity| . 3)))
 	 (((|Event| . 1) 		|object| 	(|Tangible-Entity| . 3))))

 	((((|Event| . 1) 		|origin| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|location| 	(|Place| . 3)))
 	 (((|Event| . 1) 		|origin| 	(|Place| . 3))))
 	((((|Event| . 1) 		|origin| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|location-of| 	(|Spatial-Entity| . 3)))
 	 (((|Event| . 1) 		|origin| 	(|Spatial-Entity| . 3))))
 	((((|Event| . 1) 		|origin| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|is-part-of| 	(|Entity| . 3)))
 	 (((|Event| . 1) 		|origin| 	(|Entity| . 3))))
 	((((|Event| . 1) 		|origin| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|is-region-of| 	(|Tangible-Entity| . 3)))
 	 (((|Event| . 1) 		|origin| 	(|Tangible-Entity| . 3))))
 	((((|Event| . 1) 		|origin| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|is-at| 	(|Spatial-Entity| . 3)))
 	 (((|Event| . 1) 		|origin| 	(|Spatial-Entity| . 3))))
 	((((|Event| . 1) 		|origin| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|is-inside| 	(|Spatial-Entity| . 3)))
 	 (((|Event| . 1) 		|origin| 	(|Spatial-Entity| . 3))))

 	((((|Event| . 1) 		|path| 		(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|location| 	(|Place| . 3)))
 	 (((|Event| . 1) 		|path| 		(|Place| . 3))))
 	((((|Event| . 1) 		|path| 		(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|location-of| 	(|Spatial-Entity| . 3)))
 	 (((|Event| . 1) 		|path| 		(|Spatial-Entity| . 3))))
 	((((|Event| . 1) 		|path| 		(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|is-part-of| 	(|Entity| . 3)))
 	 (((|Event| . 1) 		|path| 		(|Entity| . 3))))
	((((|Event| . 1) 		|path| 		(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|is-region-of| 	(|Tangible-Entity| . 3)))
 	 (((|Event| . 1) 		|path| 		(|Tangible-Entity| . 3))))

 	((((|Event| . 1) 		|raw-material| 	(|Tangible-Entity| . 2))
 	  ((|Tangible-Entity| . 2) 	|has-part| 	(|Tangible-Entity| . 3)))
 	 (((|Event| . 1) 		|raw-material| 	(|Tangible-Entity| . 3))))
 	((((|Event| . 1) 		|raw-material| 	(|Tangible-Entity| . 2))
 	  ((|Tangible-Entity| . 2) 	|material| 	(|Tangible-Entity| . 3)))
 	 (((|Event| . 1) 		|raw-material| 	(|Tangible-Entity| . 3))))
 	((((|Event| . 1) 		|raw-material| 	(|Aggregate| . 2))
 	  ((|Aggregate| . 2) 		|element| 	(|Tangible-Entity| . 3)))
 	 (((|Event| . 1) 		|raw-material| 	(|Tangible-Entity| . 3))))

 	((((|Entity| . 1) 		|result-of| 	(|Event| . 2))
 	  ((|Event| . 2) 		|subevent-of| 	(|Event| . 3)))
 	 (((|Entity| . 1) 		|result-of| 	(|Event| . 3))))

 	((((|Event| . 1) 		|site| 		(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|location| 	(|Place| . 3)))
 	 (((|Event| . 1) 		|site| 		(|Place| . 3))))
 	((((|Event| . 1) 		|site| 		(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|is-part-of| 	(|Entity| . 3)))
 	 (((|Event| . 1) 		|site| 		(|Entity| . 3))))
 	((((|Event| . 1) 		|site| 		(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|is-region-of| 	(|Tangible-Entity| . 3)))
 	 (((|Event| . 1) 		|site| 		(|Tangible-Entity| . 3))))
 	((((|Spatial-Entity| . 1) 	|site-of| 	(|Event| . 2))
 	  ((|Event| . 2) 		|subevent| 	(|Event| . 3)))
 	 (((|Spatial-Entity| . 1) 	|site-of| 	(|Event| . 3))))

 	((((|Event| . 1) 		|toward| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|location| 	(|Place| . 3)))
 	 (((|Event| . 1) 		|toward| 	(|Place| . 3))))
 	((((|Event| . 1) 		|toward| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|location-of| 	(|Spatial-Entity| . 3)))
 	 (((|Event| . 1) 		|toward| 	(|Spatial-Entity| . 3))))
 	((((|Event| . 1) 		|toward| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|has-part| 	(|Entity| . 3)))
 	 (((|Event| . 1) 		|toward| 	(|Entity| . 3))))
 	((((|Event| . 1) 		|toward| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|has-region| 	(|Spatial-Entity| . 3)))
 	 (((|Event| . 1) 		|toward| 	(|Spatial-Entity| . 3))))
 	((((|Event| . 1) 		|toward| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|is-at| 	(|Spatial-Entity| . 3)))
 	 (((|Event| . 1) 		|toward| 	(|Spatial-Entity| . 3))))
 	((((|Event| . 1) 		|toward| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|is-near| 	(|Spatial-Entity| . 3)))
 	 (((|Event| . 1) 		|toward| 	(|Spatial-Entity| . 3))))

        ((((|Event|  . 0) 		|site|      	(|Place| . 1)))
         (((|Event|  . 0) 		|location|   	(|Place| . 1))))
        ((((|Event|  . 0) 		|location|   	(|Place| . 1)))
         (((|Event|  . 0) 		|site|      	(|Place| . 1))))


	;;===============================================================
	;;===============================================================
	;; Roles.
	;;===============================================================
	;;===============================================================
 	((((|Role| . 1) 		|played-by| 		(|Entity| . 2))
 	  ((|Entity| . 2) 		|is-part-of| 		(|Entity| . 3)))
 	 (((|Role| . 1) 		|played-by| 		(|Entity| . 3))))
 	((((|Role| . 1) 		|played-by| 		(|Entity| . 2))
 	  ((|Entity| . 2) 		|is-region-of| 		(|Tangible-Entity| . 3)))
 	 (((|Role| . 1) 		|played-by| 		(|Tangible-Entity| . 3))))

 	((((|Role| . 1) 		|in-event| 		(|Event| . 2))
 	  ((|Event| . 2) 		|subevent-of| 		(|Event| . 3)))
 	 (((|Role| . 1) 		|in-event| 		(|Event| . 3))))

 	((((|Container| . 1) 		|content| 		(|Entity| . 2))		;; <- ??
 	  ((|Entity| . 2) 		|content| 		(|Entity| . 3)))
 	 (((|Container| . 1) 		|content| 		(|Entity| . 3))))
 	((((|Container| . 1) 		|content| 		(|Entity| . 2))
 	  ((|Entity| . 2) 		|has-part| 		(|Entity| . 3)))
 	 (((|Container| . 1) 		|content| 		(|Entity| . 3))))
 	((((|Container| . 1) 		|content| 		(|Entity| . 2))
 	  ((|Entity| . 2) 		|has-region| 		(|Spatial-Entity| . 3)))
 	 (((|Container| . 1) 		|content| 		(|Spatial-Entity| . 3))))
 	((((|Container| . 1) 		|content| 		(|Tangible-Entity| . 2))
 	  ((|Tangible-Entity| . 2) 	|material| 		(|Tangible-Entity| . 3)))
 	 (((|Container| . 1) 		|content| 		(|Tangible-Entity| . 3))))
 	((((|Container| . 1) 		|content| 		(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|encloses| 		(|Spatial-Entity| . 3)))
 	 (((|Container| . 1) 		|content| 		(|Spatial-Entity| . 3))))

	;;===============================================================
        ;;===============================================================
        ;; Rewrites for Entity to Entity relations.
        ;;===============================================================
        ;;===============================================================
	;; **NOTE**: Need to fix these!
 	((((|Entity| . 1) 		|has-part| 		(|Entity| . 2))
 	  ((|Entity| . 2) 		|has-part| 		(|Entity| . 3)))
 	 (((|Entity| . 1) 		|has-part| 		(|Entity| . 3))))
	;; Was Tangible-Entity, but has been changed to Entity.
	;;
 	;; ((((|Entity| . 1) 		|has-functional-part| 	(|Entity| . 2)))
 	;;  (((|Entity| . 1) 		|has-part| 		(|Entity| . 2))))
 	;; ((((|Entity| . 1) 		|has-structural-part|	(|Entity| . 2)))
 	;;  (((|Entity| . 1) 		|has-part| 		(|Entity| . 2))))
	;;
 	((((|Entity| . 1) 		|has-basic-structural-unit| (|Entity| . 2)))
 	 (((|Entity| . 1) 		|has-part| 		(|Entity| . 2))))
 	((((|Entity| . 1) 		|has-basic-functional-unit| (|Entity| . 2)))
  	 (((|Entity| . 1) 		|has-part| 		(|Entity| . 2))))

 	((((|Tangible-Entity| . 1) 	|has-region| 		(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|has-region| 		(|Spatial-Entity| . 3)))
 	 (((|Tangible-Entity| . 1) 	|has-region| 		(|Spatial-Entity| . 3))))

 	((((|Spatial-Entity| . 1) 	|is-region-of| 		(|Tangible-Entity| . 2))
 	  ((|Tangible-Entity| . 2) 	|is-part-of| 		(|Entity| . 3)))
 	 (((|Spatial-Entity| . 1) 	|is-region-of| 		(|Entity| . 3))))

 	((((|Thing| . 1) 		|location| 		(|Place| . 2))
  	  ((|Place| . 2) 		|location| 		(|Place| . 3)))
  	 (((|Thing| . 1) 		|location| 		(|Place| . 3))))
#| *PZY*: 07/26/05 -- causing problems.
 	((((|Place| . 1) 		|location-of| 		(|Entity| . 2))
 	  ((|Entity| . 2) 		|has-part| 		(|Entity| . 3)))
 	 (((|Place| . 1) 		|location-of| 		(|Entity| . 3))))
|#
 	((((|Place| . 1) 		|location-of| 		(|Tangible-Entity| . 2))
 	  ((|Tangible-Entity| . 2) 	|has-region| 		(|Spatial-Entity| . 3)))
 	 (((|Place| . 1) 		|location-of| 		(|Spatial-Entity| . 3))))
 	((((|Place| . 1) 		|location-of| 		(|Tangible-Entity| . 2))
 	  ((|Tangible-Entity| . 2) 	|material| 		(|Tangible-Entity| . 3)))
 	 (((|Place| . 1) 		|location-of| 		(|Tangible-Entity| . 3))))

 	((((|Tangible-Entity| . 1) 	|material| 		(|Tangible-Entity| . 2))
 	  ((|Tangible-Entity| . 2) 	|material| 		(|Tangible-Entity| . 3)))
 	 (((|Tangible-Entity| . 1) 	|material| 		(|Tangible-Entity| . 3))))
 	((((|Tangible-Entity| . 1) 	|material-of| 		(|Tangible-Entity| . 2))
 	  ((|Tangible-Entity| . 2) 	|is-part-of| 		(|Entity| . 3)))
 	 (((|Tangible-Entity| . 1) 	|material-of| 		(|Entity| . 3))))

 	((((|Aggregate| . 1) 		|element| 		(|Thing| . 2))
 	  ((|Thing| . 2) 		|element| 		(|Thing| . 3)))
 	 (((|Aggregate| . 1) 		|element| 		(|Thing| . 3))))
 	((((|Aggregate| . 1) 		|first-element| 	(|Entity| . 2))
 	  ((|Entity| . 2) 		|first-element| 	(|Entity| . 3)))
 	 (((|Aggregate| . 1) 		|first-element| 	(|Entity| . 3))))

 	((((|Entity| . 1) 		|possesses| 		(|Entity| . 2))
 	  ((|Entity| . 2) 		|has-part| 		(|Entity| . 3)))
 	 (((|Entity| . 1) 		|possesses| 		(|Entity| . 3))))
 	((((|Entity| . 1) 		|possesses| 		(|Tangible-Entity| . 2))
 	  ((|Tangible-Entity| . 2) 	|has-region|	 	(|Spatial-Entity| . 3)))
 	 (((|Entity| . 1) 		|possesses| 		(|Spatial-Entity| . 3))))
 	((((|Entity| . 1) 		|possesses| 		(|Tangible-Entity| . 2))
 	  ((|Tangible-Entity| . 2) 	|material| 		(|Tangible-Entity| . 3)))
 	 (((|Entity| . 1) 		|possesses| 		(|Tangible-Entity| . 3))))
 	((((|Entity| . 1) 		|possesses| 		(|Aggregate| . 2))
 	  ((|Aggregate| . 2) 		|element| 		(|Thing| . 3)))
 	 (((|Entity| . 1) 		|possesses| 		(|Thing| . 3))))

	;;===============================================================
        ;;===============================================================
        ;; Transformations for space.
        ;;===============================================================
        ;;===============================================================
 	((((|Spatial-Entity| . 1) 	|abuts| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|location| 	(|Place| . 3)))
 	 (((|Spatial-Entity| . 1) 	|abuts| 	(|Place| . 3))))
 	((((|Spatial-Entity| . 1) 	|abuts| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|location-of| 	(|Spatial-Entity| . 3)))
 	 (((|Spatial-Entity| . 1) 	|abuts| 	(|Spatial-Entity| . 3))))

 	((((|Spatial-Entity| . 1) 	|is-above| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|location| 	(|Place| . 3)))
 	 (((|Spatial-Entity| . 1) 	|is-above| 	(|Place| . 3))))
 	((((|Spatial-Entity| . 1) 	|is-above| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|location-of| 	(|Spatial-Entity| . 3)))
 	 (((|Spatial-Entity| . 1) 	|is-above| 	(|Spatial-Entity| . 3))))
 	((((|Spatial-Entity| . 1) 	|is-above| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|is-above| 	(|Spatial-Entity| . 3)))
 	 (((|Spatial-Entity| . 1) 	|is-above| 	(|Spatial-Entity| . 3))))
 	((((|Spatial-Entity| . 1) 	|is-above| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|encloses| 	(|Spatial-Entity| . 3)))
 	 (((|Spatial-Entity| . 1) 	|is-above| 	(|Spatial-Entity| . 3))))
 	((((|Spatial-Entity| . 1) 	|is-above| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|is-on| 	(|Spatial-Entity| . 3)))
 	 (((|Spatial-Entity| . 1) 	|is-above| 	(|Spatial-Entity| . 3))))
 	((((|Spatial-Entity| . 1) 	|is-above|	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|is-over| 	(|Spatial-Entity| . 3)))
 	 (((|Spatial-Entity| . 1) 	|is-above| 	(|Spatial-Entity| . 3))))
 	((((|Spatial-Entity| . 1) 	|is-above| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|is-at-of| 	(|Spatial-Entity| . 3)))
 	 (((|Spatial-Entity| . 1) 	|is-above| 	(|Spatial-Entity| . 3))))
 	((((|Spatial-Entity| . 1) 	|is-above| 	(|Spatial-Entity| . 2))		;; <- ??
 	  ((|Spatial-Entity| . 2) 	|element| 	(|Spatial-Entity| . 3)))
 	 (((|Spatial-Entity| . 1) 	|is-above| 	(|Spatial-Entity| . 3))))

 	((((|Spatial-Entity| . 1) 	|is-below| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|location| 	(|Place| . 3)))
 	 (((|Spatial-Entity| . 1) 	|is-below| 	(|Place| . 3))))
 	((((|Spatial-Entity| . 1) 	|is-below| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|location-of| 	(|Spatial-Entity| . 3)))
 	 (((|Spatial-Entity| . 1) 	|is-below| 	(|Spatial-Entity| . 3))))
 	((((|Spatial-Entity| . 1) 	|is-below| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|encloses| 	(|Spatial-Entity| . 3)))
 	 (((|Spatial-Entity| . 1) 	|is-below| 	(|Spatial-Entity| . 3))))
 	((((|Spatial-Entity| . 1) 	|is-below| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|has-on-it| 	(|Spatial-Entity| . 3)))
 	 (((|Spatial-Entity| . 1) 	|is-below| 	(|Spatial-Entity| . 3))))
 	((((|Spatial-Entity| . 1) 	|is-below| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|is-under| 	(|Spatial-Entity| . 3)))
 	 (((|Spatial-Entity| . 1) 	|is-below| 	(|Spatial-Entity| . 3))))
 	((((|Spatial-Entity| . 1) 	|is-below| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|is-at-of| 	(|Spatial-Entity| . 3)))
 	 (((|Spatial-Entity| . 1) 	|is-below| 	(|Spatial-Entity| . 3))))
 	((((|Spatial-Entity| . 1) 	|is-below| 	(|Spatial-Entity| . 2))		;; <- ??
 	  ((|Spatial-Entity| . 2) 	|element| 	(|Spatial-Entity| . 3)))
 	 (((|Spatial-Entity| . 1) 	|is-below| 	(|Spatial-Entity| . 3))))

 	((((|Spatial-Entity| . 1) 	|is-along| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|location| 	(|Place| . 3)))
 	 (((|Spatial-Entity| . 1) 	|is-along| 	(|Place| . 3))))
 	((((|Spatial-Entity| . 1) 	|is-along| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|location-of| 	(|Spatial-Entity| . 3)))
 	 (((|Spatial-Entity| . 1) 	|is-along| 	(|Spatial-Entity| . 3))))
 	((((|Spatial-Entity| . 1) 	|is-along| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|is-at| 	(|Spatial-Entity| . 3)))
 	 (((|Spatial-Entity| . 1) 	|is-along| 	(|Spatial-Entity| . 3))))
 	((((|Spatial-Entity| . 1) 	|is-along| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|encloses| 	(|Spatial-Entity| . 3)))
 	 (((|Spatial-Entity| . 1) 	|is-along| 	(|Spatial-Entity| . 3))))

 	((((|Spatial-Entity| . 1) 	|is-at| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|is-at| 	(|Spatial-Entity| . 3)))
 	 (((|Spatial-Entity| . 1) 	|is-at| 	(|Spatial-Entity| . 3))))
 	((((|Spatial-Entity| . 1) 	|is-at| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|location| 	(|Place| . 3)))
 	 (((|Spatial-Entity| . 1) 	|is-at| 	(|Place| . 3))))
 	((((|Spatial-Entity| . 1) 	|is-at| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|location-of| 	(|Spatial-Entity| . 3)))
 	 (((|Spatial-Entity| . 1) 	|is-at| 	(|Spatial-Entity| . 3))))
 	((((|Spatial-Entity| . 1) 	|is-at| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|is-inside| 	(|Spatial-Entity| . 3)))
 	 (((|Spatial-Entity| . 1) 	|is-at| 	(|Spatial-Entity| . 3))))
 	((((|Spatial-Entity| . 1) 	|is-at-of| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|location| 	(|Place| . 3)))
 	 (((|Spatial-Entity| . 1) 	|is-at-of| 	(|Place| . 3))))
 	((((|Spatial-Entity| . 1) 	|is-at-of| 	(|Spatial-Entity| . 2))
  	  ((|Spatial-Entity| . 2) 	|location-of| 	(|Spatial-Entity| . 3)))
  	 (((|Spatial-Entity| . 1) 	|is-at-of| 	(|Spatial-Entity| . 3))))
 	((((|Spatial-Entity| . 1) 	|is-at-of| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|has-on-it| 	(|Spatial-Entity| . 3)))
 	 (((|Spatial-Entity| . 1) 	|is-at-of| 	(|Spatial-Entity| . 3))))
 	((((|Spatial-Entity| . 1) 	|is-at-of| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|element| 	(|Spatial-Entity| . 3)))
 	 (((|Spatial-Entity| . 1) 	|is-at-of| 	(|Spatial-Entity| . 3))))

 	((((|Spatial-Entity| . 1) 	|is-beside| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|location| 	(|Place| . 3)))
 	 (((|Spatial-Entity| . 1) 	|is-beside| 	(|Place| . 3))))
 	((((|Spatial-Entity| . 1) 	|is-beside| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|location-of| 	(|Spatial-Entity| . 3)))
 	 (((|Spatial-Entity| . 1) 	|is-beside| 	(|Spatial-Entity| . 3))))
 	((((|Spatial-Entity| . 1) 	|is-beside| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|is-at| 	(|Spatial-Entity| . 3)))
 	 (((|Spatial-Entity| . 1) 	|is-beside| 	(|Spatial-Entity| . 3))))
 	((((|Spatial-Entity| . 1) 	|is-beside| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|encloses| 	(|Spatial-Entity| . 3)))
 	 (((|Spatial-Entity| . 1) 	|is-beside| 	(|Spatial-Entity| . 3))))

 	((((|Spatial-Entity| . 1) 	|is-between| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|location| 	(|Place| . 3)))
 	 (((|Spatial-Entity| . 1) 	|is-between| 	(|Place| . 3))))
 	((((|Spatial-Entity| . 1) 	|is-between| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|location-of| 	(|Spatial-Entity| . 3)))
 	 (((|Spatial-Entity| . 1) 	|is-between| 	(|Spatial-Entity| . 3))))

 	((((|Spatial-Entity| . 1) 	|is-behind| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|location| 	(|Place| . 3)))
 	 (((|Spatial-Entity| . 1) 	|is-behind| 	(|Place| . 3))))
 	((((|Spatial-Entity| . 1) 	|is-behind| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|location-of| 	(|Spatial-Entity| . 3)))
 	 (((|Spatial-Entity| . 1) 	|is-behind| 	(|Spatial-Entity| . 3))))
 	((((|Spatial-Entity| . 1) 	|is-behind| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|is-behind| 	(|Spatial-Entity| . 3)))
 	 (((|Spatial-Entity| . 1) 	|is-behind| 	(|Spatial-Entity| . 3))))
 	((((|Spatial-Entity| . 1) 	|is-behind| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|encloses| 	(|Spatial-Entity| . 3)))
 	 (((|Spatial-Entity| . 1) 	|is-behind| 	(|Spatial-Entity| . 3))))
 	((((|Spatial-Entity| . 1) 	|is-behind| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|has-on-it| 	(|Spatial-Entity| . 3)))
 	 (((|Spatial-Entity| . 1) 	|is-behind| 	(|Spatial-Entity| . 3))))
 	((((|Spatial-Entity| . 1) 	|is-behind| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|is-at| 	(|Spatial-Entity| . 3)))
 	 (((|Spatial-Entity| . 1) 	|is-behind| 	(|Spatial-Entity| . 3))))
 	((((|Spatial-Entity| . 1) 	|is-behind| 	(|Spatial-Entity| . 2))		;; <- ??
 	  ((|Spatial-Entity| . 2) 	|element| 	(|Spatial-Entity| . 3)))
 	 (((|Spatial-Entity| . 1) 	|is-behind| 	(|Spatial-Entity| . 3))))

 	((((|Spatial-Entity| . 1) 	|is-in-front-of| (|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|location| 	 (|Place| . 3)))
 	 (((|Spatial-Entity| . 1) 	|is-in-front-of| (|Place| . 3))))
 	((((|Spatial-Entity| . 1) 	|is-in-front-of| (|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|location-of| 	 (|Spatial-Entity| . 3)))
 	 (((|Spatial-Entity| . 1) 	|is-in-front-of| (|Spatial-Entity| . 3))))
 	((((|Spatial-Entity| . 1) 	|is-in-front-of| (|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|is-along| 	 (|Spatial-Entity| . 3)))
 	 (((|Spatial-Entity| . 1) 	|is-in-front-of| (|Spatial-Entity| . 3))))
 	((((|Spatial-Entity| . 1) 	|is-in-front-of| (|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|is-at| 	 (|Spatial-Entity| . 3)))
 	 (((|Spatial-Entity| . 1) 	|is-in-front-of| (|Spatial-Entity| . 3))))
 	((((|Spatial-Entity| . 1) 	|is-in-front-of| (|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|encloses| 	 (|Spatial-Entity| . 3)))
 	 (((|Spatial-Entity| . 1) 	|is-in-front-of| (|Spatial-Entity| . 3))))
 	((((|Spatial-Entity| . 1) 	|is-in-front-of| (|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|has-on-it| 	 (|Spatial-Entity| . 3)))
 	 (((|Spatial-Entity| . 1) 	|is-in-front-of| (|Spatial-Entity| . 3))))
 	((((|Spatial-Entity| . 1) 	|is-in-front-of| (|Spatial-Entity| . 2))	;; <- ??
 	  ((|Spatial-Entity| . 2) 	|element| 	 (|Spatial-Entity| . 3)))
 	 (((|Spatial-Entity| . 1) 	|is-in-front-of| (|Spatial-Entity| . 3))))

 	((((|Spatial-Entity| . 1) 	|is-inside| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|is-inside| 	(|Spatial-Entity| . 3)))
 	 (((|Spatial-Entity| . 1) 	|is-inside| 	(|Spatial-Entity| . 3))))
 	((((|Spatial-Entity| . 1) 	|is-inside| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|location| 	(|Place| . 3)))
 	 (((|Spatial-Entity| . 1) 	|is-inside| 	(|Place| . 3))))
 	((((|Spatial-Entity| . 1) 	|is-inside| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|location-of| 	(|Spatial-Entity| . 3)))
 	 (((|Spatial-Entity| . 1) 	|is-inside| 	(|Spatial-Entity| . 3))))
 	((((|Spatial-Entity| . 1) 	|is-inside| 	(|Spatial-Entity| . 2))		;; <- ??
 	  ((|Spatial-Entity| . 2) 	|element-of| 	(|Aggregate| . 3)))
 	 (((|Spatial-Entity| . 1) 	|is-inside| 	(|Aggregate| . 3))))
 	((((|Spatial-Entity| . 1) 	|is-inside| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|is-part-of| 	(|Spatial-Entity| . 3)))
 	 (((|Spatial-Entity| . 1) 	|is-inside| 	(|Spatial-Entity| . 3))))

 	((((|Spatial-Entity| . 1) 	|encloses| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|location| 	(|Place| . 3)))
 	 (((|Spatial-Entity| . 1) 	|encloses| 	(|Place| . 3))))
 	((((|Spatial-Entity| . 1) 	|encloses| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|location-of| 	(|Spatial-Entity| . 3)))
 	 (((|Spatial-Entity| . 1) 	|encloses| 	(|Spatial-Entity| . 3))))
 	((((|Spatial-Entity| . 1) 	|encloses| 	(|Spatial-Entity| . 2))		;; <- ??
 	  ((|Spatial-Entity| . 2) 	|element| 	(|Spatial-Entity| . 3)))
 	 (((|Spatial-Entity| . 1) 	|encloses| 	(|Spatial-Entity| . 3))))
 	((((|Spatial-Entity| . 1) 	|encloses| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|abuts| 	(|Spatial-Entity| . 3)))
 	 (((|Spatial-Entity| . 1) 	|encloses| 	(|Spatial-Entity| . 3))))
 	((((|Spatial-Entity| . 1) 	|encloses| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|is-along| 	(|Spatial-Entity| . 3)))
 	 (((|Spatial-Entity| . 1) 	|encloses| 	(|Spatial-Entity| . 3))))
 	((((|Spatial-Entity| . 1) 	|encloses| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|is-on| 	(|Spatial-Entity| . 3)))
 	 (((|Spatial-Entity| . 1) 	|encloses| 	(|Spatial-Entity| . 3))))
 	((((|Spatial-Entity| . 1) 	|encloses| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|has-on-it| 	(|Spatial-Entity| . 3)))
 	 (((|Spatial-Entity| . 1) 	|encloses| 	(|Spatial-Entity| . 3))))
 	((((|Spatial-Entity| . 1) 	|encloses| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|is-at| 	(|Spatial-Entity| . 3)))
 	 (((|Spatial-Entity| . 1) 	|encloses| 	(|Spatial-Entity| . 3))))
 	((((|Spatial-Entity| . 1) 	|encloses| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|is-at-of| 	(|Spatial-Entity| . 3)))
 	 (((|Spatial-Entity| . 1) 	|encloses| 	(|Spatial-Entity| . 3))))

 	((((|Spatial-Entity| . 1) 	|is-near| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|is-near| 	(|Spatial-Entity| . 3)))
 	 (((|Spatial-Entity| . 1) 	|is-near| 	(|Spatial-Entity| . 3))))
 	((((|Spatial-Entity| . 1) 	|is-near| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|location| 	(|Place| . 3)))
 	 (((|Spatial-Entity| . 1) 	|is-near| 	(|Place| . 3))))
 	((((|Spatial-Entity| . 1) 	|is-near| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|location-of| 	(|Spatial-Entity| . 3)))
 	 (((|Spatial-Entity| . 1) 	|is-near| 	(|Spatial-Entity| . 3))))
 	((((|Spatial-Entity| . 1) 	|is-near| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|abuts| 	(|Spatial-Entity| . 3)))
 	 (((|Spatial-Entity| . 1) 	|is-near| 	(|Spatial-Entity| . 3))))
 	((((|Spatial-Entity| . 1) 	|is-near| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|is-along| 	(|Spatial-Entity| . 3)))
 	 (((|Spatial-Entity| . 1) 	|is-near| 	(|Spatial-Entity| . 3))))
 	((((|Spatial-Entity| . 1) 	|is-near| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|is-beside| 	(|Spatial-Entity| . 3)))
 	 (((|Spatial-Entity| . 1) 	|is-near| 	(|Spatial-Entity| . 3))))
 	((((|Spatial-Entity| . 1) 	|is-near| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|is-at| 	(|Spatial-Entity| . 3)))
 	 (((|Spatial-Entity| . 1) 	|is-near| 	(|Spatial-Entity| . 3))))
 	((((|Spatial-Entity| . 1) 	|is-near| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|is-between| 	(|Spatial-Entity| . 3)))
 	 (((|Spatial-Entity| . 1) 	|is-near| 	(|Spatial-Entity| . 3))))
 	((((|Spatial-Entity| . 1) 	|is-near| 	(|Spatial-Entity| . 2))
  	  ((|Spatial-Entity| . 2) 	|encloses| 	(|Spatial-Entity| . 3)))
  	 (((|Spatial-Entity| . 1) 	|is-near| 	(|Spatial-Entity| . 3))))
 	((((|Spatial-Entity| . 1) 	|is-near| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|is-on| 	(|Spatial-Entity| . 3)))
 	 (((|Spatial-Entity| . 1) 	|is-near| 	(|Spatial-Entity| . 3))))
 	((((|Spatial-Entity| . 1) 	|is-near| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|has-on-it| 	(|Spatial-Entity| . 3)))
 	 (((|Spatial-Entity| . 1) 	|is-near| 	(|Spatial-Entity| . 3))))
 	((((|Spatial-Entity| . 1) 	|is-near| 	(|Spatial-Entity| . 2))		;; <- ??
 	  ((|Spatial-Entity| . 2) 	|element| 	(|Spatial-Entity| . 3)))
 	 (((|Spatial-Entity| . 1) 	|is-near| 	(|Spatial-Entity| . 3))))

 	((((|Spatial-Entity| . 1) 	|is-on| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|location| 	(|Place| . 3)))
 	 (((|Spatial-Entity| . 1) 	|is-on| 	(|Place| . 3))))
 	((((|Spatial-Entity| . 1) 	|is-on| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|location-of| 	(|Spatial-Entity| . 3)))
 	 (((|Spatial-Entity| . 1) 	|is-on| 	(|Spatial-Entity| . 3))))
 	((((|Spatial-Entity| . 1) 	|is-on| 	(|Spatial-Entity| . 2))		;; <- ??
 	  ((|Spatial-Entity| . 2) 	|element| 	(|Spatial-Entity| . 3)))
 	 (((|Spatial-Entity| . 1) 	|is-on| 	(|Spatial-Entity| . 3))))

 	((((|Spatial-Entity| . 1) 	|has-on-it| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|location| 	(|Place| . 3)))
 	 (((|Spatial-Entity| . 1) 	|has-on-it| 	(|Place| . 3))))
 	((((|Spatial-Entity| . 1) 	|has-on-it| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|location-of| 	(|Spatial-Entity| . 3)))
 	 (((|Spatial-Entity| . 1) 	|has-on-it| 	(|Spatial-Entity| . 3))))
 	((((|Spatial-Entity| . 1) 	|has-on-it| 	(|Spatial-Entity| . 2))		;; <- ??
 	  ((|Spatial-Entity| . 2) 	|element| 	(|Spatial-Entity| . 3)))
 	 (((|Spatial-Entity| . 1) 	|has-on-it| 	(|Spatial-Entity| . 3))))

 	((((|Spatial-Entity| . 1) 	|is-opposite| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|location| 	(|Place| . 3)))
 	 (((|Spatial-Entity| . 1) 	|is-opposite| 	(|Place| . 3))))
 	((((|Spatial-Entity| . 1) 	|is-opposite| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|location-of| 	(|Spatial-Entity| . 3)))
 	 (((|Spatial-Entity| . 1) 	|is-opposite| 	(|Spatial-Entity| . 3))))
 	((((|Spatial-Entity| . 1) 	|is-opposite| 	(|Spatial-Entity| . 2))		;; <- ??
 	  ((|Spatial-Entity| . 2) 	|element| 	(|Spatial-Entity| . 3)))
 	 (((|Spatial-Entity| . 1) 	|is-opposite| 	(|Spatial-Entity| . 3))))

 	((((|Spatial-Entity| . 1) 	|is-outside| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|location| 	(|Place| . 3)))
 	 (((|Spatial-Entity| . 1) 	|is-outside| 	(|Place| . 3))))
 	((((|Spatial-Entity| . 1) 	|is-outside| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|location-of| 	(|Spatial-Entity| . 3)))
 	 (((|Spatial-Entity| . 1) 	|is-outside| 	(|Spatial-Entity| . 3))))
 	((((|Spatial-Entity| . 1) 	|is-outside| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|is-at| 	(|Spatial-Entity| . 3)))
 	 (((|Spatial-Entity| . 1) 	|is-outside| 	(|Spatial-Entity| . 3))))
 	((((|Spatial-Entity| . 1) 	|is-outside| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|encloses| 	(|Spatial-Entity| . 3)))
 	 (((|Spatial-Entity| . 1) 	|is-outside| 	(|Spatial-Entity| . 3))))

 	((((|Spatial-Entity| . 1) |does-not-enclose| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) |location| 		(|Place| . 3)))
 	 (((|Spatial-Entity| . 1) |does-not-enclose| 	(|Place| . 3))))
 	((((|Spatial-Entity| . 1) |does-not-enclose| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) |location-of| 	(|Spatial-Entity| . 3)))
 	 (((|Spatial-Entity| . 1) |does-not-enclose| 	(|Spatial-Entity| . 3))))
 	((((|Spatial-Entity| . 1) |does-not-enclose| 	(|Spatial-Entity| . 2))		;; <- ??
 	  ((|Spatial-Entity| . 2) |element| 		(|Spatial-Entity| . 3)))
 	 (((|Spatial-Entity| . 1) |does-not-enclose| 	(|Spatial-Entity| . 3))))
 	((((|Spatial-Entity| . 1) |does-not-enclose| 	(|Spatial-Entity| . 2))		;; <- ??
 	  ((|Spatial-Entity| . 2) |element-of| 		(|Aggregate| . 3)))
 	 (((|Spatial-Entity| . 1) |does-not-enclose| 	(|Aggregate| . 3))))
 	((((|Spatial-Entity| . 1) |does-not-enclose| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) |abuts| 		(|Spatial-Entity| . 3)))
 	 (((|Spatial-Entity| . 1) |does-not-enclose| 	(|Spatial-Entity| . 3))))
 	((((|Spatial-Entity| . 1) |does-not-enclose| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) |encloses| 		(|Spatial-Entity| . 3)))
 	 (((|Spatial-Entity| . 1) |does-not-enclose| 	(|Spatial-Entity| . 3))))
 	((((|Spatial-Entity| . 1) |does-not-enclose| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) |is-at| 		(|Spatial-Entity| . 3)))
 	 (((|Spatial-Entity| . 1) |does-not-enclose| 	(|Spatial-Entity| . 3))))

 	((((|Spatial-Entity| . 1) 	|is-over| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|location| 	(|Place| . 3)))
 	 (((|Spatial-Entity| . 1) 	|is-over| 	(|Place| . 3))))
 	((((|Spatial-Entity| . 1) 	|is-over| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|location-of| 	(|Spatial-Entity| . 3)))
 	 (((|Spatial-Entity| . 1) 	|is-over| 	(|Spatial-Entity| . 3))))
 	((((|Spatial-Entity| . 1) 	|is-over| 	(|Spatial-Entity| . 2))		;; <- ??
 	  ((|Spatial-Entity| . 2) 	|element| 	(|Spatial-Entity| . 3)))
 	 (((|Spatial-Entity| . 1) 	|is-over| 	(|Spatial-Entity| . 3))))
 	((((|Spatial-Entity| . 1) 	|is-over| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|encloses| 	(|Spatial-Entity| . 3)))
 	 (((|Spatial-Entity| . 1) 	|is-over| 	(|Spatial-Entity| . 3))))
 	((((|Spatial-Entity| . 1) 	|is-over| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|is-on| 	(|Spatial-Entity| . 3)))
 	 (((|Spatial-Entity| . 1) 	|is-over| 	(|Spatial-Entity| . 3))))

 	((((|Spatial-Entity| . 1) 	|is-under| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|location| 	(|Place| . 3)))
 	 (((|Spatial-Entity| . 1) 	|is-under| 	(|Place| . 3))))
 	((((|Spatial-Entity| . 1) 	|is-under| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|location-of| 	(|Spatial-Entity| . 3)))
 	 (((|Spatial-Entity| . 1) 	|is-under| 	(|Spatial-Entity| . 3))))
 	((((|Spatial-Entity| . 1) 	|is-under| 	(|Spatial-Entity| . 2))		;; <- ??
 	  ((|Spatial-Entity| . 2) 	|element| 	(|Spatial-Entity| . 3)))
 	 (((|Spatial-Entity| . 1) 	|is-under| 	(|Spatial-Entity| . 3))))
 	((((|Spatial-Entity| . 1) 	|is-under| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|encloses| 	(|Spatial-Entity| . 3)))
 	 (((|Spatial-Entity| . 1) 	|is-under| 	(|Spatial-Entity| . 3))))
 	((((|Spatial-Entity| . 1) 	|is-under| 	(|Spatial-Entity| . 2))
 	  ((|Spatial-Entity| . 2) 	|has-on-it| 	(|Spatial-Entity| . 3)))
 	 (((|Spatial-Entity| . 1) 	|is-under| 	(|Spatial-Entity| . 3))))

        ((((|Spatial-Entity|  . 0) 	|is-at|      	(|Place| . 1)))
         (((|Spatial-Entity|  . 0) 	|location|   	(|Place| . 1))))
        ((((|Spatial-Entity|  . 0) 	|location|   	(|Place| . 1)))
         (((|Spatial-Entity|  . 0) 	|is-at|      	(|Place| . 1))))

	;;===============================================================  
        ;;===============================================================  
        ;; Temporal transformations.
        ;;===============================================================  
        ;;===============================================================
 	((((|Time-Interval| . 1) |before| 		(|Time-Interval| . 2))
 	  ((|Time-Interval| . 2) |before| 		(|Time-Interval| . 3)))
 	 (((|Time-Interval| . 1) |before| 		(|Time-Interval| . 3))))
 	((((|Time-Interval| . 1) |before| 		(|Time-Interval| . 2))
 	  ((|Time-Interval| . 2) |time| 		(|Time-Interval| . 3)))
 	 (((|Time-Interval| . 1) |before| 		(|Time-Interval| . 3))))
 	((((|Time-Interval| . 1) |before| 		(|Time-Interval| . 2))		;; <- ??
 	  ((|Time-Interval| . 2) |time-of| 		(|Event| . 3)))
 	 (((|Time-Interval| . 1) |before| 		(|Event| . 3))))
 	((((|Time-Interval| . 1) |before| 		(|Time-Interval| . 2))
 	  ((|Time-Interval| . 2) |temporally-starts| 	(|Time-Interval| . 3)))
 	 (((|Time-Interval| . 1) |before| 		(|Time-Interval| . 3))))
 	((((|Time-Interval| . 1) |before| 		(|Time-Interval| . 2))
 	  ((|Time-Interval| . 2) |temporally-started-by| (|Time-Interval| . 3)))
	 (((|Time-Interval| . 1) |before| 		(|Time-Interval| . 3))))
 	((((|Time-Interval| . 1) |before| 		(|Time-Interval| . 2))
 	  ((|Time-Interval| . 2) |temporally-meets| 	(|Time-Interval| . 3)))
 	 (((|Time-Interval| . 1) |before| 		(|Time-Interval| . 3))))
 	((((|Time-Interval| . 1) |before| 		(|Time-Interval| . 2))
 	  ((|Time-Interval| . 2) |temporally-contains| 	(|Time-Interval| . 3)))
 	 (((|Time-Interval| . 1) |before| 		(|Time-Interval| . 3))))

 	((((|Time-Interval| . 1) |after| 		(|Time-Interval| . 2))
 	  ((|Time-Interval| . 2) |time| 		(|Time-Interval| . 3)))
 	 (((|Time-Interval| . 1) |after| 		(|Time-Interval| . 3))))
 	((((|Time-Interval| . 1) |after| 		(|Time-Interval| . 2))		;; <- ??
 	  ((|Time-Interval| . 2) |time-of| 		(|Event| . 3)))
 	 (((|Time-Interval| . 1) |after| 		(|Event| . 3))))
 	((((|Time-Interval| . 1) |after| 		(|Time-Interval| . 2))
 	  ((|Time-Interval| . 2) |temporally-met-by| 	(|Time-Interval| . 3)))
 	 (((|Time-Interval| . 1) |after| 		(|Time-Interval| . 3))))
 	((((|Time-Interval| . 1) |after| 		(|Time-Interval| . 2))
 	  ((|Time-Interval| . 2) |temporally-started-by| (|Time-Interval| . 3)))
 	 (((|Time-Interval| . 1) |after| 		(|Time-Interval| . 3))))
 	((((|Time-Interval| . 1) |after| 		(|Time-Interval| . 2))
 	  ((|Time-Interval| . 2) |temporally-finished-by| (|Time-Interval| . 3)))
 	 (((|Time-Interval| . 1) |after| 		(|Time-Interval| . 3))))

 	((((|Time-Interval| . 1) |during| 		(|Time-Interval| . 2))
 	  ((|Time-Interval| . 2) |during| 		(|Time-Interval| . 3)))
 	 (((|Time-Interval| . 1) |during| 		(|Time-Interval| . 3))))
 	((((|Time-Interval| . 1) |during| 		(|Time-Interval| . 2))
 	  ((|Time-Interval| . 2) |time| 		(|Time-Interval| . 3)))
 	 (((|Time-Interval| . 1) |during| 		(|Time-Interval| . 3))))
 	((((|Time-Interval| . 1) |during| 		(|Time-Interval| . 2))		;; <- ??
 	  ((|Time-Interval| . 2) |time-of| 		(|Event| . 3)))
 	 (((|Time-Interval| . 1) |during| 		(|Event| . 3))))

 	((((|Time-Interval| . 1) |temporally-contains| 	(|Time-Interval| . 2))
 	  ((|Time-Interval| . 2) |time| 		(|Time-Interval| . 3)))
 	 (((|Time-Interval| . 1) |temporally-contains| 	(|Time-Interval| . 3))))
 	((((|Time-Interval| . 1) |temporally-contains| 	(|Time-Interval| . 2))		;; <- ??
 	  ((|Time-Interval| . 2) |time-of| 		(|Event| . 3)))
 	 (((|Time-Interval| . 1) |temporally-contains| 	(|Event| . 3))))

 	((((|Time-Interval| . 1) |temporally-overlaps| 	(|Time-Interval| . 2))
 	  ((|Time-Interval| . 2) |time| 		(|Time-Interval| . 3)))
 	 (((|Time-Interval| . 1) |temporally-overlaps|	(|Time-Interval| . 3))))
 	((((|Time-Interval| . 1) |temporally-overlaps| 	(|Time-Interval| . 2))		;; <- ??
 	  ((|Time-Interval| . 2) |time-of| 		(|Event| . 3)))
 	 (((|Time-Interval| . 1) |temporally-overlaps| 	(|Event| . 3))))
 	((((|Time-Interval| . 1) |temporally-overlaps| 	(|Time-Interval| . 2))
 	  ((|Time-Interval| . 2) |temporally-starts| 	(|Time-Interval| . 3)))
 	 (((|Time-Interval| . 1) |temporally-overlaps|	(|Time-Interval| . 3))))

 	((((|Time-Interval| . 1) |temporally-overlapped-by|	(|Time-Interval| . 2))
 	  ((|Time-Interval| . 2) |time| 			(|Time-Interval| . 3)))
 	 (((|Time-Interval| . 1) |temporally-overlapped-by|	(|Time-Interval| . 3))))
 	((((|Time-Interval| . 1) |temporally-overlapped-by|	(|Time-Interval| . 2))	;; <- ??
 	  ((|Time-Interval| . 2) |time-of| 			(|Event| . 3)))
 	 (((|Time-Interval| . 1) |temporally-overlapped-by| 	(|Event| . 3))))

 	((((|Time-Interval| . 1) |temporally-meets| 	(|Time-Interval| . 2))
 	  ((|Time-Interval| . 2) |time| 		(|Time-Interval| . 3)))
 	 (((|Time-Interval| . 1) |temporally-meets| 	(|Time-Interval| . 3))))
 	((((|Time-Interval| . 1) |temporally-meets| 	(|Time-Interval| . 2))		;; <- ??
 	  ((|Time-Interval| . 2) |time-of| 		(|Event| . 3)))
 	 (((|Time-Interval| . 1) |temporally-meets| 	(|Event| . 3))))

 	((((|Time-Interval| . 1) |temporally-starts| 	(|Time-Interval| . 2))
 	  ((|Time-Interval| . 2) |time| 		(|Time-Interval| . 3)))
 	 (((|Time-Interval| . 1) |temporally-starts| 	(|Time-Interval| . 3))))
 	((((|Time-Interval| . 1) |temporally-starts| 	(|Time-Interval| . 2))		;; <- ??
 	  ((|Time-Interval| . 2) |time-of| 		(|Event| . 3)))
 	 (((|Time-Interval| . 1) |temporally-starts| 	(|Event| . 3))))
 	((((|Time-Interval| . 1) |temporally-starts| 	(|Time-Interval| . 2))
 	  ((|Time-Interval| . 2) |temporally-starts| 	(|Time-Interval| . 3)))
 	 (((|Time-Interval| . 1) |temporally-starts| 	(|Time-Interval| . 3))))
 	
	((((|Time-Interval| . 1) |temporally-started-by| 	(|Time-Interval| . 2))
   	  ((|Time-Interval| . 2) |time| 			(|Time-Interval| . 3)))
	 (((|Time-Interval| . 1) |temporally-started-by|	(|Time-Interval| . 3))))
 	((((|Time-Interval| . 1) |temporally-started-by|	(|Time-Interval| . 2))	;; <- ??
	  ((|Time-Interval| . 2) |time-of| 			(|Event| . 3)))
 	 (((|Time-Interval| . 1) |temporally-started-by| 	(|Event| . 3))))

 	((((|Time-Interval| . 1) |temporally-finishes| 	(|Time-Interval| . 2))
 	  ((|Time-Interval| . 2) |time| 		(|Time-Interval| . 3)))
 	 (((|Time-Interval| . 1) |temporally-finishes| 	(|Time-Interval| . 3))))
 	((((|Time-Interval| . 1) |temporally-finishes| 	(|Time-Interval| . 2))		;; <- ??
 	  ((|Time-Interval| . 2) |time-of| 		(|Event| . 3)))
 	 (((|Time-Interval| . 1) |temporally-finishes| 	(|Event| . 3))))

 	((((|Time-Interval| . 1) |temporally-finished-by| 	(|Time-Interval| . 2))
 	  ((|Time-Interval| . 2) |time| 			(|Time-Interval| . 3)))
  	 (((|Time-Interval| . 1) |temporally-finished-by|	(|Time-Interval| . 3))))
 	((((|Time-Interval| . 1) |temporally-finished-by|	(|Time-Interval| . 2))	;; <- ??
 	  ((|Time-Interval| . 2) |time-of| 			(|Event| . 3)))
 	 (((|Time-Interval| . 1) |temporally-finished-by| 	(|Event| . 3))))

	((((|Time-Interval| . 1)    |end-time|      	(|End-Time-Value| . 2))
          ((|End-Time-Value| . 2)   |before|        	(|Start-Time-Value| . 3))
          ((|Start-Time-Value| . 3) |start-time-of| 	(|Time-Interval| . 4)))
         (((|Time-Interval| . 1)    |before|        	(|Time-Interval| . 4))))

	;;===============================================================  
	;; Misc. xforms. We may get rid of these in the future.
        ;;===============================================================  
 	((((|Event| . x) 		|result| 		    (|Tangible-Entity| . y))
;;   	  ((|Tangible-Entity| . y) 	|has-basic-structural-unit| (|Tangible-Entity| . z)))
   	  ((|Tangible-Entity| . y) 	|has-part| 		    (|Tangible-Entity| . z)))
  	 (((|Event| . x) 		|result| 		    (|Tangible-Entity| . z))))

        ((((|Event| . 1)                |object|        	    (|Information| . 2))
          ((|Information| . 2)          |information-content-of|    (|Message| 	   . 3)))
         (((|Event| . 1)                |object|        	    (|Message| 	   . 3))))

        ((((|Event|  . 1)               |object|        	    (|Entity| . 2))
          ((|Entity| . 2)          	|encloses|    		    (|Entity| . 3)))
         (((|Event|  . 1)               |object|        	    (|Entity| . 3))))

;; KB: these next two should probably be removed since many
;; types of Create (in particular, Copy, etc.) require distinct
;; object and result
        ((((|Create|  . 0) 		|result|		(|Entity| . 1)))
         (((|Create|  . 0) 		|object|		(|Entity| . 1))))
        ((((|Create|  . 0) 		|object|		(|Entity| . 1)))
         (((|Create|  . 0) 		|result|		(|Entity| . 1))))

	;; *PZY*: 05/31/06 -- These rules are obselete.
        ;; ((((|Event|  . 1)            |object|        	(|Role|   . 2))
        ;;   ((|Role|   . 2)          	|played-by|    		(|Entity| . 3)))
        ;;  (((|Event|  . 1)            |object|        	(|Entity| . 3))))
        ;; ((((|Event|  . 1)            |agent|        		(|Role|   . 2))
        ;;   ((|Role|   . 2)          	|played-by|    		(|Entity| . 3)))
        ;;  (((|Event|  . 1)            |agent|        		(|Entity| . 3))))
        ;; ((((|Event|  . 1)            |recipient|        	(|Role|   . 2))
        ;;   ((|Role|   . 2)          	|played-by|    		(|Entity| . 3)))
        ;;  (((|Event|  . 1)            |recipient|        	(|Entity| . 3))))
        ;; ((((|Event|  . 1)            |donor|        		(|Role|   . 2))
        ;;   ((|Role|   . 2)          	|played-by|    		(|Entity| . 3)))
        ;;  (((|Event|  . 1)            |donor|        		(|Entity| . 3))))
        ;; ((((|Event|  . 1)            |beneficiary|        	(|Role|   . 2))		;; <-- *PZY*: 10/21/05
        ;;   ((|Role|   . 2)          	|played-by|    		(|Entity| . 3)))
        ;;  (((|Event|  . 1)            |beneficiary|        	(|Entity| . 3))))
	;; *PZY*: Before 05/31/06
        ;; ((((|Event|  . 1)            |instrument|        	(|Role|   . 2))
        ;;   ((|Role|   . 2)          	|played-by|    		(|Entity| . 3)))
        ;;  (((|Event|  . 1)            |instrument|        	(|Entity| . 3))))

        ((((|Event|  . 1)               |object|        	(|Entity| . 2))
          ((|Entity| . 2)          	|plays|    		(|Role|   . 3)))
         (((|Event|  . 1)               |object|        	(|Role|   . 3))))
        ((((|Event|  . 1)               |agent|        		(|Entity| . 2))
          ((|Entity| . 2)          	|plays|    		(|Role|   . 3)))
         (((|Event|  . 1)               |agent|        		(|Role|   . 3))))
        ((((|Event|  . 1)               |recipient|        	(|Entity| . 2))
          ((|Entity| . 2)          	|plays|    		(|Role|   . 3)))
         (((|Event|  . 1)               |recipient|        	(|Role|   . 3))))
        ((((|Event|  . 1)               |donor|        		(|Entity| . 2))
          ((|Entity| . 2)          	|plays|    		(|Role|   . 3)))
         (((|Event|  . 1)               |donor|        		(|Role|   . 3))))
        ((((|Event|  . 1)               |beneficiary|        	(|Entity| . 2))		;; <-- *PZY*: 10/21/05
          ((|Entity| . 2)          	|plays|    		(|Role|   . 3)))
         (((|Event|  . 1)               |beneficiary|        	(|Role|   . 3))))
        ((((|Event|  . 1)               |instrument|        	(|Entity| . 2))
          ((|Entity| . 2)          	|plays|    		(|Role|   . 3)))
         (((|Event|  . 1)               |instrument|        	(|Role|   . 3))))
        ((((|Event|  . 1)               |experiencer|           (|Entity| . 2))  	;; <-- *PZY*: 06/07/06
          ((|Entity| . 2)               |plays|                 (|Role|   . 3))) 
         (((|Event|  . 1)               |experiencer|           (|Role|   . 3))))

))

;;;=====================================================================
