;; 
;; $Id: chem-defs.lisp,v 1.577 2010/01/22 15:59:53 kbarker Exp $ 
;;

 (unless (find-package :km) (make-package :km)) 
 (in-package :km) 
 (setq *using-km-package* t)

 (defparameter *chemical-defs-table* nil)
 (defun setup-chem-def-table ()
  (if (null *chemical-defs-table*)
    (setf *chemical-defs-table* '(
   (KM::|Ag3PO4| ("silver phosphate")
    (:|seq| (:|pair| 3 KM::|Ag-Plus|) (:|pair| 1 KM::|PO4-Minus-3|))
    (:|seq| (:|pair| 3 KM::|Ag|) (:|pair| 1 KM::P) (:|pair| 4 KM::O))
    (:|seq| (:|pair| 3 KM::|Ag|) (:|pair| 1 KM::P) (:|pair| 4 KM::O))
    NIL NIL NIL)
   (KM::|Al2O3| ("aluminum oxide")
    (:|seq| (:|pair| 2 KM::|Al-Plus-3|) (:|pair| 3 KM::|O-Minus-2|))
    (:|seq| (:|pair| 2 KM::|Al|) (:|pair| 3 KM::O))
    (:|seq| (:|pair| 2 KM::|Al|) (:|pair| 3 KM::O)) NIL NIL NIL)
   (KM::|AlCl3| ("aluminum chloride")
    (:|seq| (:|pair| 1 KM::|Al-Plus-3|) (:|pair| 3 KM::|Cl-Minus|))
    (:|seq| (:|pair| 1 KM::|Al|) (:|pair| 3 KM::|Cl|))
    (:|seq| (:|pair| 1 KM::|Al|) (:|pair| 3 KM::|Cl|)) NIL NIL NIL)
   (KM::|AuCl3|
    ("gold(iii) chloride" "auric chloride" "gold (iii) chloride")
    (:|seq| (:|pair| 1 KM::|Au-Plus-3|) (:|pair| 3 KM::|Cl-Minus|))
    (:|seq| (:|pair| 1 KM::|Au|) (:|pair| 3 KM::|Cl|))
    (:|seq| (:|pair| 1 KM::|Au|) (:|pair| 3 KM::|Cl|)) NIL NIL NIL)
   (KM::|BaCl2| ("barium chloride")
    (:|seq| (:|pair| 1 KM::|Ba-Plus-2|) (:|pair| 2 KM::|Cl-Minus|))
    (:|seq| (:|pair| 1 KM::|Ba|) (:|pair| 2 KM::|Cl|))
    (:|seq| (:|pair| 1 KM::|Ba|) (:|pair| 2 KM::|Cl|)) NIL NIL NIL)
   (KM::|BaSO4| ("barium sulfate")
    (:|seq| (:|pair| 1 KM::|Ba-Plus-2|) (:|pair| 1 KM::|SO4-Minus-2|))
    (:|seq| (:|pair| 1 KM::|Ba|) (:|pair| 1 KM::S) (:|pair| 4 KM::O))
    (:|seq| (:|pair| 1 KM::|Ba|) (:|pair| 1 KM::S) (:|pair| 4 KM::O))
    NIL NIL NIL)
   (KM::|Ba_NO3_2| ("barium nitrate")
    (:|seq| (:|pair| 1 KM::|Ba-Plus-2|) (:|pair| 2 KM::|NO3-Minus|))
    (:|seq| (:|pair| 1 KM::|Ba|)
     (:|pair| 2 (:|seq| (:|pair| 1 KM::N) (:|pair| 3 KM::O))))
    (:|seq| (:|pair| 1 KM::|Ba|) (:|pair| 2 KM::N) (:|pair| 6 KM::O))
    NIL NIL NIL)
   (KM::|Ba_OH_2| ("barium hydroxide")
    (:|seq| (:|pair| 1 KM::|Ba-Plus-2|) (:|pair| 2 KM::|OH-Minus|))
    (:|seq| (:|pair| 1 KM::|Ba|)
     (:|pair| 2 (:|seq| (:|pair| 1 KM::O) (:|pair| 1 KM::H))))
    (:|seq| (:|pair| 1 KM::|Ba|) (:|pair| 2 KM::O) (:|pair| 2 KM::H))
    NIL NIL NIL)
   (KM::H2C2O4 ("oxalic acid" "hydrogen oxalate")
    (:|seq| (:|pair| 2 KM::|H-Plus|) (:|pair| 1 KM::|C2O4-Minus-2|))
    (:|seq| (:|pair| 2 KM::H) (:|pair| 2 KM::C) (:|pair| 4 KM::O))
    (:|seq| (:|pair| 2 KM::H) (:|pair| 2 KM::C) (:|pair| 4 KM::O)) NIL
    NIL NIL)
   (KM::H2C4H4O6
    ("succinic acid" "butanedioc acid" "hydrogen tartrate")
    (:|seq| (:|pair| 2 KM::|H-Plus|) (:|pair| 1 KM::|C4H4O6-Minus-2|))
    (:|seq| (:|pair| 2 KM::H) (:|pair| 4 KM::C) (:|pair| 4 KM::H)
     (:|pair| 6 KM::O))
    (:|seq| (:|pair| 6 KM::H) (:|pair| 4 KM::C) (:|pair| 6 KM::O)) NIL
    NIL NIL)
   (KM::H2C6H6O6 ("ascoribic acid" "vitamin c" "hydrogen ascorbate")
    (:|seq| (:|pair| 2 KM::|H-Plus|) (:|pair| 1 KM::|C6H6O6-Minus-2|))
    (:|seq| (:|pair| 2 KM::H) (:|pair| 6 KM::C) (:|pair| 6 KM::H)
     (:|pair| 6 KM::O))
    (:|seq| (:|pair| 8 KM::H) (:|pair| 6 KM::C) (:|pair| 6 KM::O)) NIL
    NIL NIL)
   (KM::H2CO3 ("acarbonic acid" "bicarbonate" "hydrogen carbonate")
    (:|seq| (:|pair| 2 KM::|H-Plus|) (:|pair| 1 KM::|CO3-Minus-2|))
    (:|seq| (:|pair| 2 KM::H) (:|pair| 1 KM::C) (:|pair| 3 KM::O))
    (:|seq| (:|pair| 2 KM::H) (:|pair| 1 KM::C) (:|pair| 3 KM::O)) NIL
    NIL NIL)
   (KM::H2O2 ("hydrogen peroxide" "hydrogen dioxide")
    (:|seq| (:|pair| 2 KM::|H-Plus|) (:|pair| 1 KM::|O2-Minus-2|))
    (:|seq| (:|pair| 2 KM::H) (:|pair| 2 KM::O))
    (:|seq| (:|pair| 2 KM::H) (:|pair| 2 KM::O)) NIL NIL NIL)
   (KM::H2S ("hydrogen sulfide")
    (:|seq| (:|pair| 2 KM::|H-Plus|) (:|pair| 1 KM::|S-Minus-2|))
    (:|seq| (:|pair| 2 KM::H) (:|pair| 1 KM::S))
    (:|seq| (:|pair| 2 KM::H) (:|pair| 1 KM::S)) NIL NIL NIL)
   (KM::H2SO3 ("sulfurous acid" "hydrogen sulfite")
    (:|seq| (:|pair| 2 KM::|H-Plus|) (:|pair| 1 KM::|SO3-Minus-2|))
    (:|seq| (:|pair| 2 KM::H) (:|pair| 1 KM::S) (:|pair| 3 KM::O))
    (:|seq| (:|pair| 2 KM::H) (:|pair| 1 KM::S) (:|pair| 3 KM::O)) NIL
    NIL NIL)
   (KM::H2SO4 ("sulfuric acid" "hydrogen sulfate")
    (:|seq| (:|pair| 2 KM::|H-Plus|) (:|pair| 1 KM::|SO4-Minus-2|))
    (:|seq| (:|pair| 2 KM::H) (:|pair| 1 KM::S) (:|pair| 4 KM::O))
    (:|seq| (:|pair| 2 KM::H) (:|pair| 1 KM::S) (:|pair| 4 KM::O)) NIL
    NIL NIL)
   (KM::|H2SeO3| ("selenous acid" "hydrogen selenite")
    (:|seq| (:|pair| 2 KM::|H-Plus|) (:|pair| 1 KM::|SeO3-Minus-2|))
    (:|seq| (:|pair| 2 KM::H) (:|pair| 1 KM::|Se|) (:|pair| 3 KM::O))
    (:|seq| (:|pair| 2 KM::H) (:|pair| 1 KM::|Se|) (:|pair| 3 KM::O))
    NIL NIL NIL)
   (KM::|H2SiF6|
    ("fluorosilicic acid" "hexafluorosilicic acid"
     "hydrogen hexafluorosilicate" "hydrogen silver hexafluoride")
    (:|seq| (:|pair| 2 KM::|H-Plus|) (:|pair| 1 KM::|SiF6-Minus-2|))
    (:|seq| (:|pair| 2 KM::H) (:|pair| 1 KM::|Si|) (:|pair| 6 KM::F))
    (:|seq| (:|pair| 2 KM::H) (:|pair| 1 KM::|Si|) (:|pair| 6 KM::F))
    NIL NIL NIL)
   (KM::|H3AsO3| ("arsenous acid" "hydrogen arsenite")
    (:|seq| (:|pair| 3 KM::|H-Plus|) (:|pair| 1 KM::|AsO3-Minus-3|))
    (:|seq| (:|pair| 3 KM::H) (:|pair| 1 KM::|As|) (:|pair| 3 KM::O))
    (:|seq| (:|pair| 3 KM::H) (:|pair| 1 KM::|As|) (:|pair| 3 KM::O))
    NIL NIL NIL)
   (KM::|H3AsO4| ("arsenic acid" "hydrogen arsenate")
    (:|seq| (:|pair| 3 KM::|H-Plus|) (:|pair| 1 KM::|AsO4-Minus-3|))
    (:|seq| (:|pair| 3 KM::H) (:|pair| 1 KM::|As|) (:|pair| 4 KM::O))
    (:|seq| (:|pair| 3 KM::H) (:|pair| 1 KM::|As|) (:|pair| 4 KM::O))
    NIL NIL NIL)
   (KM::H3BO3 ("boric acid" "hydrogen borate")
    (:|seq| (:|pair| 3 KM::|H-Plus|) (:|pair| 1 KM::|BO3-Minus-3|))
    (:|seq| (:|pair| 3 KM::H) (:|pair| 1 KM::B) (:|pair| 3 KM::O))
    (:|seq| (:|pair| 3 KM::H) (:|pair| 1 KM::B) (:|pair| 3 KM::O)) NIL
    NIL NIL)
   (KM::H3C6H5O7
    ("citric acid" "hydrogen 2-hydroxypropane-1,2,3-tricarboxylate")
    (:|seq| (:|pair| 3 KM::|H-Plus|) (:|pair| 1 KM::|C6H5O7-Minus-3|))
    (:|seq| (:|pair| 3 KM::H) (:|pair| 6 KM::C) (:|pair| 5 KM::H)
     (:|pair| 7 KM::O))
    (:|seq| (:|pair| 8 KM::H) (:|pair| 6 KM::C) (:|pair| 7 KM::O)) NIL
    NIL NIL)
   (KM::H3PO3 ("phosphorous acid" "hydrogen phosphite")
    (:|seq| (:|pair| 3 KM::|H-Plus|) (:|pair| 1 KM::|PO3-Minus-3|))
    (:|seq| (:|pair| 3 KM::H) (:|pair| 1 KM::P) (:|pair| 3 KM::O))
    (:|seq| (:|pair| 3 KM::H) (:|pair| 1 KM::P) (:|pair| 3 KM::O)) NIL
    NIL NIL)
   (KM::H3PO4 ("phosphoric acid" "hydrogen phosphate")
    (:|seq| (:|pair| 3 KM::|H-Plus|) (:|pair| 1 KM::|PO4-Minus-3|))
    (:|seq| (:|pair| 3 KM::H) (:|pair| 1 KM::P) (:|pair| 4 KM::O))
    (:|seq| (:|pair| 3 KM::H) (:|pair| 1 KM::P) (:|pair| 4 KM::O)) NIL
    NIL NIL)
   (KM::H4P2O7 ("pyrophosphoric acid" "hydrogen pyrophosphate")
    (:|seq| (:|pair| 4 KM::|H-Plus|) (:|pair| 1 KM::|P2O7-Minus-4|))
    (:|seq| (:|pair| 4 KM::H) (:|pair| 2 KM::P) (:|pair| 7 KM::O))
    (:|seq| (:|pair| 4 KM::H) (:|pair| 2 KM::P) (:|pair| 7 KM::O)) NIL
    NIL NIL)
   (KM::H5IO6 ("orthoperiodic acid" "hydrogen orthoperiodate")
    (:|seq| (:|pair| 5 KM::|H-Plus|) (:|pair| 1 KM::|IO6-Minus-5|))
    (:|seq| (:|pair| 5 KM::H) (:|pair| 1 KM::I) (:|pair| 6 KM::O))
    (:|seq| (:|pair| 5 KM::H) (:|pair| 1 KM::I) (:|pair| 6 KM::O)) NIL
    NIL NIL)
   (KM::|HBr| ("hydrobromic acid" "hydrogen bromide")
    (:|seq| (:|pair| 1 KM::|H-Plus|) (:|pair| 1 KM::|Br-Minus|))
    (:|seq| (:|pair| 1 KM::H) (:|pair| 1 KM::|Br|))
    (:|seq| (:|pair| 1 KM::H) (:|pair| 1 KM::|Br|)) NIL NIL NIL)
   (KM::|HBrO| ("hypobromous acid" "hydrogen hypobromite")
    (:|seq| (:|pair| 1 KM::|H-Plus|) (:|pair| 1 KM::|BrO-Minus|))
    (:|seq| (:|pair| 1 KM::H) (:|pair| 1 KM::|Br|) (:|pair| 1 KM::O))
    (:|seq| (:|pair| 1 KM::H) (:|pair| 1 KM::|Br|) (:|pair| 1 KM::O))
    NIL NIL NIL)
   (KM::|HC2H2O2Cl| ("chloride acetate" "hydrogen chloroacetate")
    (:|seq| (:|pair| 1 KM::|H-Plus|) (:|pair| 1 KM::|C2H2O2Cl-Minus|))
    (:|seq| (:|pair| 1 KM::H) (:|pair| 2 KM::C) (:|pair| 2 KM::H)
     (:|pair| 2 KM::O) (:|pair| 1 KM::|Cl|))
    (:|seq| (:|pair| 3 KM::H) (:|pair| 2 KM::C) (:|pair| 2 KM::O)
     (:|pair| 1 KM::|Cl|))
    NIL NIL NIL)
   (KM::HCHO2 ("formic acid" "hydrogen formate")
    (:|seq| (:|pair| 1 KM::|H-Plus|) (:|pair| 1 KM::|CHO2-Minus|))
    (:|seq| (:|pair| 1 KM::H) (:|pair| 1 KM::C) (:|pair| 1 KM::H)
     (:|pair| 2 KM::O))
    (:|seq| (:|pair| 2 KM::H) (:|pair| 1 KM::C) (:|pair| 2 KM::O)) NIL
    NIL NIL)
   (KM::HCN ("hydrocyanic acid" "hydrogen cyanide")
    (:|seq| (:|pair| 1 KM::|H-Plus|) (:|pair| 1 KM::|CN-Minus|))
    (:|seq| (:|pair| 1 KM::H) (:|pair| 1 KM::C) (:|pair| 1 KM::N))
    (:|seq| (:|pair| 1 KM::H) (:|pair| 1 KM::C) (:|pair| 1 KM::N)) NIL
    NIL NIL)
   (KM::HCNO ("cyanic acid" "hydrogen cyanate")
    (:|seq| (:|pair| 1 KM::|H-Plus|) (:|pair| 1 KM::|CNO-Minus|))
    (:|seq| (:|pair| 1 KM::H) (:|pair| 1 KM::C) (:|pair| 1 KM::N)
     (:|pair| 1 KM::O))
    (:|seq| (:|pair| 1 KM::H) (:|pair| 1 KM::C) (:|pair| 1 KM::N)
     (:|pair| 1 KM::O))
    NIL NIL NIL)
   (KM::|HCl| ("hydrochloric acid" "hydrogen chloride")
    (:|seq| (:|pair| 1 KM::|H-Plus|) (:|pair| 1 KM::|Cl-Minus|))
    (:|seq| (:|pair| 1 KM::H) (:|pair| 1 KM::|Cl|))
    (:|seq| (:|pair| 1 KM::H) (:|pair| 1 KM::|Cl|)) NIL NIL NIL)
   (KM::|HClO| ("hypochlorous acid" "hydrogen hypochlorite")
    (:|seq| (:|pair| 1 KM::|H-Plus|) (:|pair| 1 KM::|ClO-Minus|))
    (:|seq| (:|pair| 1 KM::H) (:|pair| 1 KM::|Cl|) (:|pair| 1 KM::O))
    (:|seq| (:|pair| 1 KM::H) (:|pair| 1 KM::|Cl|) (:|pair| 1 KM::O))
    NIL NIL NIL)
   (KM::|HClO2| ("hydrogen chlorite")
    (:|seq| (:|pair| 1 KM::|H-Plus|) (:|pair| 1 KM::|ClO2-Minus|))
    (:|seq| (:|pair| 1 KM::H) (:|pair| 1 KM::|Cl|) (:|pair| 2 KM::O))
    (:|seq| (:|pair| 1 KM::H) (:|pair| 1 KM::|Cl|) (:|pair| 2 KM::O))
    NIL NIL NIL)
   (KM::|HF-Compound| ("hydrogen fluoride" "hydrofluoric acid")
    (:|seq| (:|pair| 1 KM::|H-Plus|) (:|pair| 1 KM::|F-Minus|))
    (:|seq| (:|pair| 1 KM::H) (:|pair| 1 KM::F))
    (:|seq| (:|pair| 1 KM::H) (:|pair| 1 KM::F)) NIL NIL NIL)
   (KM::HI ("hydroiodic acid" "hydrogen iodide")
    (:|seq| (:|pair| 1 KM::|H-Plus|) (:|pair| 1 KM::|I-Minus|))
    (:|seq| (:|pair| 1 KM::H) (:|pair| 1 KM::I))
    (:|seq| (:|pair| 1 KM::H) (:|pair| 1 KM::I)) NIL NIL NIL)
   (KM::HIO ("hypoiodous acid" "hydrogen hypoiodite")
    (:|seq| (:|pair| 1 KM::|H-Plus|) (:|pair| 1 KM::|IO-Minus|))
    (:|seq| (:|pair| 1 KM::H) (:|pair| 1 KM::I) (:|pair| 1 KM::O))
    (:|seq| (:|pair| 1 KM::H) (:|pair| 1 KM::I) (:|pair| 1 KM::O)) NIL
    NIL NIL)
   (KM::HIO3 ("iodic acid" "hydrogen iodate")
    (:|seq| (:|pair| 1 KM::|H-Plus|) (:|pair| 1 KM::|IO3-Minus|))
    (:|seq| (:|pair| 1 KM::H) (:|pair| 1 KM::I) (:|pair| 3 KM::O))
    (:|seq| (:|pair| 1 KM::H) (:|pair| 1 KM::I) (:|pair| 3 KM::O)) NIL
    NIL NIL)
   (KM::HN3 ("hydrogen azide")
    (:|seq| (:|pair| 1 KM::|H-Plus|) (:|pair| 1 KM::|N3-Minus|))
    (:|seq| (:|pair| 1 KM::H) (:|pair| 3 KM::N))
    (:|seq| (:|pair| 1 KM::H) (:|pair| 3 KM::N)) NIL NIL NIL)
   (KM::HNO2 ("nitrous acid" "hydrogen nitrite")
    (:|seq| (:|pair| 1 KM::|H-Plus|) (:|pair| 1 KM::|NO2-Minus|))
    (:|seq| (:|pair| 1 KM::H) (:|pair| 1 KM::N) (:|pair| 2 KM::O))
    (:|seq| (:|pair| 1 KM::H) (:|pair| 1 KM::N) (:|pair| 2 KM::O)) NIL
    NIL NIL)
   (KM::C2H5NH2 ("ethylamine") NIL
    (:|seq| (:|pair| 2 KM::C) (:|pair| 5 KM::H) (:|pair| 1 KM::N)
     (:|pair| 2 KM::H))
    (:|seq| (:|pair| 2 KM::C) (:|pair| 7 KM::H) (:|pair| 1 KM::N)) NIL
    NIL NIL)
   (KM::C5H5N ("pyridine") NIL
    (:|seq| (:|pair| 5 KM::C) (:|pair| 5 KM::H) (:|pair| 1 KM::N))
    (:|seq| (:|pair| 5 KM::C) (:|pair| 5 KM::H) (:|pair| 1 KM::N)) NIL
    NIL NIL)
   (KM::C6H5COOH ("benzoic acid" "hydrogen benzoate")
    (:|seq| (:|pair| 1 KM::|H-Plus|) (:|pair| 1 KM::|C7H5O2-Minus|))
    (:|seq| (:|pair| 1 KM::H) (:|pair| 7 KM::C) (:|pair| 5 KM::H)
     (:|pair| 2 KM::O))
    (:|seq| (:|pair| 6 KM::H) (:|pair| 7 KM::C) (:|pair| 2 KM::O)) NIL
    NIL NIL)
   (KM::C6H5NH2 ("aniline" "phenylamine") NIL
    (:|seq| (:|pair| 6 KM::C) (:|pair| 5 KM::H) (:|pair| 1 KM::N)
     (:|pair| 2 KM::H))
    (:|seq| (:|pair| 6 KM::C) (:|pair| 7 KM::H) (:|pair| 1 KM::N)) NIL
    NIL NIL)
   (KM::C6H5OH ("phenol" "hydrogen phenolate")
    (:|seq| (:|pair| 1 KM::|H-Plus|) (:|pair| 1 KM::|C6H5O-Minus|))
    (:|seq| (:|pair| 1 KM::H) (:|pair| 6 KM::C) (:|pair| 5 KM::H)
     (:|pair| 1 KM::O))
    (:|seq| (:|pair| 6 KM::H) (:|pair| 6 KM::C) (:|pair| 1 KM::O)) NIL
    NIL NIL)
   (KM::CH2_COOH_2 ("malonic acid" "hydrogen malonate")
    (:|seq| (:|pair| 2 KM::|H-Plus|) (:|pair| 1 KM::|C3H2O4-Minus-2|))
    (:|seq| (:|pair| 2 KM::H) (:|pair| 3 KM::C) (:|pair| 2 KM::H)
     (:|pair| 4 KM::O))
    (:|seq| (:|pair| 4 KM::H) (:|pair| 3 KM::C) (:|pair| 4 KM::O)) NIL
    NIL NIL)
   (KM::CH3CH2COOH
    ("propianic acid" "propanoic acid" "hydrogen propanoate")
    (:|seq| (:|pair| 1 KM::|H-Plus|) (:|pair| 1 KM::|C2H5COO-Minus|))
    (:|seq| (:|pair| 1 KM::H) (:|pair| 3 KM::C) (:|pair| 5 KM::H)
     (:|pair| 2 KM::O))
    (:|seq| (:|pair| 6 KM::H) (:|pair| 3 KM::C) (:|pair| 2 KM::O)) NIL
    NIL NIL)
   (KM::CH3CHOHCOOH ("lactic acid" "hydrogen lactate")
    (:|seq| (:|pair| 1 KM::|H-Plus|) (:|pair| 1 KM::|C3H5O3-Minus|))
    (:|seq| (:|pair| 1 KM::H) (:|pair| 3 KM::C) (:|pair| 5 KM::H)
     (:|pair| 3 KM::O))
    (:|seq| (:|pair| 6 KM::H) (:|pair| 3 KM::C) (:|pair| 3 KM::O)) NIL
    NIL NIL)
   (KM::CH3COOCH2CH3 ("ethylacetate" "hydrogen butyrate")
    (:|seq| (:|pair| 1 KM::|H-Plus|) (:|pair| 1 KM::|C4H7O2-Minus|))
    (:|seq| (:|pair| 1 KM::H) (:|pair| 4 KM::C) (:|pair| 7 KM::H)
     (:|pair| 2 KM::O))
    (:|seq| (:|pair| 8 KM::H) (:|pair| 4 KM::C) (:|pair| 2 KM::O)) NIL
    NIL NIL)
   (KM::CH3COOH ("hydrogen acetate" "acetic acid" "ethanoic acid")
    (:|seq| (:|pair| 1 KM::|H-Plus|) (:|pair| 1 KM::|CH3COO-Minus|))
    (:|seq| (:|pair| 1 KM::H) (:|pair| 2 KM::C) (:|pair| 3 KM::H)
     (:|pair| 2 KM::O))
    (:|seq| (:|pair| 4 KM::H) (:|pair| 2 KM::C) (:|pair| 2 KM::O)) NIL
    NIL NIL)
   (KM::CH3NH2 ("aniline" "aminobenzene") NIL
    (:|seq| (:|pair| 1 KM::C) (:|pair| 3 KM::H) (:|pair| 1 KM::N)
     (:|pair| 2 KM::H))
    (:|seq| (:|pair| 1 KM::C) (:|pair| 5 KM::H) (:|pair| 1 KM::N)) NIL
    NIL NIL)
   (KM::CH3_2_NH ("dimethylamine") NIL
    (:|seq| (:|pair| 2 (:|seq| (:|pair| 1 KM::C) (:|pair| 3 KM::H)))
     (:|pair| 1 KM::N) (:|pair| 1 KM::H))
    (:|seq| (:|pair| 2 KM::C) (:|pair| 7 KM::H) (:|pair| 1 KM::N)) NIL
    NIL NIL)
   (KM::CH3_3_N ("trimethylammonium") NIL
    (:|seq| (:|pair| 3 (:|seq| (:|pair| 1 KM::C) (:|pair| 3 KM::H)))
     (:|pair| 1 KM::N))
    (:|seq| (:|pair| 3 KM::C) (:|pair| 9 KM::H) (:|pair| 1 KM::N)) NIL
    NIL NIL)
   (KM::|CaCO3| ("calcium carbonate")
    (:|seq| (:|pair| 1 KM::|Ca-Plus-2|) (:|pair| 1 KM::|CO3-Minus-2|))
    (:|seq| (:|pair| 1 KM::|Ca|) (:|pair| 1 KM::C) (:|pair| 3 KM::O))
    (:|seq| (:|pair| 1 KM::|Ca|) (:|pair| 1 KM::C) (:|pair| 3 KM::O))
    NIL NIL NIL)
   (KM::|CaO| ("calcium oxide")
    (:|seq| (:|pair| 1 KM::|Ca-Plus-2|) (:|pair| 1 KM::|O-Minus-2|))
    (:|seq| (:|pair| 1 KM::|Ca|) (:|pair| 1 KM::O))
    (:|seq| (:|pair| 1 KM::|Ca|) (:|pair| 1 KM::O)) NIL NIL NIL)
   (KM::|Ca_OCl_2| ("calcium hypochlorite")
    (:|seq| (:|pair| 1 KM::|Ca-Plus-2|) (:|pair| 2 KM::|OCl-Minus|))
    (:|seq| (:|pair| 1 KM::|Ca|)
     (:|pair| 2 (:|seq| (:|pair| 1 KM::O) (:|pair| 1 KM::|Cl|))))
    (:|seq| (:|pair| 1 KM::|Ca|) (:|pair| 2 KM::O)
     (:|pair| 2 KM::|Cl|))
    NIL NIL NIL)
   (KM::|Ca_OH_2| ("calcium hydroxide")
    (:|seq| (:|pair| 1 KM::|Ca-Plus-2|) (:|pair| 2 KM::|OH-Minus|))
    (:|seq| (:|pair| 1 KM::|Ca|)
     (:|pair| 2 (:|seq| (:|pair| 1 KM::O) (:|pair| 1 KM::H))))
    (:|seq| (:|pair| 1 KM::|Ca|) (:|pair| 2 KM::O) (:|pair| 2 KM::H))
    NIL NIL NIL)
   (KM::|CsOH| ("caesium hydroxide")
    (:|seq| (:|pair| 1 KM::|Cs-Plus|) (:|pair| 1 KM::|OH-Minus|))
    (:|seq| (:|pair| 1 KM::|Cs|) (:|pair| 1 KM::O) (:|pair| 1 KM::H))
    (:|seq| (:|pair| 1 KM::|Cs|) (:|pair| 1 KM::O) (:|pair| 1 KM::H))
    NIL NIL NIL)
   (KM::|CuCl2| ("copper(ii) chloride")
    (:|seq| (:|pair| 1 KM::|Cu-Plus-2|) (:|pair| 2 KM::|Cl-Minus|))
    (:|seq| (:|pair| 1 KM::|Cu|) (:|pair| 2 KM::|Cl|))
    (:|seq| (:|pair| 1 KM::|Cu|) (:|pair| 2 KM::|Cl|)) NIL NIL NIL)
   (KM::|CuO| ("copper oxide" "copper(ii) oxide")
    (:|seq| (:|pair| 1 KM::|Cu-Plus-2|) (:|pair| 1 KM::|O-Minus-2|))
    (:|seq| (:|pair| 1 KM::|Cu|) (:|pair| 1 KM::O))
    (:|seq| (:|pair| 1 KM::|Cu|) (:|pair| 1 KM::O)) NIL NIL NIL)
   (KM::|CuSO4| ("copper(ii) sulfate" "copper(ii) sulfate")
    (:|seq| (:|pair| 1 KM::|Cu-Plus-2|) (:|pair| 1 KM::|SO4-Minus-2|))
    (:|seq| (:|pair| 1 KM::|Cu|) (:|pair| 1 KM::S) (:|pair| 4 KM::O))
    (:|seq| (:|pair| 1 KM::|Cu|) (:|pair| 1 KM::S) (:|pair| 4 KM::O))
    NIL NIL NIL)
   (KM::|Cu_CH3COO_2| ("copper(ii) acetate" "copper(ii) acetate")
    (:|seq| (:|pair| 1 KM::|Cu-Plus-2|) (:|pair| 2 KM::|CH3COO-Minus|))
    (:|seq| (:|pair| 1 KM::|Cu|)
     (:|pair| 2
      (:|seq| (:|pair| 2 KM::C) (:|pair| 3 KM::H) (:|pair| 2 KM::O))))
    (:|seq| (:|pair| 1 KM::|Cu|) (:|pair| 4 KM::C) (:|pair| 6 KM::H)
     (:|pair| 4 KM::O))
    NIL NIL NIL)
   (KM::|Cu_OH_2| ("copper hydroxide" "copper(ii) hydroxide")
    (:|seq| (:|pair| 1 KM::|Cu-Plus-2|) (:|pair| 2 KM::|OH-Minus|))
    (:|seq| (:|pair| 1 KM::|Cu|)
     (:|pair| 2 (:|seq| (:|pair| 1 KM::O) (:|pair| 1 KM::H))))
    (:|seq| (:|pair| 1 KM::|Cu|) (:|pair| 2 KM::O) (:|pair| 2 KM::H))
    NIL NIL NIL)
   (KM::|Fe2O3| ("iron(iii) oxide" "iron(iii) oxide")
    (:|seq| (:|pair| 2 KM::|Fe-Plus-3|) (:|pair| 3 KM::|O-Minus-2|))
    (:|seq| (:|pair| 2 KM::|Fe|) (:|pair| 3 KM::O))
    (:|seq| (:|pair| 2 KM::|Fe|) (:|pair| 3 KM::O)) NIL NIL NIL)
   (KM::|Fe3O4| ("magnetite" "iron(iii) iron(ii)")
    (:|seq| (:|pair| 2 KM::|Fe-Plus-3|) (:|pair| 1 KM::|Fe-Plus-2|)
     (:|pair| 4 KM::|O-Minus-2|))
    (:|seq| (:|pair| 3 KM::|Fe|) (:|pair| 4 KM::O))
    (:|seq| (:|pair| 3 KM::|Fe|) (:|pair| 4 KM::O)) NIL NIL NIL)
   (KM::|FeBr3| ("iron(iii) bromide" "iron(iii) bromide")
    (:|seq| (:|pair| 1 KM::|Fe-Plus-3|) (:|pair| 3 KM::|Br-Minus|))
    (:|seq| (:|pair| 1 KM::|Fe|) (:|pair| 3 KM::|Br|))
    (:|seq| (:|pair| 1 KM::|Fe|) (:|pair| 3 KM::|Br|)) NIL NIL NIL)
   (KM::|FeCl3|
    ("iron(iii) chloride" "ferrous chloride" "iron(iii) chloride")
    (:|seq| (:|pair| 1 KM::|Fe-Plus-3|) (:|pair| 3 KM::|Cl-Minus|))
    (:|seq| (:|pair| 1 KM::|Fe|) (:|pair| 3 KM::|Cl|))
    (:|seq| (:|pair| 1 KM::|Fe|) (:|pair| 3 KM::|Cl|)) NIL NIL NIL)
   (KM::|Fe_Cl_2|
    ("iron(ii) chloride" "ferrous chloride" "iron(ii) chloride")
    (:|seq| (:|pair| 1 KM::|Fe-Plus-2|) (:|pair| 2 KM::|Cl-Minus|))
    (:|seq| (:|pair| 1 KM::|Fe|) (:|pair| 2 KM::|Cl|))
    (:|seq| (:|pair| 1 KM::|Fe|) (:|pair| 2 KM::|Cl|)) NIL NIL NIL)
   (KM::|Fe_OH_2|
    ("iron(ii) hydroxide" "ferrous hydroxide" "iron(ii) hydroxide")
    (:|seq| (:|pair| 1 KM::|Fe-Plus-2|) (:|pair| 2 KM::|OH-Minus|))
    (:|seq| (:|pair| 1 KM::|Fe|)
     (:|pair| 2 (:|seq| (:|pair| 1 KM::O) (:|pair| 1 KM::H))))
    (:|seq| (:|pair| 1 KM::|Fe|) (:|pair| 2 KM::O) (:|pair| 2 KM::H))
    NIL NIL NIL)
   (KM::|Fe_OH_3|
    ("iron(iii) hydroxide" "ferric hydroxide" "iron(iii) hydroxide")
    (:|seq| (:|pair| 1 KM::|Fe-Plus-3|) (:|pair| 3 KM::|OH-Minus|))
    (:|seq| (:|pair| 1 KM::|Fe|)
     (:|pair| 3 (:|seq| (:|pair| 1 KM::O) (:|pair| 1 KM::H))))
    (:|seq| (:|pair| 1 KM::|Fe|) (:|pair| 3 KM::O) (:|pair| 3 KM::H))
    NIL NIL NIL)
   (KM::H2NNH2 ("hydrazine") NIL
    (:|seq| (:|pair| 2 KM::H) (:|pair| 1 KM::N) (:|pair| 1 KM::N)
     (:|pair| 2 KM::H))
    (:|seq| (:|pair| 4 KM::H) (:|pair| 2 KM::N)) NIL NIL NIL)
   (KM::H2O ("water" "hydrogen hydroxide")
    (:|seq| (:|pair| 1 KM::|H-Plus|) (:|pair| 1 KM::|OH-Minus|))
    (:|seq| (:|pair| 2 KM::H) (:|pair| 1 KM::O))
    (:|seq| (:|pair| 2 KM::H) (:|pair| 1 KM::O)) NIL NIL NIL)
   (KM::|HClO3| ("hydrogen chlorate")
    (:|seq| (:|pair| 1 KM::|H-Plus|) (:|pair| 1 KM::|ClO3-Minus|))
    (:|seq| (:|pair| 1 KM::H) (:|pair| 1 KM::|Cl|) (:|pair| 3 KM::O))
    (:|seq| (:|pair| 1 KM::H) (:|pair| 1 KM::|Cl|) (:|pair| 3 KM::O))
    NIL NIL NIL)
   (KM::|HClO4| ("perchloric acid" "hydrogen perchlorate")
    (:|seq| (:|pair| 1 KM::|H-Plus|) (:|pair| 1 KM::|ClO4-Minus|))
    (:|seq| (:|pair| 1 KM::H) (:|pair| 1 KM::|Cl|) (:|pair| 4 KM::O))
    (:|seq| (:|pair| 1 KM::H) (:|pair| 1 KM::|Cl|) (:|pair| 4 KM::O))
    NIL NIL NIL)
   (KM::HNO3 ("nitric acid" "hydrogen nitrate")
    (:|seq| (:|pair| 1 KM::|H-Plus|) (:|pair| 1 KM::|NO3-Minus|))
    (:|seq| (:|pair| 1 KM::H) (:|pair| 1 KM::N) (:|pair| 3 KM::O))
    (:|seq| (:|pair| 1 KM::H) (:|pair| 1 KM::N) (:|pair| 3 KM::O)) NIL
    NIL NIL)
   (KM::HONH2 ("hydroxylamine") NIL
    (:|seq| (:|pair| 1 KM::H) (:|pair| 1 KM::O) (:|pair| 1 KM::N)
     (:|pair| 2 KM::H))
    (:|seq| (:|pair| 3 KM::H) (:|pair| 1 KM::O) (:|pair| 1 KM::N)) NIL
    NIL NIL)
   (KM::K2CO3 ("potassium carbonate")
    (:|seq| (:|pair| 2 KM::|K-Plus|) (:|pair| 1 KM::|CO3-Minus-2|))
    (:|seq| (:|pair| 2 KM::K) (:|pair| 1 KM::C) (:|pair| 3 KM::O))
    (:|seq| (:|pair| 2 KM::K) (:|pair| 1 KM::C) (:|pair| 3 KM::O)) NIL
    NIL NIL)
   (KM::|K2CrO4| ("potassium chromate")
    (:|seq| (:|pair| 2 KM::|K-Plus|) (:|pair| 1 KM::|CrO4-Minus-2|))
    (:|seq| (:|pair| 2 KM::K) (:|pair| 1 KM::|Cr|) (:|pair| 4 KM::O))
    (:|seq| (:|pair| 2 KM::K) (:|pair| 1 KM::|Cr|) (:|pair| 4 KM::O))
    NIL NIL NIL)
   (KM::K2SO4 ("potassium sulfate")
    (:|seq| (:|pair| 2 KM::|K-Plus|) (:|pair| 1 KM::|SO4-Minus-2|))
    (:|seq| (:|pair| 2 KM::K) (:|pair| 1 KM::S) (:|pair| 4 KM::O))
    (:|seq| (:|pair| 2 KM::K) (:|pair| 1 KM::S) (:|pair| 4 KM::O)) NIL
    NIL NIL)
   (KM::|KI-Compound| ("potassium iodide")
    (:|seq| (:|pair| 1 KM::|K-Plus|) (:|pair| 1 KM::|I-Minus|))
    (:|seq| (:|pair| 1 KM::K) (:|pair| 1 KM::I))
    (:|seq| (:|pair| 1 KM::K) (:|pair| 1 KM::I)) NIL NIL NIL)
   (KM::KOH ("potassium hydroxide")
    (:|seq| (:|pair| 1 KM::|K-Plus|) (:|pair| 1 KM::|OH-Minus|))
    (:|seq| (:|pair| 1 KM::K) (:|pair| 1 KM::O) (:|pair| 1 KM::H))
    (:|seq| (:|pair| 1 KM::K) (:|pair| 1 KM::O) (:|pair| 1 KM::H)) NIL
    NIL NIL)
   (KM::|Li2CO3| ("lithium carbonate")
    (:|seq| (:|pair| 2 KM::|Li-Plus|) (:|pair| 1 KM::|CO3-Minus-2|))
    (:|seq| (:|pair| 2 KM::|Li|) (:|pair| 1 KM::C) (:|pair| 3 KM::O))
    (:|seq| (:|pair| 2 KM::|Li|) (:|pair| 1 KM::C) (:|pair| 3 KM::O))
    NIL NIL NIL)
   (KM::|LiOH| ("lithium hydroxide")
    (:|seq| (:|pair| 1 KM::|Li-Plus|) (:|pair| 1 KM::|OH-Minus|))
    (:|seq| (:|pair| 1 KM::|Li|) (:|pair| 1 KM::O) (:|pair| 1 KM::H))
    (:|seq| (:|pair| 1 KM::|Li|) (:|pair| 1 KM::O) (:|pair| 1 KM::H))
    NIL NIL NIL)
   (KM::|MgO| ("magnesium oxide")
    (:|seq| (:|pair| 1 KM::|Mg-Plus-2|) (:|pair| 1 KM::|O-Minus-2|))
    (:|seq| (:|pair| 1 KM::|Mg|) (:|pair| 1 KM::O))
    (:|seq| (:|pair| 1 KM::|Mg|) (:|pair| 1 KM::O)) NIL NIL NIL)
   (KM::|MgSO4| ("magnesium sulfate")
    (:|seq| (:|pair| 1 KM::|Mg-Plus-2|) (:|pair| 1 KM::|SO4-Minus-2|))
    (:|seq| (:|pair| 1 KM::|Mg|) (:|pair| 1 KM::S) (:|pair| 4 KM::O))
    (:|seq| (:|pair| 1 KM::|Mg|) (:|pair| 1 KM::S) (:|pair| 4 KM::O))
    NIL NIL NIL)
   (KM::NH4_2_SO4 ("ammonium sulphate" "ammonium sulfate")
    (:|seq| (:|pair| 2 KM::|NH4-Plus|) (:|pair| 1 KM::|SO4-Minus-2|))
    (:|seq| (:|pair| 2 (:|seq| (:|pair| 1 KM::N) (:|pair| 4 KM::H)))
     (:|pair| 1 KM::S) (:|pair| 4 KM::O))
    (:|seq| (:|pair| 2 KM::N) (:|pair| 8 KM::H) (:|pair| 1 KM::S)
     (:|pair| 4 KM::O))
    NIL NIL NIL)
   (KM::NH4_3_PO4 ("ammonium phosphate")
    (:|seq| (:|pair| 3 KM::|NH4-Plus|) (:|pair| 1 KM::|PO4-Minus-3|))
    (:|seq| (:|pair| 3 (:|seq| (:|pair| 1 KM::N) (:|pair| 4 KM::H)))
     (:|pair| 1 KM::P) (:|pair| 4 KM::O))
    (:|seq| (:|pair| 3 KM::N) (:|pair| 12 KM::H) (:|pair| 1 KM::P)
     (:|pair| 4 KM::O))
    NIL NIL NIL)
   (KM::|Na2CO3| ("sodium carbonate")
    (:|seq| (:|pair| 2 KM::|Na-Plus|) (:|pair| 1 KM::|CO3-Minus-2|))
    (:|seq| (:|pair| 2 KM::|Na|) (:|pair| 1 KM::C) (:|pair| 3 KM::O))
    (:|seq| (:|pair| 2 KM::|Na|) (:|pair| 1 KM::C) (:|pair| 3 KM::O))
    NIL NIL NIL)
   (KM::|Na2S| ("sodium sulfide")
    (:|seq| (:|pair| 2 KM::|Na-Plus|) (:|pair| 1 KM::|S-Minus-2|))
    (:|seq| (:|pair| 2 KM::|Na|) (:|pair| 1 KM::S))
    (:|seq| (:|pair| 2 KM::|Na|) (:|pair| 1 KM::S)) NIL NIL NIL)
   (KM::|Na2SO4| ("sodium sulfate")
    (:|seq| (:|pair| 2 KM::|Na-Plus|) (:|pair| 1 KM::|SO4-Minus-2|))
    (:|seq| (:|pair| 2 KM::|Na|) (:|pair| 1 KM::S) (:|pair| 4 KM::O))
    (:|seq| (:|pair| 2 KM::|Na|) (:|pair| 1 KM::S) (:|pair| 4 KM::O))
    NIL NIL NIL)
   (KM::|NaHCO3| ("sodium hydrogen carbonate" "sodium bicarbonate")
    (:|seq| (:|pair| 1 KM::|Na-Plus|) (:|pair| 1 KM::|HCO3-Minus|))
    (:|seq| (:|pair| 1 KM::|Na|) (:|pair| 1 KM::H) (:|pair| 1 KM::C)
     (:|pair| 3 KM::O))
    (:|seq| (:|pair| 1 KM::|Na|) (:|pair| 1 KM::H) (:|pair| 1 KM::C)
     (:|pair| 3 KM::O))
    NIL NIL NIL)
   (KM::|NaI| ("sodium iodide")
    (:|seq| (:|pair| 1 KM::|Na-Plus|) (:|pair| 1 KM::|I-Minus|))
    (:|seq| (:|pair| 1 KM::|Na|) (:|pair| 1 KM::I))
    (:|seq| (:|pair| 1 KM::|Na|) (:|pair| 1 KM::I)) NIL NIL NIL)
   (KM::|NaN3| ("sodium azide")
    (:|seq| (:|pair| 1 KM::|Na-Plus|) (:|pair| 1 KM::|N3-Minus|))
    (:|seq| (:|pair| 1 KM::|Na|) (:|pair| 3 KM::N))
    (:|seq| (:|pair| 1 KM::|Na|) (:|pair| 3 KM::N)) NIL NIL NIL)
   (KM::|NaNO3| ("sodium nitrate")
    (:|seq| (:|pair| 1 KM::|Na-Plus|) (:|pair| 1 KM::|NO3-Minus|))
    (:|seq| (:|pair| 1 KM::|Na|) (:|pair| 1 KM::N) (:|pair| 3 KM::O))
    (:|seq| (:|pair| 1 KM::|Na|) (:|pair| 1 KM::N) (:|pair| 3 KM::O))
    NIL NIL NIL)
   (KM::|NaOCl| ("sodium hypochlorite")
    (:|seq| (:|pair| 1 KM::|Na-Plus|) (:|pair| 1 KM::|OCl-Minus|))
    (:|seq| (:|pair| 1 KM::|Na|) (:|pair| 1 KM::O)
     (:|pair| 1 KM::|Cl|))
    (:|seq| (:|pair| 1 KM::|Na|) (:|pair| 1 KM::O)
     (:|pair| 1 KM::|Cl|))
    NIL NIL NIL)
   (KM::|NaOH| ("sodium hydroxide")
    (:|seq| (:|pair| 1 KM::|Na-Plus|) (:|pair| 1 KM::|OH-Minus|))
    (:|seq| (:|pair| 1 KM::|Na|) (:|pair| 1 KM::O) (:|pair| 1 KM::H))
    (:|seq| (:|pair| 1 KM::|Na|) (:|pair| 1 KM::O) (:|pair| 1 KM::H))
    NIL NIL NIL)
   (KM::|PbO| ("lead oxide")
    (:|seq| (:|pair| 1 KM::|Pb-Plus-2|) (:|pair| 1 KM::|O-Minus-2|))
    (:|seq| (:|pair| 1 KM::|Pb|) (:|pair| 1 KM::O))
    (:|seq| (:|pair| 1 KM::|Pb|) (:|pair| 1 KM::O)) NIL NIL NIL)
   (KM::|PbS| ("lead sulfide")
    (:|seq| (:|pair| 1 KM::|Pb-Plus-2|) (:|pair| 1 KM::|S-Minus-2|))
    (:|seq| (:|pair| 1 KM::|Pb|) (:|pair| 1 KM::S))
    (:|seq| (:|pair| 1 KM::|Pb|) (:|pair| 1 KM::S)) NIL NIL NIL)
   (KM::|PbSO4| ("lead sulfate")
    (:|seq| (:|pair| 1 KM::|Pb-Plus-2|) (:|pair| 1 KM::|SO4-Minus-2|))
    (:|seq| (:|pair| 1 KM::|Pb|) (:|pair| 1 KM::S) (:|pair| 4 KM::O))
    (:|seq| (:|pair| 1 KM::|Pb|) (:|pair| 1 KM::S) (:|pair| 4 KM::O))
    NIL NIL NIL)
   (KM::|Pb_NO3_2| ("lead nitrate")
    (:|seq| (:|pair| 1 KM::|Pb-Plus-2|) (:|pair| 2 KM::|NO3-Minus|))
    (:|seq| (:|pair| 1 KM::|Pb|)
     (:|pair| 2 (:|seq| (:|pair| 1 KM::N) (:|pair| 3 KM::O))))
    (:|seq| (:|pair| 1 KM::|Pb|) (:|pair| 2 KM::N) (:|pair| 6 KM::O))
    NIL NIL NIL)
   (KM::|Pb_OH_2| ("lead hydroxide")
    (:|seq| (:|pair| 1 KM::|Pb-Plus-2|) (:|pair| 2 KM::|OH-Minus|))
    (:|seq| (:|pair| 1 KM::|Pb|)
     (:|pair| 2 (:|seq| (:|pair| 1 KM::O) (:|pair| 1 KM::H))))
    (:|seq| (:|pair| 1 KM::|Pb|) (:|pair| 2 KM::O) (:|pair| 2 KM::H))
    NIL NIL NIL)
   (KM::|RbOH| ("rubidium hydroxide")
    (:|seq| (:|pair| 1 KM::|Rb-Plus|) (:|pair| 1 KM::|OH-Minus|))
    (:|seq| (:|pair| 1 KM::|Rb|) (:|pair| 1 KM::O) (:|pair| 1 KM::H))
    (:|seq| (:|pair| 1 KM::|Rb|) (:|pair| 1 KM::O) (:|pair| 1 KM::H))
    NIL NIL NIL)
   (KM::|CH3COONa| ("sodium acetate")
    (:|seq| (:|pair| 1 KM::|Na-Plus|) (:|pair| 1 KM::|CH3COO-Minus|))
    (:|seq| (:|pair| 1 KM::|Na|) (:|pair| 2 KM::C) (:|pair| 3 KM::H)
     (:|pair| 2 KM::O))
    (:|seq| (:|pair| 1 KM::|Na|) (:|pair| 2 KM::C) (:|pair| 3 KM::H)
     (:|pair| 2 KM::O))
    NIL NIL NIL)
   (KM::|CH3NH3Cl| ("methylammonium chloride")
    (:|seq| (:|pair| 1 KM::|CH3NH3-Plus|) (:|pair| 1 KM::|Cl-Minus|))
    (:|seq| (:|pair| 1 KM::C) (:|pair| 3 KM::H) (:|pair| 1 KM::N)
     (:|pair| 3 KM::H) (:|pair| 1 KM::|Cl|))
    (:|seq| (:|pair| 1 KM::C) (:|pair| 6 KM::H) (:|pair| 1 KM::N)
     (:|pair| 1 KM::|Cl|))
    NIL NIL NIL)
   (KM::|LiF| ("lithium fluoride")
    (:|seq| (:|pair| 1 KM::|Li-Plus|) (:|pair| 1 KM::|F-Minus|))
    (:|seq| (:|pair| 1 KM::|Li|) (:|pair| 1 KM::F))
    (:|seq| (:|pair| 1 KM::|Li|) (:|pair| 1 KM::F)) NIL NIL NIL)
   (KM::|NH4Cl| ("ammonium chloride")
    (:|seq| (:|pair| 1 KM::|NH4-Plus|) (:|pair| 1 KM::|Cl-Minus|))
    (:|seq| (:|pair| 1 KM::N) (:|pair| 4 KM::H) (:|pair| 1 KM::|Cl|))
    (:|seq| (:|pair| 1 KM::N) (:|pair| 4 KM::H) (:|pair| 1 KM::|Cl|))
    NIL NIL NIL)
   (KM::NH4NO3 ("ammonium nitrate")
    (:|seq| (:|pair| 1 KM::|NH4-Plus|) (:|pair| 1 KM::|NO3-Minus|))
    (:|seq| (:|pair| 1 KM::N) (:|pair| 4 KM::H) (:|pair| 1 KM::N)
     (:|pair| 3 KM::O))
    (:|seq| (:|pair| 2 KM::N) (:|pair| 4 KM::H) (:|pair| 3 KM::O)) NIL
    NIL NIL)
   (KM::|NaCl| ("sodium chloride")
    (:|seq| (:|pair| 1 KM::|Na-Plus|) (:|pair| 1 KM::|Cl-Minus|))
    (:|seq| (:|pair| 1 KM::|Na|) (:|pair| 1 KM::|Cl|))
    (:|seq| (:|pair| 1 KM::|Na|) (:|pair| 1 KM::|Cl|)) NIL NIL NIL)
   (KM::|Sn_NO3_2| ("tin nitrate")
    (:|seq| (:|pair| 1 KM::|Sn-Plus-2|) (:|pair| 2 KM::|NO3-Minus|))
    (:|seq| (:|pair| 1 KM::|Sn|)
     (:|pair| 2 (:|seq| (:|pair| 1 KM::N) (:|pair| 3 KM::O))))
    (:|seq| (:|pair| 1 KM::|Sn|) (:|pair| 2 KM::N) (:|pair| 6 KM::O))
    NIL NIL NIL)
   (KM::|Sr_OH_2| ("strontium hydroxide")
    (:|seq| (:|pair| 1 KM::|Sr-Plus-2|) (:|pair| 2 KM::|OH-Minus|))
    (:|seq| (:|pair| 1 KM::|Sr|)
     (:|pair| 2 (:|seq| (:|pair| 1 KM::O) (:|pair| 1 KM::H))))
    (:|seq| (:|pair| 1 KM::|Sr|) (:|pair| 2 KM::O) (:|pair| 2 KM::H))
    NIL NIL NIL)
   (KM::A NIL (:|seq| (:|pair| 1 KM::A)) (:|seq| (:|pair| 1 KM::A))
    (:|seq| (:|pair| 1 KM::A)) (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::|Ag| ("silver" "silver") (:|seq| (:|pair| 1 KM::|Ag|))
    (:|seq| (:|pair| 1 KM::|Ag|)) (:|seq| (:|pair| 1 KM::|Ag|))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::|Al| ("aluminum" "aluminum") (:|seq| (:|pair| 1 KM::|Al|))
    (:|seq| (:|pair| 1 KM::|Al|)) (:|seq| (:|pair| 1 KM::|Al|))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::|Au| ("gold" "gold") (:|seq| (:|pair| 1 KM::|Au|))
    (:|seq| (:|pair| 1 KM::|Au|)) (:|seq| (:|pair| 1 KM::|Au|))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::|Ba| ("barium" "barium") (:|seq| (:|pair| 1 KM::|Ba|))
    (:|seq| (:|pair| 1 KM::|Ba|)) (:|seq| (:|pair| 1 KM::|Ba|))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::|Be| ("beryllium" "beryllium") (:|seq| (:|pair| 1 KM::|Be|))
    (:|seq| (:|pair| 1 KM::|Be|)) (:|seq| (:|pair| 1 KM::|Be|))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::|Ca| ("calcium" "calcium") (:|seq| (:|pair| 1 KM::|Ca|))
    (:|seq| (:|pair| 1 KM::|Ca|)) (:|seq| (:|pair| 1 KM::|Ca|))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::|Cd| ("cadmium" "cadmium") (:|seq| (:|pair| 1 KM::|Cd|))
    (:|seq| (:|pair| 1 KM::|Cd|)) (:|seq| (:|pair| 1 KM::|Cd|))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::|Cs| ("cesium" "cesium") (:|seq| (:|pair| 1 KM::|Cs|))
    (:|seq| (:|pair| 1 KM::|Cs|)) (:|seq| (:|pair| 1 KM::|Cs|))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::|Cu| ("copper" "copper") (:|seq| (:|pair| 1 KM::|Cu|))
    (:|seq| (:|pair| 1 KM::|Cu|)) (:|seq| (:|pair| 1 KM::|Cu|))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::|Fr| ("francium" "francium") (:|seq| (:|pair| 1 KM::|Fr|))
    (:|seq| (:|pair| 1 KM::|Fr|)) (:|seq| (:|pair| 1 KM::|Fr|))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::|Ga| ("gallium" "gallium") (:|seq| (:|pair| 1 KM::|Ga|))
    (:|seq| (:|pair| 1 KM::|Ga|)) (:|seq| (:|pair| 1 KM::|Ga|))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::|Hf| ("hafnium" "hafnium") (:|seq| (:|pair| 1 KM::|Hf|))
    (:|seq| (:|pair| 1 KM::|Hf|)) (:|seq| (:|pair| 1 KM::|Hf|))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::|Hg| ("mercury" "mercury") (:|seq| (:|pair| 1 KM::|Hg|))
    (:|seq| (:|pair| 1 KM::|Hg|)) (:|seq| (:|pair| 1 KM::|Hg|))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::|In| ("indium" "indium") (:|seq| (:|pair| 1 KM::|In|))
    (:|seq| (:|pair| 1 KM::|In|)) (:|seq| (:|pair| 1 KM::|In|))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::K ("potassium" "potassium") (:|seq| (:|pair| 1 KM::K))
    (:|seq| (:|pair| 1 KM::K)) (:|seq| (:|pair| 1 KM::K))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::|Li| ("lithium" "lithium") (:|seq| (:|pair| 1 KM::|Li|))
    (:|seq| (:|pair| 1 KM::|Li|)) (:|seq| (:|pair| 1 KM::|Li|))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::|Lr| ("lawrencium" "lawrencium") (:|seq| (:|pair| 1 KM::|Lr|))
    (:|seq| (:|pair| 1 KM::|Lr|)) (:|seq| (:|pair| 1 KM::|Lr|))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::|Lu| ("lutetium" "lutetium") (:|seq| (:|pair| 1 KM::|Lu|))
    (:|seq| (:|pair| 1 KM::|Lu|)) (:|seq| (:|pair| 1 KM::|Lu|))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::|Mg| ("magnesium" "magnesium") (:|seq| (:|pair| 1 KM::|Mg|))
    (:|seq| (:|pair| 1 KM::|Mg|)) (:|seq| (:|pair| 1 KM::|Mg|))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::|Na| ("sodium" "sodium") (:|seq| (:|pair| 1 KM::|Na|))
    (:|seq| (:|pair| 1 KM::|Na|)) (:|seq| (:|pair| 1 KM::|Na|))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::|Pb| ("lead" "lead") (:|seq| (:|pair| 1 KM::|Pb|))
    (:|seq| (:|pair| 1 KM::|Pb|)) (:|seq| (:|pair| 1 KM::|Pb|))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::|Ra| ("radium" "radium") (:|seq| (:|pair| 1 KM::|Ra|))
    (:|seq| (:|pair| 1 KM::|Ra|)) (:|seq| (:|pair| 1 KM::|Ra|))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::|Rb| ("rubidium" "rubidium") (:|seq| (:|pair| 1 KM::|Rb|))
    (:|seq| (:|pair| 1 KM::|Rb|)) (:|seq| (:|pair| 1 KM::|Rb|))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::|Rf| ("rutherfordium" "rutherfordium")
    (:|seq| (:|pair| 1 KM::|Rf|)) (:|seq| (:|pair| 1 KM::|Rf|))
    (:|seq| (:|pair| 1 KM::|Rf|)) (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::|Sc| ("scandium" "scandium") (:|seq| (:|pair| 1 KM::|Sc|))
    (:|seq| (:|pair| 1 KM::|Sc|)) (:|seq| (:|pair| 1 KM::|Sc|))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::|Sn| ("tin" "tin") (:|seq| (:|pair| 1 KM::|Sn|))
    (:|seq| (:|pair| 1 KM::|Sn|)) (:|seq| (:|pair| 1 KM::|Sn|))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::|Sr| ("strontium" "strontium") (:|seq| (:|pair| 1 KM::|Sr|))
    (:|seq| (:|pair| 1 KM::|Sr|)) (:|seq| (:|pair| 1 KM::|Sr|))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::|Ti| ("titanium" "titanium") (:|seq| (:|pair| 1 KM::|Ti|))
    (:|seq| (:|pair| 1 KM::|Ti|)) (:|seq| (:|pair| 1 KM::|Ti|))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::|Tl| ("thallium" "thallium") (:|seq| (:|pair| 1 KM::|Tl|))
    (:|seq| (:|pair| 1 KM::|Tl|)) (:|seq| (:|pair| 1 KM::|Tl|))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::Y ("yttrium" "yttrium") (:|seq| (:|pair| 1 KM::Y))
    (:|seq| (:|pair| 1 KM::Y)) (:|seq| (:|pair| 1 KM::Y))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::|Zn| ("zinc" "zinc") (:|seq| (:|pair| 1 KM::|Zn|))
    (:|seq| (:|pair| 1 KM::|Zn|)) (:|seq| (:|pair| 1 KM::|Zn|))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::|Zr| ("zirconium" "zirconium") (:|seq| (:|pair| 1 KM::|Zr|))
    (:|seq| (:|pair| 1 KM::|Zr|)) (:|seq| (:|pair| 1 KM::|Zr|))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::B ("boron" "boron") (:|seq| (:|pair| 1 KM::B))
    (:|seq| (:|pair| 1 KM::B)) (:|seq| (:|pair| 1 KM::B))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::|Ge| ("germanium" "germanium") (:|seq| (:|pair| 1 KM::|Ge|))
    (:|seq| (:|pair| 1 KM::|Ge|)) (:|seq| (:|pair| 1 KM::|Ge|))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::|Si| ("silicon" "silicon") (:|seq| (:|pair| 1 KM::|Si|))
    (:|seq| (:|pair| 1 KM::|Si|)) (:|seq| (:|pair| 1 KM::|Si|))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::C ("carbon" "carbon") (:|seq| (:|pair| 1 KM::C))
    (:|seq| (:|pair| 1 KM::C)) (:|seq| (:|pair| 1 KM::C))
    (:|pair| 0 KM::|*unity|) NIL ("carbide"))
   (KM::H ("hydrogen" "hydrogen") (:|seq| (:|pair| 1 KM::H))
    (:|seq| (:|pair| 1 KM::H)) (:|seq| (:|pair| 1 KM::H))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::|As| ("arsenic" "arsenic") (:|seq| (:|pair| 1 KM::|As|))
    (:|seq| (:|pair| 1 KM::|As|)) (:|seq| (:|pair| 1 KM::|As|))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::|Bi| ("bismuth" "bismuth") (:|seq| (:|pair| 1 KM::|Bi|))
    (:|seq| (:|pair| 1 KM::|Bi|)) (:|seq| (:|pair| 1 KM::|Bi|))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::N ("nitrogen" "nitrogen") (:|seq| (:|pair| 1 KM::N))
    (:|seq| (:|pair| 1 KM::N)) (:|seq| (:|pair| 1 KM::N))
    (:|pair| 0 KM::|*unity|) NIL ("nitride"))
   (KM::P ("phosphorus" "phosphorus") (:|seq| (:|pair| 1 KM::P))
    (:|seq| (:|pair| 1 KM::P)) (:|seq| (:|pair| 1 KM::P))
    (:|pair| 0 KM::|*unity|) NIL ("phosphide"))
   (KM::|Sb| ("antimony" "antimony") (:|seq| (:|pair| 1 KM::|Sb|))
    (:|seq| (:|pair| 1 KM::|Sb|)) (:|seq| (:|pair| 1 KM::|Sb|))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::|Db| ("dubnium" "dubnium") (:|seq| (:|pair| 1 KM::|Db|))
    (:|seq| (:|pair| 1 KM::|Db|)) (:|seq| (:|pair| 1 KM::|Db|))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::|Nb| ("niobium" "niobium") (:|seq| (:|pair| 1 KM::|Nb|))
    (:|seq| (:|pair| 1 KM::|Nb|)) (:|seq| (:|pair| 1 KM::|Nb|))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::|Ta| ("tantalum" "tantalum") (:|seq| (:|pair| 1 KM::|Ta|))
    (:|seq| (:|pair| 1 KM::|Ta|)) (:|seq| (:|pair| 1 KM::|Ta|))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::V ("vanadium" "vanadium") (:|seq| (:|pair| 1 KM::V))
    (:|seq| (:|pair| 1 KM::V)) (:|seq| (:|pair| 1 KM::V))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::O ("oxygen" "oxygen") (:|seq| (:|pair| 1 KM::O))
    (:|seq| (:|pair| 1 KM::O)) (:|seq| (:|pair| 1 KM::O))
    (:|pair| 0 KM::|*unity|) NIL ("oxide"))
   (KM::|Po| ("polonium" "polonium") (:|seq| (:|pair| 1 KM::|Po|))
    (:|seq| (:|pair| 1 KM::|Po|)) (:|seq| (:|pair| 1 KM::|Po|))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::S ("sulfur" "sulfur") (:|seq| (:|pair| 1 KM::S))
    (:|seq| (:|pair| 1 KM::S)) (:|seq| (:|pair| 1 KM::S))
    (:|pair| 0 KM::|*unity|) NIL ("sulfide"))
   (KM::|Se| ("selenium" "selenium") (:|seq| (:|pair| 1 KM::|Se|))
    (:|seq| (:|pair| 1 KM::|Se|)) (:|seq| (:|pair| 1 KM::|Se|))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::|Te| ("tellurium" "tellurium") (:|seq| (:|pair| 1 KM::|Te|))
    (:|seq| (:|pair| 1 KM::|Te|)) (:|seq| (:|pair| 1 KM::|Te|))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::|Cr| ("chromium" "chromium") (:|seq| (:|pair| 1 KM::|Cr|))
    (:|seq| (:|pair| 1 KM::|Cr|)) (:|seq| (:|pair| 1 KM::|Cr|))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::|Mo| ("molybdenum" "molybdenum") (:|seq| (:|pair| 1 KM::|Mo|))
    (:|seq| (:|pair| 1 KM::|Mo|)) (:|seq| (:|pair| 1 KM::|Mo|))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::|Sg| ("seaborgium" "seaborgium") (:|seq| (:|pair| 1 KM::|Sg|))
    (:|seq| (:|pair| 1 KM::|Sg|)) (:|seq| (:|pair| 1 KM::|Sg|))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::W ("tungsten" "tungsten") (:|seq| (:|pair| 1 KM::W))
    (:|seq| (:|pair| 1 KM::W)) (:|seq| (:|pair| 1 KM::W))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::|At| ("astatine" "astatine") (:|seq| (:|pair| 1 KM::|At|))
    (:|seq| (:|pair| 1 KM::|At|)) (:|seq| (:|pair| 1 KM::|At|))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::|Br| ("bromine" "bromine") (:|seq| (:|pair| 1 KM::|Br|))
    (:|seq| (:|pair| 1 KM::|Br|)) (:|seq| (:|pair| 1 KM::|Br|))
    (:|pair| 0 KM::|*unity|) NIL ("bromine"))
   (KM::F ("fluorine" "fluorine") (:|seq| (:|pair| 1 KM::F))
    (:|seq| (:|pair| 1 KM::F)) (:|seq| (:|pair| 1 KM::F))
    (:|pair| 0 KM::|*unity|) NIL ("fluoride"))
   (KM::|Cl| ("chlorine" "chlorine") (:|seq| (:|pair| 1 KM::|Cl|))
    (:|seq| (:|pair| 1 KM::|Cl|)) (:|seq| (:|pair| 1 KM::|Cl|))
    (:|pair| 0 KM::|*unity|) NIL ("chloride"))
   (KM::I ("iodine" "iodine") (:|seq| (:|pair| 1 KM::I))
    (:|seq| (:|pair| 1 KM::I)) (:|seq| (:|pair| 1 KM::I))
    (:|pair| 0 KM::|*unity|) NIL ("iodide"))
   (KM::|Bh| ("bohrium" "bohrium") (:|seq| (:|pair| 1 KM::|Bh|))
    (:|seq| (:|pair| 1 KM::|Bh|)) (:|seq| (:|pair| 1 KM::|Bh|))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::|Mn| ("manganese" "manganese") (:|seq| (:|pair| 1 KM::|Mn|))
    (:|seq| (:|pair| 1 KM::|Mn|)) (:|seq| (:|pair| 1 KM::|Mn|))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::|Re| ("rhenium" "rhenium") (:|seq| (:|pair| 1 KM::|Re|))
    (:|seq| (:|pair| 1 KM::|Re|)) (:|seq| (:|pair| 1 KM::|Re|))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::|Tc| ("technetium" "technetium") (:|seq| (:|pair| 1 KM::|Tc|))
    (:|seq| (:|pair| 1 KM::|Tc|)) (:|seq| (:|pair| 1 KM::|Tc|))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::|Ar| ("argon" "argon") (:|seq| (:|pair| 1 KM::|Ar|))
    (:|seq| (:|pair| 1 KM::|Ar|)) (:|seq| (:|pair| 1 KM::|Ar|))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::|He| ("helium" "helium") (:|seq| (:|pair| 1 KM::|He|))
    (:|seq| (:|pair| 1 KM::|He|)) (:|seq| (:|pair| 1 KM::|He|))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::|Kr| ("krypton" "krypton") (:|seq| (:|pair| 1 KM::|Kr|))
    (:|seq| (:|pair| 1 KM::|Kr|)) (:|seq| (:|pair| 1 KM::|Kr|))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::|Ne| ("neon" "neon") (:|seq| (:|pair| 1 KM::|Ne|))
    (:|seq| (:|pair| 1 KM::|Ne|)) (:|seq| (:|pair| 1 KM::|Ne|))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::|Rn| ("radon" "radon") (:|seq| (:|pair| 1 KM::|Rn|))
    (:|seq| (:|pair| 1 KM::|Rn|)) (:|seq| (:|pair| 1 KM::|Rn|))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::|Xe| ("xenon" "xenon") (:|seq| (:|pair| 1 KM::|Xe|))
    (:|seq| (:|pair| 1 KM::|Xe|)) (:|seq| (:|pair| 1 KM::|Xe|))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::|Co| ("cobalt" "cobalt") (:|seq| (:|pair| 1 KM::|Co|))
    (:|seq| (:|pair| 1 KM::|Co|)) (:|seq| (:|pair| 1 KM::|Co|))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::|Fe| ("iron" "iron") (:|seq| (:|pair| 1 KM::|Fe|))
    (:|seq| (:|pair| 1 KM::|Fe|)) (:|seq| (:|pair| 1 KM::|Fe|))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::|Hs| ("hassium" "hassium") (:|seq| (:|pair| 1 KM::|Hs|))
    (:|seq| (:|pair| 1 KM::|Hs|)) (:|seq| (:|pair| 1 KM::|Hs|))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::|Ir| ("iridium" "iridium") (:|seq| (:|pair| 1 KM::|Ir|))
    (:|seq| (:|pair| 1 KM::|Ir|)) (:|seq| (:|pair| 1 KM::|Ir|))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::|Mt| ("meitnerium" "meitnerium") (:|seq| (:|pair| 1 KM::|Mt|))
    (:|seq| (:|pair| 1 KM::|Mt|)) (:|seq| (:|pair| 1 KM::|Mt|))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::|Ni| ("nickel" "nickel") (:|seq| (:|pair| 1 KM::|Ni|))
    (:|seq| (:|pair| 1 KM::|Ni|)) (:|seq| (:|pair| 1 KM::|Ni|))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::|Os| ("osmium" "osmium") (:|seq| (:|pair| 1 KM::|Os|))
    (:|seq| (:|pair| 1 KM::|Os|)) (:|seq| (:|pair| 1 KM::|Os|))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::|Pd| ("palladium" "palladium") (:|seq| (:|pair| 1 KM::|Pd|))
    (:|seq| (:|pair| 1 KM::|Pd|)) (:|seq| (:|pair| 1 KM::|Pd|))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::|Pt| ("platinum" "platinum") (:|seq| (:|pair| 1 KM::|Pt|))
    (:|seq| (:|pair| 1 KM::|Pt|)) (:|seq| (:|pair| 1 KM::|Pt|))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::|Rh| ("rhodium" "rhodium") (:|seq| (:|pair| 1 KM::|Rh|))
    (:|seq| (:|pair| 1 KM::|Rh|)) (:|seq| (:|pair| 1 KM::|Rh|))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::|Ru| ("ruthenium" "ruthenium") (:|seq| (:|pair| 1 KM::|Ru|))
    (:|seq| (:|pair| 1 KM::|Ru|)) (:|seq| (:|pair| 1 KM::|Ru|))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::N2O NIL (:|seq| (:|pair| 2 KM::N) (:|pair| 1 KM::O))
    (:|seq| (:|pair| 2 KM::N) (:|pair| 1 KM::O))
    (:|seq| (:|pair| 2 KM::N) (:|pair| 1 KM::O))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::|Ar-Molecule| ("argon") (:|seq| (:|pair| 1 KM::|Ar|))
    (:|seq| (:|pair| 1 KM::|Ar|)) (:|seq| (:|pair| 1 KM::|Ar|))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::|C-Molecule| ("carbon") (:|seq| (:|pair| 1 KM::C))
    (:|seq| (:|pair| 1 KM::C)) (:|seq| (:|pair| 1 KM::C))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::|CO-Compound| ("carbon monoxide")
    (:|seq| (:|pair| 1 KM::C) (:|pair| 1 KM::O))
    (:|seq| (:|pair| 1 KM::C) (:|pair| 1 KM::O))
    (:|seq| (:|pair| 1 KM::C) (:|pair| 1 KM::O))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::CO2 ("carbon dioxide")
    (:|seq| (:|pair| 1 KM::C) (:|pair| 2 KM::O))
    (:|seq| (:|pair| 1 KM::C) (:|pair| 2 KM::O))
    (:|seq| (:|pair| 1 KM::C) (:|pair| 2 KM::O))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::|He-Molecule| ("helium") (:|seq| (:|pair| 1 KM::|He|))
    (:|seq| (:|pair| 1 KM::|He|)) (:|seq| (:|pair| 1 KM::|He|))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::|Kr-Molecule| ("krypton") (:|seq| (:|pair| 1 KM::|Kr|))
    (:|seq| (:|pair| 1 KM::|Kr|)) (:|seq| (:|pair| 1 KM::|Kr|))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::NH3 ("ammonia") (:|seq| (:|pair| 1 KM::N) (:|pair| 3 KM::H))
    (:|seq| (:|pair| 1 KM::N) (:|pair| 3 KM::H))
    (:|seq| (:|pair| 1 KM::N) (:|pair| 3 KM::H))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::NO ("nitrogen monoxide")
    (:|seq| (:|pair| 1 KM::N) (:|pair| 1 KM::O))
    (:|seq| (:|pair| 1 KM::N) (:|pair| 1 KM::O))
    (:|seq| (:|pair| 1 KM::N) (:|pair| 1 KM::O))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::NO2 ("nitrogen dioxide")
    (:|seq| (:|pair| 1 KM::N) (:|pair| 2 KM::O))
    (:|seq| (:|pair| 1 KM::N) (:|pair| 2 KM::O))
    (:|seq| (:|pair| 1 KM::N) (:|pair| 2 KM::O))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::|Ne-Molecule| ("neon") (:|seq| (:|pair| 1 KM::|Ne|))
    (:|seq| (:|pair| 1 KM::|Ne|)) (:|seq| (:|pair| 1 KM::|Ne|))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::|Br2| ("bromine gas") (:|seq| (:|pair| 2 KM::|Br|))
    (:|seq| (:|pair| 2 KM::|Br|)) (:|seq| (:|pair| 2 KM::|Br|))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::|Cl2| ("chlorine gas") (:|seq| (:|pair| 2 KM::|Cl|))
    (:|seq| (:|pair| 2 KM::|Cl|)) (:|seq| (:|pair| 2 KM::|Cl|))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::F2 ("fluorine gas") (:|seq| (:|pair| 2 KM::F))
    (:|seq| (:|pair| 2 KM::F)) (:|seq| (:|pair| 2 KM::F))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::H2 ("hydrogen gas") (:|seq| (:|pair| 2 KM::H))
    (:|seq| (:|pair| 2 KM::H)) (:|seq| (:|pair| 2 KM::H))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::I2 ("iodine gas") (:|seq| (:|pair| 2 KM::I))
    (:|seq| (:|pair| 2 KM::I)) (:|seq| (:|pair| 2 KM::I))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::N2 ("nitrogen gas") (:|seq| (:|pair| 2 KM::N))
    (:|seq| (:|pair| 2 KM::N)) (:|seq| (:|pair| 2 KM::N))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::O2 ("oxygen gas") (:|seq| (:|pair| 2 KM::O))
    (:|seq| (:|pair| 2 KM::O)) (:|seq| (:|pair| 2 KM::O))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::|P-Molecule| ("phosphorus") (:|seq| (:|pair| 1 KM::P))
    (:|seq| (:|pair| 1 KM::P)) (:|seq| (:|pair| 1 KM::P))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::|Rn-Molecule| ("radon") (:|seq| (:|pair| 1 KM::|Rn|))
    (:|seq| (:|pair| 1 KM::|Rn|)) (:|seq| (:|pair| 1 KM::|Rn|))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::|S-Molecule| ("sulfur") (:|seq| (:|pair| 1 KM::S))
    (:|seq| (:|pair| 1 KM::S)) (:|seq| (:|pair| 1 KM::S))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::SO2 ("sulfur dioxide")
    (:|seq| (:|pair| 1 KM::S) (:|pair| 2 KM::O))
    (:|seq| (:|pair| 1 KM::S) (:|pair| 2 KM::O))
    (:|seq| (:|pair| 1 KM::S) (:|pair| 2 KM::O))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::SO3 ("sulfur trioxide")
    (:|seq| (:|pair| 1 KM::S) (:|pair| 3 KM::O))
    (:|seq| (:|pair| 1 KM::S) (:|pair| 3 KM::O))
    (:|seq| (:|pair| 1 KM::S) (:|pair| 3 KM::O))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::|VOCl| ("vanadium hypochlorite")
    (:|seq| (:|pair| 1 KM::V) (:|pair| 1 KM::O) (:|pair| 1 KM::|Cl|))
    (:|seq| (:|pair| 1 KM::V) (:|pair| 1 KM::O) (:|pair| 1 KM::|Cl|))
    (:|seq| (:|pair| 1 KM::V) (:|pair| 1 KM::O) (:|pair| 1 KM::|Cl|))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::|Xe-Molecule| ("xenon") (:|seq| (:|pair| 1 KM::|Xe|))
    (:|seq| (:|pair| 1 KM::|Xe|)) (:|seq| (:|pair| 1 KM::|Xe|))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::C12H22O11 ("sucrose" "sugar" "table sugar")
    (:|seq| (:|pair| 12 KM::C) (:|pair| 22 KM::H) (:|pair| 11 KM::O))
    (:|seq| (:|pair| 12 KM::C) (:|pair| 22 KM::H) (:|pair| 11 KM::O))
    (:|seq| (:|pair| 12 KM::C) (:|pair| 22 KM::H) (:|pair| 11 KM::O))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::C3H7OH ("propanol")
    (:|seq| (:|pair| 3 KM::C) (:|pair| 8 KM::H) (:|pair| 1 KM::O))
    (:|seq| (:|pair| 3 KM::C) (:|pair| 8 KM::H) (:|pair| 1 KM::O))
    (:|seq| (:|pair| 3 KM::C) (:|pair| 8 KM::H) (:|pair| 1 KM::O))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::C6H12O6 ("glucose")
    (:|seq| (:|pair| 6 KM::C) (:|pair| 12 KM::H) (:|pair| 6 KM::O))
    (:|seq| (:|pair| 6 KM::C) (:|pair| 12 KM::H) (:|pair| 6 KM::O))
    (:|seq| (:|pair| 6 KM::C) (:|pair| 12 KM::H) (:|pair| 6 KM::O))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::CH3CH2OH ("ethanol")
    (:|seq| (:|pair| 1 KM::C) (:|pair| 3 KM::H) (:|pair| 1 KM::C)
     (:|pair| 2 KM::H) (:|pair| 1 KM::O) (:|pair| 1 KM::H))
    (:|seq| (:|pair| 1 KM::C) (:|pair| 3 KM::H) (:|pair| 1 KM::C)
     (:|pair| 2 KM::H) (:|pair| 1 KM::O) (:|pair| 1 KM::H))
    (:|seq| (:|pair| 2 KM::C) (:|pair| 6 KM::H) (:|pair| 1 KM::O))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::CH3OH ("methanol")
    (:|seq| (:|pair| 1 KM::C) (:|pair| 1 KM::O) (:|pair| 4 KM::H)) NIL
    (:|seq| (:|pair| 1 KM::C) (:|pair| 1 KM::O) (:|pair| 4 KM::H))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::C10H22 ("decane")
    (:|seq| (:|pair| 10 KM::C) (:|pair| 22 KM::H))
    (:|seq| (:|pair| 10 KM::C) (:|pair| 22 KM::H))
    (:|seq| (:|pair| 10 KM::C) (:|pair| 22 KM::H))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::C2H4 ("ethylene" "ethene")
    (:|seq| (:|pair| 2 KM::C) (:|pair| 4 KM::H))
    (:|seq| (:|pair| 2 KM::C) (:|pair| 4 KM::H))
    (:|seq| (:|pair| 2 KM::C) (:|pair| 4 KM::H))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::C2H6 ("ethane") (:|seq| (:|pair| 2 KM::C) (:|pair| 6 KM::H))
    (:|seq| (:|pair| 2 KM::C) (:|pair| 6 KM::H))
    (:|seq| (:|pair| 2 KM::C) (:|pair| 6 KM::H))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::C3H6 ("propene") (:|seq| (:|pair| 3 KM::C) (:|pair| 6 KM::H))
    (:|seq| (:|pair| 3 KM::C) (:|pair| 6 KM::H))
    (:|seq| (:|pair| 3 KM::C) (:|pair| 6 KM::H))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::C3H8 ("propane") (:|seq| (:|pair| 3 KM::C) (:|pair| 8 KM::H))
    (:|seq| (:|pair| 3 KM::C) (:|pair| 8 KM::H))
    (:|seq| (:|pair| 3 KM::C) (:|pair| 8 KM::H))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::C5H12 ("pentane") (:|seq| (:|pair| 5 KM::C) (:|pair| 12 KM::H))
    (:|seq| (:|pair| 5 KM::C) (:|pair| 12 KM::H))
    (:|seq| (:|pair| 5 KM::C) (:|pair| 12 KM::H))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::C8H18 ("octane") (:|seq| (:|pair| 8 KM::C) (:|pair| 18 KM::H))
    (:|seq| (:|pair| 8 KM::C) (:|pair| 18 KM::H))
    (:|seq| (:|pair| 8 KM::C) (:|pair| 18 KM::H))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::CH4 ("methane") (:|seq| (:|pair| 1 KM::C) (:|pair| 4 KM::H))
    (:|seq| (:|pair| 1 KM::C) (:|pair| 4 KM::H))
    (:|seq| (:|pair| 1 KM::C) (:|pair| 4 KM::H))
    (:|pair| 0 KM::|*unity|) NIL NIL)
   (KM::|AsO3-Minus-3| ("arsenite")
    (:|seq| (:|pair| 1 KM::|As|) (:|pair| 3 KM::O))
    (:|seq| (:|pair| 1 KM::|As|) (:|pair| 3 KM::O))
    (:|seq| (:|pair| 1 KM::|As|) (:|pair| 3 KM::O))
    (:|pair| -3 KM::|*unity|) ("arsenous") NIL)
   (KM::|AsO4-Minus-3| ("arsenate")
    (:|seq| (:|pair| 1 KM::|As|) (:|pair| 4 KM::O))
    (:|seq| (:|pair| 1 KM::|As|) (:|pair| 4 KM::O))
    (:|seq| (:|pair| 1 KM::|As|) (:|pair| 4 KM::O))
    (:|pair| -3 KM::|*unity|) ("arsenic") NIL)
   (KM::|AuCl4-Minus| ("gold chloride")
    (:|seq| (:|pair| 1 KM::|Au|) (:|pair| 4 KM::|Cl|))
    (:|seq| (:|pair| 1 KM::|Au|) (:|pair| 4 KM::|Cl|))
    (:|seq| (:|pair| 1 KM::|Au|) (:|pair| 4 KM::|Cl|))
    (:|pair| -1 KM::|*unity|) NIL NIL)
   (KM::|BO3-Minus-3| ("borate")
    (:|seq| (:|pair| 1 KM::B) (:|pair| 3 KM::O))
    (:|seq| (:|pair| 1 KM::B) (:|pair| 3 KM::O))
    (:|seq| (:|pair| 1 KM::B) (:|pair| 3 KM::O))
    (:|pair| -3 KM::|*unity|) ("boric") NIL)
   (KM::|Br-Minus| ("bromide") (:|seq| (:|pair| 1 KM::|Br|))
    (:|seq| (:|pair| 1 KM::|Br|)) (:|seq| (:|pair| 1 KM::|Br|))
    (:|pair| -1 KM::|*unity|) ("hydrobromic") NIL)
   (KM::|BrO-Minus| ("hypobromite")
    (:|seq| (:|pair| 1 KM::|Br|) (:|pair| 1 KM::O))
    (:|seq| (:|pair| 1 KM::|Br|) (:|pair| 1 KM::O))
    (:|seq| (:|pair| 1 KM::|Br|) (:|pair| 1 KM::O))
    (:|pair| -1 KM::|*unity|) ("hypobromous") NIL)
   (KM::|C2H2O2Cl-Minus| ("chloroacetate")
    (:|seq| (:|pair| 2 KM::C) (:|pair| 2 KM::H) (:|pair| 2 KM::O)
     (:|pair| 1 KM::|Cl|))
    (:|seq| (:|pair| 2 KM::C) (:|pair| 2 KM::H) (:|pair| 2 KM::O)
     (:|pair| 1 KM::|Cl|))
    (:|seq| (:|pair| 2 KM::C) (:|pair| 2 KM::H) (:|pair| 2 KM::O)
     (:|pair| 1 KM::|Cl|))
    (:|pair| -1 KM::|*unity|) NIL NIL)
   (KM::|C2H3O2-Minus| ("acetate")
    (:|seq| (:|pair| 2 KM::C) (:|pair| 3 KM::H) (:|pair| 2 KM::O))
    (:|seq| (:|pair| 2 KM::C) (:|pair| 3 KM::H) (:|pair| 2 KM::O))
    (:|seq| (:|pair| 2 KM::C) (:|pair| 3 KM::H) (:|pair| 2 KM::O))
    (:|pair| -1 KM::|*unity|) ("acetic") NIL)
   (KM::|C2H5COO-Minus| ("propanoate")
    (:|seq| (:|pair| 2 KM::C) (:|pair| 5 KM::H) (:|pair| 1 KM::C)
     (:|pair| 1 KM::O) (:|pair| 1 KM::O))
    (:|seq| (:|pair| 2 KM::C) (:|pair| 5 KM::H) (:|pair| 1 KM::C)
     (:|pair| 1 KM::O) (:|pair| 1 KM::O))
    (:|seq| (:|pair| 3 KM::C) (:|pair| 5 KM::H) (:|pair| 2 KM::O))
    (:|pair| -1 KM::|*unity|) ("propanoic") NIL)
   (KM::|C2O4-Minus-2| ("oxalate")
    (:|seq| (:|pair| 2 KM::C) (:|pair| 4 KM::O))
    (:|seq| (:|pair| 2 KM::C) (:|pair| 4 KM::O))
    (:|seq| (:|pair| 2 KM::C) (:|pair| 4 KM::O))
    (:|pair| -2 KM::|*unity|) ("oxalic") NIL)
   (KM::|C3H2O4-Minus-2| ("malonate" "propanedioate")
    (:|seq| (:|pair| 3 KM::C) (:|pair| 2 KM::H) (:|pair| 4 KM::O))
    (:|seq| (:|pair| 3 KM::C) (:|pair| 2 KM::H) (:|pair| 4 KM::O))
    (:|seq| (:|pair| 3 KM::C) (:|pair| 2 KM::H) (:|pair| 4 KM::O))
    (:|pair| -2 KM::|*unity|) NIL NIL)
   (KM::|C3H5O2-Minus| ("propionate")
    (:|seq| (:|pair| 3 KM::C) (:|pair| 5 KM::H) (:|pair| 2 KM::O))
    (:|seq| (:|pair| 3 KM::C) (:|pair| 5 KM::H) (:|pair| 2 KM::O))
    (:|seq| (:|pair| 3 KM::C) (:|pair| 5 KM::H) (:|pair| 2 KM::O))
    (:|pair| -1 KM::|*unity|) NIL NIL)
   (KM::|C3H5O3-Minus| ("lactate" "2-hydroxypropanoate")
    (:|seq| (:|pair| 3 KM::C) (:|pair| 5 KM::H) (:|pair| 3 KM::O))
    (:|seq| (:|pair| 3 KM::C) (:|pair| 5 KM::H) (:|pair| 3 KM::O))
    (:|seq| (:|pair| 3 KM::C) (:|pair| 5 KM::H) (:|pair| 3 KM::O))
    (:|pair| -1 KM::|*unity|) NIL NIL)
   (KM::|C4H4O6-Minus-2|
    ("tartrate" "2,3-dihydroxybutanedioate" "2,3-dihydroxysuccinate")
    (:|seq| (:|pair| 4 KM::C) (:|pair| 4 KM::H) (:|pair| 6 KM::O))
    (:|seq| (:|pair| 4 KM::C) (:|pair| 4 KM::H) (:|pair| 6 KM::O))
    (:|seq| (:|pair| 4 KM::C) (:|pair| 4 KM::H) (:|pair| 6 KM::O))
    (:|pair| -2 KM::|*unity|) NIL NIL)
   (KM::|C4H7O2-Minus| ("butyrate")
    (:|seq| (:|pair| 4 KM::C) (:|pair| 7 KM::H) (:|pair| 2 KM::O))
    (:|seq| (:|pair| 4 KM::C) (:|pair| 7 KM::H) (:|pair| 2 KM::O))
    (:|seq| (:|pair| 4 KM::C) (:|pair| 7 KM::H) (:|pair| 2 KM::O))
    (:|pair| -1 KM::|*unity|) NIL NIL)
   (KM::|C6H5O-Minus| ("phenolate" "phenoxide")
    (:|seq| (:|pair| 6 KM::C) (:|pair| 5 KM::H) (:|pair| 1 KM::O))
    (:|seq| (:|pair| 6 KM::C) (:|pair| 5 KM::H) (:|pair| 1 KM::O))
    (:|seq| (:|pair| 6 KM::C) (:|pair| 5 KM::H) (:|pair| 1 KM::O))
    (:|pair| -1 KM::|*unity|) NIL NIL)
   (KM::|C6H5O7-Minus-3| ("2-hydroxypropane-1,2,3-tricarboxylate")
    (:|seq| (:|pair| 6 KM::C) (:|pair| 5 KM::H) (:|pair| 7 KM::O))
    (:|seq| (:|pair| 6 KM::C) (:|pair| 5 KM::H) (:|pair| 7 KM::O))
    (:|seq| (:|pair| 6 KM::C) (:|pair| 5 KM::H) (:|pair| 7 KM::O))
    (:|pair| -3 KM::|*unity|) NIL NIL)
   (KM::|C6H6O6-Minus-2| ("ascorbate" "vitamin c")
    (:|seq| (:|pair| 6 KM::C) (:|pair| 6 KM::H) (:|pair| 6 KM::O))
    (:|seq| (:|pair| 6 KM::C) (:|pair| 6 KM::H) (:|pair| 6 KM::O))
    (:|seq| (:|pair| 6 KM::C) (:|pair| 6 KM::H) (:|pair| 6 KM::O))
    (:|pair| -2 KM::|*unity|) NIL NIL)
   (KM::|C7H5O-Minus| ("benzoyl")
    (:|seq| (:|pair| 7 KM::C) (:|pair| 5 KM::H) (:|pair| 1 KM::O))
    (:|seq| (:|pair| 7 KM::C) (:|pair| 5 KM::H) (:|pair| 1 KM::O))
    (:|seq| (:|pair| 7 KM::C) (:|pair| 5 KM::H) (:|pair| 1 KM::O))
    (:|pair| -1 KM::|*unity|) NIL NIL)
   (KM::|C7H5O2-Minus| ("benzoate")
    (:|seq| (:|pair| 7 KM::C) (:|pair| 5 KM::H) (:|pair| 2 KM::O))
    (:|seq| (:|pair| 7 KM::C) (:|pair| 5 KM::H) (:|pair| 2 KM::O))
    (:|seq| (:|pair| 7 KM::C) (:|pair| 5 KM::H) (:|pair| 2 KM::O))
    (:|pair| -1 KM::|*unity|) ("benzoic") NIL)
   (KM::|CH3-Minus| ("methyl")
    (:|seq| (:|pair| 1 KM::C) (:|pair| 3 KM::H))
    (:|seq| (:|pair| 1 KM::C) (:|pair| 3 KM::H))
    (:|seq| (:|pair| 1 KM::C) (:|pair| 3 KM::H))
    (:|pair| -1 KM::|*unity|) NIL NIL)
   (KM::|CH3COO-Minus| ("acetate")
    (:|seq| (:|pair| 1 KM::C) (:|pair| 3 KM::H) (:|pair| 1 KM::C)
     (:|pair| 1 KM::O) (:|pair| 1 KM::O))
    (:|seq| (:|pair| 1 KM::C) (:|pair| 3 KM::H) (:|pair| 1 KM::C)
     (:|pair| 1 KM::O) (:|pair| 1 KM::O))
    (:|seq| (:|pair| 2 KM::C) (:|pair| 3 KM::H) (:|pair| 2 KM::O))
    (:|pair| -1 KM::|*unity|) ("acetic") NIL)
   (KM::|CHO2-Minus| ("formate")
    (:|seq| (:|pair| 1 KM::C) (:|pair| 1 KM::H) (:|pair| 2 KM::O))
    (:|seq| (:|pair| 1 KM::C) (:|pair| 1 KM::H) (:|pair| 2 KM::O))
    (:|seq| (:|pair| 1 KM::C) (:|pair| 1 KM::H) (:|pair| 2 KM::O))
    (:|pair| -1 KM::|*unity|) ("formic") NIL)
   (KM::|CN-Minus| ("cyanide")
    (:|seq| (:|pair| 1 KM::C) (:|pair| 1 KM::N))
    (:|seq| (:|pair| 1 KM::C) (:|pair| 1 KM::N))
    (:|seq| (:|pair| 1 KM::C) (:|pair| 1 KM::N))
    (:|pair| -1 KM::|*unity|) ("hydrocyanic") NIL)
   (KM::|CNO-Minus| ("cyanate")
    (:|seq| (:|pair| 1 KM::C) (:|pair| 1 KM::N) (:|pair| 1 KM::O))
    (:|seq| (:|pair| 1 KM::C) (:|pair| 1 KM::N) (:|pair| 1 KM::O))
    (:|seq| (:|pair| 1 KM::C) (:|pair| 1 KM::N) (:|pair| 1 KM::O))
    (:|pair| -1 KM::|*unity|) ("cyanic") NIL)
   (KM::|CO3-Minus-2| ("carbonate")
    (:|seq| (:|pair| 1 KM::C) (:|pair| 3 KM::O))
    (:|seq| (:|pair| 1 KM::C) (:|pair| 3 KM::O))
    (:|seq| (:|pair| 1 KM::C) (:|pair| 3 KM::O))
    (:|pair| -2 KM::|*unity|) ("carbonic") NIL)
   (KM::|Cl-Minus| ("chloride") (:|seq| (:|pair| 1 KM::|Cl|))
    (:|seq| (:|pair| 1 KM::|Cl|)) (:|seq| (:|pair| 1 KM::|Cl|))
    (:|pair| -1 KM::|*unity|) ("hydrochloric") NIL)
   (KM::|ClO-Minus| ("hypochlorite")
    (:|seq| (:|pair| 1 KM::|Cl|) (:|pair| 1 KM::O))
    (:|seq| (:|pair| 1 KM::|Cl|) (:|pair| 1 KM::O))
    (:|seq| (:|pair| 1 KM::|Cl|) (:|pair| 1 KM::O))
    (:|pair| -1 KM::|*unity|) ("hypochlorous") NIL)
   (KM::|ClO2-Minus| ("chlorite")
    (:|seq| (:|pair| 1 KM::|Cl|) (:|pair| 2 KM::O))
    (:|seq| (:|pair| 1 KM::|Cl|) (:|pair| 2 KM::O))
    (:|seq| (:|pair| 1 KM::|Cl|) (:|pair| 2 KM::O))
    (:|pair| -1 KM::|*unity|) ("chlorous") NIL)
   (KM::|ClO3-Minus| ("chlorate")
    (:|seq| (:|pair| 1 KM::|Cl|) (:|pair| 3 KM::O))
    (:|seq| (:|pair| 1 KM::|Cl|) (:|pair| 3 KM::O))
    (:|seq| (:|pair| 1 KM::|Cl|) (:|pair| 3 KM::O))
    (:|pair| -1 KM::|*unity|) ("chloric") NIL)
   (KM::|ClO4-Minus| ("perchlorate")
    (:|seq| (:|pair| 1 KM::|Cl|) (:|pair| 4 KM::O))
    (:|seq| (:|pair| 1 KM::|Cl|) (:|pair| 4 KM::O))
    (:|seq| (:|pair| 1 KM::|Cl|) (:|pair| 4 KM::O))
    (:|pair| -1 KM::|*unity|) ("perchloric") NIL)
   (KM::|Cr2O7-Minus-2| ("dichromate")
    (:|seq| (:|pair| 2 KM::|Cr|) (:|pair| 7 KM::O))
    (:|seq| (:|pair| 2 KM::|Cr|) (:|pair| 7 KM::O))
    (:|seq| (:|pair| 2 KM::|Cr|) (:|pair| 7 KM::O))
    (:|pair| -2 KM::|*unity|) ("dichromic") NIL)
   (KM::|CrO4-Minus-2| ("chromate")
    (:|seq| (:|pair| 1 KM::|Cr|) (:|pair| 4 KM::O))
    (:|seq| (:|pair| 1 KM::|Cr|) (:|pair| 4 KM::O))
    (:|seq| (:|pair| 1 KM::|Cr|) (:|pair| 4 KM::O))
    (:|pair| -2 KM::|*unity|) ("chromic") NIL)
   (KM::|F-Minus| ("fluoride") (:|seq| (:|pair| 1 KM::F))
    (:|seq| (:|pair| 1 KM::F)) (:|seq| (:|pair| 1 KM::F))
    (:|pair| -1 KM::|*unity|) ("hydrofluoric") NIL)
   (KM::|H-Minus| ("hydride") (:|seq| (:|pair| 1 KM::H))
    (:|seq| (:|pair| 1 KM::H)) (:|seq| (:|pair| 1 KM::H))
    (:|pair| -1 KM::|*unity|) NIL NIL)
   (KM::|H2AsO3-Minus| ("dihydrogen arsenite")
    (:|seq| (:|pair| 2 KM::H) (:|pair| 1 KM::|As|) (:|pair| 3 KM::O))
    (:|seq| (:|pair| 2 KM::H) (:|pair| 1 KM::|As|) (:|pair| 3 KM::O))
    (:|seq| (:|pair| 2 KM::H) (:|pair| 1 KM::|As|) (:|pair| 3 KM::O))
    (:|pair| -1 KM::|*unity|) NIL NIL)
   (KM::|H2AsO4-Minus| ("dihydrogen arsenate")
    (:|seq| (:|pair| 2 KM::H) (:|pair| 1 KM::|As|) (:|pair| 4 KM::O))
    (:|seq| (:|pair| 2 KM::H) (:|pair| 1 KM::|As|) (:|pair| 4 KM::O))
    (:|seq| (:|pair| 2 KM::H) (:|pair| 1 KM::|As|) (:|pair| 4 KM::O))
    (:|pair| -1 KM::|*unity|) NIL NIL)
   (KM::|H2BO3-Minus| ("dihydrogen borate")
    (:|seq| (:|pair| 2 KM::H) (:|pair| 1 KM::B) (:|pair| 3 KM::O))
    (:|seq| (:|pair| 2 KM::H) (:|pair| 1 KM::B) (:|pair| 3 KM::O))
    (:|seq| (:|pair| 2 KM::H) (:|pair| 1 KM::B) (:|pair| 3 KM::O))
    (:|pair| -1 KM::|*unity|) NIL NIL)
   (KM::|H2C6H5O7-Minus| ("citrate")
    (:|seq| (:|pair| 2 KM::H) (:|pair| 6 KM::C) (:|pair| 5 KM::H)
     (:|pair| 7 KM::O))
    (:|seq| (:|pair| 2 KM::H) (:|pair| 6 KM::C) (:|pair| 5 KM::H)
     (:|pair| 7 KM::O))
    (:|seq| (:|pair| 7 KM::H) (:|pair| 6 KM::C) (:|pair| 7 KM::O))
    (:|pair| -1 KM::|*unity|) NIL NIL)
   (KM::|H2P2O7-Minus-2| ("dihydrogen pyrophosphate")
    (:|seq| (:|pair| 2 KM::H) (:|pair| 2 KM::P) (:|pair| 7 KM::O))
    (:|seq| (:|pair| 2 KM::H) (:|pair| 2 KM::P) (:|pair| 7 KM::O))
    (:|seq| (:|pair| 2 KM::H) (:|pair| 2 KM::P) (:|pair| 7 KM::O))
    (:|pair| -2 KM::|*unity|) NIL NIL)
   (KM::|H2PO3-Minus| ("dihydrogen phosphite")
    (:|seq| (:|pair| 2 KM::H) (:|pair| 1 KM::P) (:|pair| 3 KM::O))
    (:|seq| (:|pair| 2 KM::H) (:|pair| 1 KM::P) (:|pair| 3 KM::O))
    (:|seq| (:|pair| 2 KM::H) (:|pair| 1 KM::P) (:|pair| 3 KM::O))
    (:|pair| -1 KM::|*unity|) NIL NIL)
   (KM::|H2PO4-Minus| ("dihydrogen phosphate")
    (:|seq| (:|pair| 2 KM::H) (:|pair| 1 KM::P) (:|pair| 4 KM::O))
    (:|seq| (:|pair| 2 KM::H) (:|pair| 1 KM::P) (:|pair| 4 KM::O))
    (:|seq| (:|pair| 2 KM::H) (:|pair| 1 KM::P) (:|pair| 4 KM::O))
    (:|pair| -1 KM::|*unity|) NIL NIL)
   (KM::|H3IO6-Minus-2| ("trihydrogen orthoperiodate")
    (:|seq| (:|pair| 3 KM::H) (:|pair| 1 KM::I) (:|pair| 6 KM::O))
    (:|seq| (:|pair| 3 KM::H) (:|pair| 1 KM::I) (:|pair| 6 KM::O))
    (:|seq| (:|pair| 3 KM::H) (:|pair| 1 KM::I) (:|pair| 6 KM::O))
    (:|pair| -2 KM::|*unity|) NIL NIL)
   (KM::|H3P2O7-Minus| ("trihydrogen pyrophosphate")
    (:|seq| (:|pair| 3 KM::H) (:|pair| 2 KM::P) (:|pair| 7 KM::O))
    (:|seq| (:|pair| 3 KM::H) (:|pair| 2 KM::P) (:|pair| 7 KM::O))
    (:|seq| (:|pair| 3 KM::H) (:|pair| 2 KM::P) (:|pair| 7 KM::O))
    (:|pair| -1 KM::|*unity|) NIL NIL)
   (KM::|H4IO6-Minus| ("tetrahydrogen orthoperiodate")
    (:|seq| (:|pair| 4 KM::H) (:|pair| 1 KM::I) (:|pair| 6 KM::O))
    (:|seq| (:|pair| 4 KM::H) (:|pair| 1 KM::I) (:|pair| 6 KM::O))
    (:|seq| (:|pair| 4 KM::H) (:|pair| 1 KM::I) (:|pair| 6 KM::O))
    (:|pair| -1 KM::|*unity|) NIL NIL)
   (KM::|HAsO4-Minus-2| ("hydrogen arsenate")
    (:|seq| (:|pair| 1 KM::H) (:|pair| 1 KM::|As|) (:|pair| 4 KM::O))
    (:|seq| (:|pair| 1 KM::H) (:|pair| 1 KM::|As|) (:|pair| 4 KM::O))
    (:|seq| (:|pair| 1 KM::H) (:|pair| 1 KM::|As|) (:|pair| 4 KM::O))
    (:|pair| -2 KM::|*unity|) NIL NIL)
   (KM::|HBO3-Minus-2| ("hydrogen borate")
    (:|seq| (:|pair| 1 KM::H) (:|pair| 1 KM::B) (:|pair| 3 KM::O))
    (:|seq| (:|pair| 1 KM::H) (:|pair| 1 KM::B) (:|pair| 3 KM::O))
    (:|seq| (:|pair| 1 KM::H) (:|pair| 1 KM::B) (:|pair| 3 KM::O))
    (:|pair| -2 KM::|*unity|) NIL NIL)
   (KM::|HC2O4-Minus| ("hydrogen oxalate")
    (:|seq| (:|pair| 1 KM::H) (:|pair| 2 KM::C) (:|pair| 4 KM::O))
    (:|seq| (:|pair| 1 KM::H) (:|pair| 2 KM::C) (:|pair| 4 KM::O))
    (:|seq| (:|pair| 1 KM::H) (:|pair| 2 KM::C) (:|pair| 4 KM::O))
    (:|pair| -1 KM::|*unity|) NIL NIL)
   (KM::|HC3H2O4-Minus| ("malonate")
    (:|seq| (:|pair| 1 KM::H) (:|pair| 3 KM::C) (:|pair| 2 KM::H)
     (:|pair| 4 KM::O))
    (:|seq| (:|pair| 1 KM::H) (:|pair| 3 KM::C) (:|pair| 2 KM::H)
     (:|pair| 4 KM::O))
    (:|seq| (:|pair| 3 KM::H) (:|pair| 3 KM::C) (:|pair| 4 KM::O))
    (:|pair| -1 KM::|*unity|) NIL NIL)
   (KM::|HC4H4O6-Minus| ("bitartrate")
    (:|seq| (:|pair| 1 KM::H) (:|pair| 4 KM::C) (:|pair| 4 KM::H)
     (:|pair| 6 KM::O))
    (:|seq| (:|pair| 1 KM::H) (:|pair| 4 KM::C) (:|pair| 4 KM::H)
     (:|pair| 6 KM::O))
    (:|seq| (:|pair| 5 KM::H) (:|pair| 4 KM::C) (:|pair| 6 KM::O))
    (:|pair| -1 KM::|*unity|) NIL NIL)
   (KM::|HC6H5O7-Minus-2| ("citrate")
    (:|seq| (:|pair| 1 KM::H) (:|pair| 6 KM::C) (:|pair| 5 KM::H)
     (:|pair| 7 KM::O))
    (:|seq| (:|pair| 1 KM::H) (:|pair| 6 KM::C) (:|pair| 5 KM::H)
     (:|pair| 7 KM::O))
    (:|seq| (:|pair| 6 KM::H) (:|pair| 6 KM::C) (:|pair| 7 KM::O))
    (:|pair| -2 KM::|*unity|) NIL NIL)
   (KM::|HC6H6O6-Minus| ("ascorbate" "vitamin c")
    (:|seq| (:|pair| 1 KM::H) (:|pair| 6 KM::C) (:|pair| 6 KM::H)
     (:|pair| 6 KM::O))
    (:|seq| (:|pair| 1 KM::H) (:|pair| 6 KM::C) (:|pair| 6 KM::H)
     (:|pair| 6 KM::O))
    (:|seq| (:|pair| 7 KM::H) (:|pair| 6 KM::C) (:|pair| 6 KM::O))
    (:|pair| -1 KM::|*unity|) NIL NIL)
   (KM::|HCO3-Minus| ("hydrogen carbonate" "bicarbonate")
    (:|seq| (:|pair| 1 KM::H) (:|pair| 1 KM::C) (:|pair| 3 KM::O))
    (:|seq| (:|pair| 1 KM::H) (:|pair| 1 KM::C) (:|pair| 3 KM::O))
    (:|seq| (:|pair| 1 KM::H) (:|pair| 1 KM::C) (:|pair| 3 KM::O))
    (:|pair| -1 KM::|*unity|) NIL NIL)
   (KM::|HCrO4-Minus| ("hydrogen chromate")
    (:|seq| (:|pair| 1 KM::H) (:|pair| 1 KM::|Cr|) (:|pair| 4 KM::O))
    (:|seq| (:|pair| 1 KM::H) (:|pair| 1 KM::|Cr|) (:|pair| 4 KM::O))
    (:|seq| (:|pair| 1 KM::H) (:|pair| 1 KM::|Cr|) (:|pair| 4 KM::O))
    (:|pair| -1 KM::|*unity|) NIL NIL)
   (KM::|HO2-Minus| ("hydrogen superoxide")
    (:|seq| (:|pair| 1 KM::H) (:|pair| 2 KM::O))
    (:|seq| (:|pair| 1 KM::H) (:|pair| 2 KM::O))
    (:|seq| (:|pair| 1 KM::H) (:|pair| 2 KM::O))
    (:|pair| -1 KM::|*unity|) NIL NIL)
   (KM::|HPO3-Minus-2| ("hydrogen phosphite")
    (:|seq| (:|pair| 1 KM::H) (:|pair| 1 KM::P) (:|pair| 3 KM::O))
    (:|seq| (:|pair| 1 KM::H) (:|pair| 1 KM::P) (:|pair| 3 KM::O))
    (:|seq| (:|pair| 1 KM::H) (:|pair| 1 KM::P) (:|pair| 3 KM::O))
    (:|pair| -2 KM::|*unity|) NIL NIL)
   (KM::|HPO4-Minus-2| ("hydrogen phosphate")
    (:|seq| (:|pair| 1 KM::H) (:|pair| 1 KM::P) (:|pair| 4 KM::O))
    (:|seq| (:|pair| 1 KM::H) (:|pair| 1 KM::P) (:|pair| 4 KM::O))
    (:|seq| (:|pair| 1 KM::H) (:|pair| 1 KM::P) (:|pair| 4 KM::O))
    (:|pair| -2 KM::|*unity|) NIL NIL)
   (KM::|HS-Minus| ("bisulfide")
    (:|seq| (:|pair| 1 KM::H) (:|pair| 1 KM::S))
    (:|seq| (:|pair| 1 KM::H) (:|pair| 1 KM::S))
    (:|seq| (:|pair| 1 KM::H) (:|pair| 1 KM::S))
    (:|pair| -1 KM::|*unity|) NIL NIL)
   (KM::|HSO3-Minus| ("hydrogen sulfite" "bisulfite")
    (:|seq| (:|pair| 1 KM::H) (:|pair| 1 KM::S) (:|pair| 3 KM::O))
    (:|seq| (:|pair| 1 KM::H) (:|pair| 1 KM::S) (:|pair| 3 KM::O))
    (:|seq| (:|pair| 1 KM::H) (:|pair| 1 KM::S) (:|pair| 3 KM::O))
    (:|pair| -1 KM::|*unity|) NIL NIL)
   (KM::|HSO4-Minus| ("hydrogen sulfate" "bisulfate")
    (:|seq| (:|pair| 1 KM::H) (:|pair| 1 KM::S) (:|pair| 4 KM::O))
    (:|seq| (:|pair| 1 KM::H) (:|pair| 1 KM::S) (:|pair| 4 KM::O))
    (:|seq| (:|pair| 1 KM::H) (:|pair| 1 KM::S) (:|pair| 4 KM::O))
    (:|pair| -1 KM::|*unity|) NIL NIL)
   (KM::|HSeO3-Minus| ("hydrogen selenite")
    (:|seq| (:|pair| 1 KM::H) (:|pair| 1 KM::|Se|) (:|pair| 3 KM::O))
    (:|seq| (:|pair| 1 KM::H) (:|pair| 1 KM::|Se|) (:|pair| 3 KM::O))
    (:|seq| (:|pair| 1 KM::H) (:|pair| 1 KM::|Se|) (:|pair| 3 KM::O))
    (:|pair| -1 KM::|*unity|) NIL NIL)
   (KM::|HSeO4-Minus| ("hydrogen selenate")
    (:|seq| (:|pair| 1 KM::H) (:|pair| 1 KM::|Se|) (:|pair| 4 KM::O))
    (:|seq| (:|pair| 1 KM::H) (:|pair| 1 KM::|Se|) (:|pair| 4 KM::O))
    (:|seq| (:|pair| 1 KM::H) (:|pair| 1 KM::|Se|) (:|pair| 4 KM::O))
    (:|pair| -1 KM::|*unity|) NIL NIL)
   (KM::|I-Minus| ("iodide") (:|seq| (:|pair| 1 KM::I))
    (:|seq| (:|pair| 1 KM::I)) (:|seq| (:|pair| 1 KM::I))
    (:|pair| -1 KM::|*unity|) ("hydroiodic") NIL)
   (KM::|IO-Minus| ("hypoiodite")
    (:|seq| (:|pair| 1 KM::I) (:|pair| 1 KM::O))
    (:|seq| (:|pair| 1 KM::I) (:|pair| 1 KM::O))
    (:|seq| (:|pair| 1 KM::I) (:|pair| 1 KM::O))
    (:|pair| -1 KM::|*unity|) ("hypoiodous") NIL)
   (KM::|IO3-Minus| ("iodate")
    (:|seq| (:|pair| 1 KM::I) (:|pair| 3 KM::O))
    (:|seq| (:|pair| 1 KM::I) (:|pair| 3 KM::O))
    (:|seq| (:|pair| 1 KM::I) (:|pair| 3 KM::O))
    (:|pair| -1 KM::|*unity|) ("iodic") NIL)
   (KM::|IO6-Minus-5| ("orthoperiodate")
    (:|seq| (:|pair| 1 KM::I) (:|pair| 6 KM::O))
    (:|seq| (:|pair| 1 KM::I) (:|pair| 6 KM::O))
    (:|seq| (:|pair| 1 KM::I) (:|pair| 6 KM::O))
    (:|pair| -5 KM::|*unity|) ("orthoperiodic") NIL)
   (KM::|MnO4-Minus| ("permanganate")
    (:|seq| (:|pair| 1 KM::|Mn|) (:|pair| 4 KM::O))
    (:|seq| (:|pair| 1 KM::|Mn|) (:|pair| 4 KM::O))
    (:|seq| (:|pair| 1 KM::|Mn|) (:|pair| 4 KM::O))
    (:|pair| -1 KM::|*unity|) ("permanganic") NIL)
   (KM::|N-Minus-3| ("nitride") (:|seq| (:|pair| 1 KM::N))
    (:|seq| (:|pair| 1 KM::N)) (:|seq| (:|pair| 1 KM::N))
    (:|pair| -3 KM::|*unity|) ("hydronitric") NIL)
   (KM::|N3-Minus| ("azide") (:|seq| (:|pair| 3 KM::N))
    (:|seq| (:|pair| 3 KM::N)) (:|seq| (:|pair| 3 KM::N))
    (:|pair| -1 KM::|*unity|) NIL NIL)
   (KM::|NH2-Minus| ("amido group")
    (:|seq| (:|pair| 1 KM::N) (:|pair| 2 KM::H))
    (:|seq| (:|pair| 1 KM::N) (:|pair| 2 KM::H))
    (:|seq| (:|pair| 1 KM::N) (:|pair| 2 KM::H))
    (:|pair| -1 KM::|*unity|) NIL NIL)
   (KM::|NO2-Minus| ("nitrite")
    (:|seq| (:|pair| 1 KM::N) (:|pair| 2 KM::O))
    (:|seq| (:|pair| 1 KM::N) (:|pair| 2 KM::O))
    (:|seq| (:|pair| 1 KM::N) (:|pair| 2 KM::O))
    (:|pair| -1 KM::|*unity|) ("nitrous") NIL)
   (KM::|NO3-Minus| ("nitrate")
    (:|seq| (:|pair| 1 KM::N) (:|pair| 3 KM::O))
    (:|seq| (:|pair| 1 KM::N) (:|pair| 3 KM::O))
    (:|seq| (:|pair| 1 KM::N) (:|pair| 3 KM::O))
    (:|pair| -1 KM::|*unity|) ("nitric") NIL)
   (KM::|O-Minus-2| ("oxide") (:|seq| (:|pair| 1 KM::O))
    (:|seq| (:|pair| 1 KM::O)) (:|seq| (:|pair| 1 KM::O))
    (:|pair| -2 KM::|*unity|) NIL NIL)
   (KM::|O-Minus| ("oxide") (:|seq| (:|pair| 1 KM::O))
    (:|seq| (:|pair| 1 KM::O)) (:|seq| (:|pair| 1 KM::O))
    (:|pair| -1 KM::|*unity|) NIL NIL)
   (KM::|O2-Minus-2| ("dioxide") (:|seq| (:|pair| 2 KM::O))
    (:|seq| (:|pair| 2 KM::O)) (:|seq| (:|pair| 2 KM::O))
    (:|pair| -2 KM::|*unity|) NIL NIL)
   (KM::|OCl-Minus| ("hypochlorite")
    (:|seq| (:|pair| 1 KM::O) (:|pair| 1 KM::|Cl|))
    (:|seq| (:|pair| 1 KM::O) (:|pair| 1 KM::|Cl|))
    (:|seq| (:|pair| 1 KM::O) (:|pair| 1 KM::|Cl|))
    (:|pair| -1 KM::|*unity|) NIL NIL)
   (KM::|OH-Minus| ("hydroxide")
    (:|seq| (:|pair| 1 KM::O) (:|pair| 1 KM::H))
    (:|seq| (:|pair| 1 KM::O) (:|pair| 1 KM::H))
    (:|seq| (:|pair| 1 KM::O) (:|pair| 1 KM::H))
    (:|pair| -1 KM::|*unity|) NIL NIL)
   (KM::|P2O7-Minus-4| ("pyrophosphate")
    (:|seq| (:|pair| 2 KM::P) (:|pair| 7 KM::O))
    (:|seq| (:|pair| 2 KM::P) (:|pair| 7 KM::O))
    (:|seq| (:|pair| 2 KM::P) (:|pair| 7 KM::O))
    (:|pair| -4 KM::|*unity|) ("pyrophosphoric") NIL)
   (KM::|PO3-Minus-3| ("phosphite")
    (:|seq| (:|pair| 1 KM::P) (:|pair| 3 KM::O))
    (:|seq| (:|pair| 1 KM::P) (:|pair| 3 KM::O))
    (:|seq| (:|pair| 1 KM::P) (:|pair| 3 KM::O))
    (:|pair| -3 KM::|*unity|) NIL NIL)
   (KM::|PO4-Minus-3| ("phosphate")
    (:|seq| (:|pair| 1 KM::P) (:|pair| 4 KM::O))
    (:|seq| (:|pair| 1 KM::P) (:|pair| 4 KM::O))
    (:|seq| (:|pair| 1 KM::P) (:|pair| 4 KM::O))
    (:|pair| -3 KM::|*unity|) ("phosphoric") NIL)
   (KM::|S-Minus-2| ("sulfide") (:|seq| (:|pair| 1 KM::S))
    (:|seq| (:|pair| 1 KM::S)) (:|seq| (:|pair| 1 KM::S))
    (:|pair| -2 KM::|*unity|) ("hydrosulfuric") NIL)
   (KM::|SO3-Minus-2| ("sulfite")
    (:|seq| (:|pair| 1 KM::S) (:|pair| 3 KM::O))
    (:|seq| (:|pair| 1 KM::S) (:|pair| 3 KM::O))
    (:|seq| (:|pair| 1 KM::S) (:|pair| 3 KM::O))
    (:|pair| -2 KM::|*unity|) ("sulfurous") NIL)
   (KM::|SO4-Minus-2| ("sulfate")
    (:|seq| (:|pair| 1 KM::S) (:|pair| 4 KM::O))
    (:|seq| (:|pair| 1 KM::S) (:|pair| 4 KM::O))
    (:|seq| (:|pair| 1 KM::S) (:|pair| 4 KM::O))
    (:|pair| -2 KM::|*unity|) ("sulfuric") NIL)
   (KM::|SeO3-Minus-2| ("selenite")
    (:|seq| (:|pair| 1 KM::|Se|) (:|pair| 3 KM::O))
    (:|seq| (:|pair| 1 KM::|Se|) (:|pair| 3 KM::O))
    (:|seq| (:|pair| 1 KM::|Se|) (:|pair| 3 KM::O))
    (:|pair| -2 KM::|*unity|) ("selenous") NIL)
   (KM::|SeO4-Minus-2| ("selenate")
    (:|seq| (:|pair| 1 KM::|Se|) (:|pair| 4 KM::O))
    (:|seq| (:|pair| 1 KM::|Se|) (:|pair| 4 KM::O))
    (:|seq| (:|pair| 1 KM::|Se|) (:|pair| 4 KM::O))
    (:|pair| -2 KM::|*unity|) ("selenic") NIL)
   (KM::|SiF6-Minus-2| ("silver hexafluoride")
    (:|seq| (:|pair| 1 KM::|Si|) (:|pair| 6 KM::F))
    (:|seq| (:|pair| 1 KM::|Si|) (:|pair| 6 KM::F))
    (:|seq| (:|pair| 1 KM::|Si|) (:|pair| 6 KM::F))
    (:|pair| -2 KM::|*unity|) NIL NIL)
   (KM::|As-Plus-3| ("arsenic(iii)") (:|seq| (:|pair| 1 KM::|As|))
    (:|seq| (:|pair| 1 KM::|As|)) (:|seq| (:|pair| 1 KM::|As|))
    (:|pair| 3 KM::|*unity|) NIL NIL)
   (KM::|C2H5NH3-Plus| ("ethlyammonium")
    (:|seq| (:|pair| 2 KM::C) (:|pair| 5 KM::H) (:|pair| 1 KM::N)
     (:|pair| 3 KM::H))
    (:|seq| (:|pair| 2 KM::C) (:|pair| 5 KM::H) (:|pair| 1 KM::N)
     (:|pair| 3 KM::H))
    (:|seq| (:|pair| 2 KM::C) (:|pair| 8 KM::H) (:|pair| 1 KM::N))
    (:|pair| 1 KM::|*unity|) NIL NIL)
   (KM::|C5H5NH-Plus| ("pyridinium")
    (:|seq| (:|pair| 5 KM::C) (:|pair| 5 KM::H) (:|pair| 1 KM::N)
     (:|pair| 1 KM::H))
    (:|seq| (:|pair| 5 KM::C) (:|pair| 5 KM::H) (:|pair| 1 KM::N)
     (:|pair| 1 KM::H))
    (:|seq| (:|pair| 5 KM::C) (:|pair| 6 KM::H) (:|pair| 1 KM::N))
    (:|pair| 1 KM::|*unity|) NIL NIL)
   (KM::|C6H5NH3-Plus| ("anilinium")
    (:|seq| (:|pair| 6 KM::C) (:|pair| 5 KM::H) (:|pair| 1 KM::N)
     (:|pair| 3 KM::H))
    (:|seq| (:|pair| 6 KM::C) (:|pair| 5 KM::H) (:|pair| 1 KM::N)
     (:|pair| 3 KM::H))
    (:|seq| (:|pair| 6 KM::C) (:|pair| 8 KM::H) (:|pair| 1 KM::N))
    (:|pair| 1 KM::|*unity|) NIL NIL)
   (KM::|CH3-Plus| ("methyl")
    (:|seq| (:|pair| 1 KM::C) (:|pair| 3 KM::H))
    (:|seq| (:|pair| 1 KM::C) (:|pair| 3 KM::H))
    (:|seq| (:|pair| 1 KM::C) (:|pair| 3 KM::H))
    (:|pair| 1 KM::|*unity|) NIL NIL)
   (KM::|CH3CH2NH3-Plus| ("ethylammonium") NIL NIL
    (:|seq| (:|pair| 2 KM::C) (:|pair| 8 KM::H) (:|pair| 1 KM::N)) NIL
    NIL NIL)
   (KM::|CH3_2_NH2-Plus| ("dimethlyammonium")
    (:|seq| (:|pair| 2 (:|seq| (:|pair| 1 KM::C) (:|pair| 3 KM::H)))
     (:|pair| 1 KM::N) (:|pair| 2 KM::H))
    (:|seq| (:|pair| 2 (:|seq| (:|pair| 1 KM::C) (:|pair| 3 KM::H)))
     (:|pair| 1 KM::N) (:|pair| 2 KM::H))
    (:|seq| (:|pair| 2 KM::C) (:|pair| 8 KM::H) (:|pair| 1 KM::N))
    (:|pair| 1 KM::|*unity|) NIL NIL)
   (KM::|CH3_3_NH-Plus| ("trimethlyammonium")
    (:|seq| (:|pair| 3 (:|seq| (:|pair| 1 KM::C) (:|pair| 3 KM::H)))
     (:|pair| 1 KM::N) (:|pair| 1 KM::H))
    (:|seq| (:|pair| 3 (:|seq| (:|pair| 1 KM::C) (:|pair| 3 KM::H)))
     (:|pair| 1 KM::N) (:|pair| 1 KM::H))
    (:|seq| (:|pair| 3 KM::C) (:|pair| 10 KM::H) (:|pair| 1 KM::N))
    (:|pair| 1 KM::|*unity|) NIL NIL)
   (KM::|Cr-Plus-3| ("chromium") (:|seq| (:|pair| 1 KM::|Cr|))
    (:|seq| (:|pair| 1 KM::|Cr|)) (:|seq| (:|pair| 1 KM::|Cr|))
    (:|pair| 3 KM::|*unity|) NIL NIL)
   (KM::|Fe_H2O_5-OH-Plus-2| ("iron hydroxide pentahydrate")
    (:|seq| (:|pair| 1 KM::|Fe|)
     (:|pair| 5 (:|seq| (:|pair| 2 KM::H) (:|pair| 1 KM::O)))
     (:|pair| 1 (:|seq| (:|pair| 1 KM::O) (:|pair| 1 KM::H))))
    (:|seq| (:|pair| 1 KM::|Fe|)
     (:|pair| 5 (:|seq| (:|pair| 2 KM::H) (:|pair| 1 KM::O)))
     (:|pair| 1 (:|seq| (:|pair| 1 KM::O) (:|pair| 1 KM::H))))
    (:|seq| (:|pair| 1 KM::|Fe|) (:|pair| 11 KM::H) (:|pair| 6 KM::O))
    (:|pair| 2 KM::|*unity|) NIL NIL)
   (KM::|Fe_H2O_6-Plus-3| ("iron hydrate")
    (:|seq| (:|pair| 1 KM::|Fe|)
     (:|pair| 6 (:|seq| (:|pair| 2 KM::H) (:|pair| 1 KM::O))))
    (:|seq| (:|pair| 1 KM::|Fe|)
     (:|pair| 6 (:|seq| (:|pair| 2 KM::H) (:|pair| 1 KM::O))))
    (:|seq| (:|pair| 1 KM::|Fe|) (:|pair| 12 KM::H) (:|pair| 6 KM::O))
    (:|pair| 3 KM::|*unity|) NIL NIL)
   (KM::|H-Plus| ("hydrogen") (:|seq| (:|pair| 1 KM::H))
    (:|seq| (:|pair| 1 KM::H)) (:|seq| (:|pair| 1 KM::H))
    (:|pair| 1 KM::|*unity|) NIL NIL)
   (KM::|H2NNH3-Plus| ("hydrazinium")
    (:|seq| (:|pair| 2 KM::H) (:|pair| 1 KM::N) (:|pair| 1 KM::N)
     (:|pair| 3 KM::H))
    (:|seq| (:|pair| 2 KM::H) (:|pair| 1 KM::N) (:|pair| 1 KM::N)
     (:|pair| 3 KM::H))
    (:|seq| (:|pair| 5 KM::H) (:|pair| 2 KM::N))
    (:|pair| 1 KM::|*unity|) NIL NIL)
   (KM::|H3NOH-Plus| ("hydroxylammonium")
    (:|seq| (:|pair| 3 KM::H) (:|pair| 1 KM::N) (:|pair| 1 KM::O)
     (:|pair| 1 KM::H))
    (:|seq| (:|pair| 3 KM::H) (:|pair| 1 KM::N) (:|pair| 1 KM::O)
     (:|pair| 1 KM::H))
    (:|seq| (:|pair| 1 KM::N) (:|pair| 4 KM::H) (:|pair| 1 KM::O))
    (:|pair| 1 KM::|*unity|) NIL NIL)
   (KM::|H3O-Plus| ("hydronium")
    (:|seq| (:|pair| 3 KM::H) (:|pair| 1 KM::O))
    (:|seq| (:|pair| 3 KM::H) (:|pair| 1 KM::O))
    (:|seq| (:|pair| 3 KM::H) (:|pair| 1 KM::O))
    (:|pair| 1 KM::|*unity|) NIL NIL)
   (KM::|HONH3-Plus| ("hydroxylammonium")
    (:|seq| (:|pair| 1 KM::H) (:|pair| 1 KM::O) (:|pair| 1 KM::N)
     (:|pair| 3 KM::H))
    (:|seq| (:|pair| 1 KM::H) (:|pair| 1 KM::O) (:|pair| 1 KM::N)
     (:|pair| 3 KM::H))
    (:|seq| (:|pair| 4 KM::H) (:|pair| 1 KM::O) (:|pair| 1 KM::N))
    (:|pair| 1 KM::|*unity|) NIL NIL)
   (KM::|Ag-Plus| ("silver") (:|seq| (:|pair| 1 KM::|Ag|))
    (:|seq| (:|pair| 1 KM::|Ag|)) (:|seq| (:|pair| 1 KM::|Ag|))
    (:|pair| 1 KM::|*unity|) NIL NIL)
   (KM::|Al-Plus-3| ("aluminum") (:|seq| (:|pair| 1 KM::|Al|))
    (:|seq| (:|pair| 1 KM::|Al|)) (:|seq| (:|pair| 1 KM::|Al|))
    (:|pair| 3 KM::|*unity|) NIL NIL)
   (KM::|Au-Plus-2| ("gold (ii)") (:|seq| (:|pair| 1 KM::|Au|))
    (:|seq| (:|pair| 1 KM::|Au|)) (:|seq| (:|pair| 1 KM::|Au|))
    (:|pair| 2 KM::|*unity|) NIL NIL)
   (KM::|Au-Plus-3| ("gold (iii)") (:|seq| (:|pair| 1 KM::|Au|))
    (:|seq| (:|pair| 1 KM::|Au|)) (:|seq| (:|pair| 1 KM::|Au|))
    (:|pair| 3 KM::|*unity|) NIL NIL)
   (KM::|Ba-Plus-2| ("barium") (:|seq| (:|pair| 1 KM::|Ba|))
    (:|seq| (:|pair| 1 KM::|Ba|)) (:|seq| (:|pair| 1 KM::|Ba|))
    (:|pair| 2 KM::|*unity|) NIL NIL)
   (KM::|Be-Plus-2| ("beryllium") (:|seq| (:|pair| 1 KM::|Be|))
    (:|seq| (:|pair| 1 KM::|Be|)) (:|seq| (:|pair| 1 KM::|Be|))
    (:|pair| 2 KM::|*unity|) NIL NIL)
   (KM::|CH3NH3-Plus| ("methylammonium")
    (:|seq| (:|pair| 1 KM::C) (:|pair| 3 KM::H) (:|pair| 1 KM::N)
     (:|pair| 3 KM::H))
    (:|seq| (:|pair| 1 KM::C) (:|pair| 3 KM::H) (:|pair| 1 KM::N)
     (:|pair| 3 KM::H))
    (:|seq| (:|pair| 1 KM::C) (:|pair| 6 KM::H) (:|pair| 1 KM::N))
    (:|pair| 1 KM::|*unity|) NIL NIL)
   (KM::|Ca-Plus-2| ("calcium") (:|seq| (:|pair| 1 KM::|Ca|))
    (:|seq| (:|pair| 1 KM::|Ca|)) (:|seq| (:|pair| 1 KM::|Ca|))
    (:|pair| 2 KM::|*unity|) NIL NIL)
   (KM::|Cd-Plus-2| ("cadmium") (:|seq| (:|pair| 1 KM::|Cd|))
    (:|seq| (:|pair| 1 KM::|Cd|)) (:|seq| (:|pair| 1 KM::|Cd|))
    (:|pair| 2 KM::|*unity|) NIL NIL)
   (KM::|Co-Plus-2| ("cobalt") (:|seq| (:|pair| 1 KM::|Co|))
    (:|seq| (:|pair| 1 KM::|Co|)) (:|seq| (:|pair| 1 KM::|Co|))
    (:|pair| 2 KM::|*unity|) NIL NIL)
   (KM::|Cs-Plus| ("caesium") (:|seq| (:|pair| 1 KM::|Cs|))
    (:|seq| (:|pair| 1 KM::|Cs|)) (:|seq| (:|pair| 1 KM::|Cs|))
    (:|pair| 1 KM::|*unity|) NIL NIL)
   (KM::|Cu-Plus-2| ("copper(ii)") (:|seq| (:|pair| 1 KM::|Cu|))
    (:|seq| (:|pair| 1 KM::|Cu|)) (:|seq| (:|pair| 1 KM::|Cu|))
    (:|pair| 2 KM::|*unity|) NIL NIL)
   (KM::|Cu-Plus| ("copper(i)") (:|seq| (:|pair| 1 KM::|Cu|))
    (:|seq| (:|pair| 1 KM::|Cu|)) (:|seq| (:|pair| 1 KM::|Cu|))
    (:|pair| 1 KM::|*unity|) NIL NIL)
   (KM::|Fe-Plus-2| ("iron(ii)") (:|seq| (:|pair| 1 KM::|Fe|))
    (:|seq| (:|pair| 1 KM::|Fe|)) (:|seq| (:|pair| 1 KM::|Fe|))
    (:|pair| 2 KM::|*unity|) NIL NIL)
   (KM::|Fe-Plus-3| ("iron(iii)") (:|seq| (:|pair| 1 KM::|Fe|))
    (:|seq| (:|pair| 1 KM::|Fe|)) (:|seq| (:|pair| 1 KM::|Fe|))
    (:|pair| 3 KM::|*unity|) NIL NIL)
   (KM::|Fr-Plus| ("francium") (:|seq| (:|pair| 1 KM::|Fr|))
    (:|seq| (:|pair| 1 KM::|Fr|)) (:|seq| (:|pair| 1 KM::|Fr|))
    (:|pair| 1 KM::|*unity|) NIL NIL)
   (KM::|Hg-Plus-2| ("mercury(ii)") (:|seq| (:|pair| 1 KM::|Hg|))
    (:|seq| (:|pair| 1 KM::|Hg|)) (:|seq| (:|pair| 1 KM::|Hg|))
    (:|pair| 2 KM::|*unity|) NIL NIL)
   (KM::|Hg-Plus| ("mercury(i)") (:|seq| (:|pair| 1 KM::|Hg|))
    (:|seq| (:|pair| 1 KM::|Hg|)) (:|seq| (:|pair| 1 KM::|Hg|))
    (:|pair| 1 KM::|*unity|) NIL NIL)
   (KM::|Hg2-Plus-2| ("mercury(i)") (:|seq| (:|pair| 2 KM::|Hg|))
    (:|seq| (:|pair| 2 KM::|Hg|)) (:|seq| (:|pair| 2 KM::|Hg|))
    (:|pair| 2 KM::|*unity|) NIL NIL)
   (KM::|K-Plus| ("potassium") (:|seq| (:|pair| 1 KM::K))
    (:|seq| (:|pair| 1 KM::K)) (:|seq| (:|pair| 1 KM::K))
    (:|pair| 1 KM::|*unity|) NIL NIL)
   (KM::|Li-Plus| ("lithium") (:|seq| (:|pair| 1 KM::|Li|))
    (:|seq| (:|pair| 1 KM::|Li|)) (:|seq| (:|pair| 1 KM::|Li|))
    (:|pair| 1 KM::|*unity|) NIL NIL)
   (KM::|Mg-Plus-2| ("magnesium") (:|seq| (:|pair| 1 KM::|Mg|))
    (:|seq| (:|pair| 1 KM::|Mg|)) (:|seq| (:|pair| 1 KM::|Mg|))
    (:|pair| 2 KM::|*unity|) NIL NIL)
   (KM::|Mn-Plus-2| ("manganese") (:|seq| (:|pair| 1 KM::|Mn|))
    (:|seq| (:|pair| 1 KM::|Mn|)) (:|seq| (:|pair| 1 KM::|Mn|))
    (:|pair| 2 KM::|*unity|) NIL NIL)
   (KM::|Mn-Plus-3| ("manganese") (:|seq| (:|pair| 1 KM::|Mn|))
    (:|seq| (:|pair| 1 KM::|Mn|)) (:|seq| (:|pair| 1 KM::|Mn|))
    (:|pair| 3 KM::|*unity|) NIL NIL)
   (KM::|Mn-Plus| ("manganese") (:|seq| (:|pair| 1 KM::|Mn|))
    (:|seq| (:|pair| 1 KM::|Mn|)) (:|seq| (:|pair| 1 KM::|Mn|))
    (:|pair| 1 KM::|*unity|) NIL NIL)
   (KM::|NH4-Plus| ("ammonium")
    (:|seq| (:|pair| 1 KM::N) (:|pair| 4 KM::H))
    (:|seq| (:|pair| 1 KM::N) (:|pair| 4 KM::H))
    (:|seq| (:|pair| 1 KM::N) (:|pair| 4 KM::H))
    (:|pair| 1 KM::|*unity|) NIL NIL)
   (KM::|Na-Plus| ("sodium") (:|seq| (:|pair| 1 KM::|Na|))
    (:|seq| (:|pair| 1 KM::|Na|)) (:|seq| (:|pair| 1 KM::|Na|))
    (:|pair| 1 KM::|*unity|) NIL NIL)
   (KM::|Ni-Plus-2| ("nickel") (:|seq| (:|pair| 1 KM::|Ni|))
    (:|seq| (:|pair| 1 KM::|Ni|)) (:|seq| (:|pair| 1 KM::|Ni|))
    (:|pair| 2 KM::|*unity|) NIL NIL)
   (KM::|Pb-Plus-2| ("lead") (:|seq| (:|pair| 1 KM::|Pb|))
    (:|seq| (:|pair| 1 KM::|Pb|)) (:|seq| (:|pair| 1 KM::|Pb|))
    (:|pair| 2 KM::|*unity|) NIL NIL)
   (KM::|Pt-Plus-2| ("platinum (ii)") (:|seq| (:|pair| 1 KM::|Pt|))
    (:|seq| (:|pair| 1 KM::|Pt|)) (:|seq| (:|pair| 1 KM::|Pt|))
    (:|pair| 2 KM::|*unity|) NIL NIL)
   (KM::|Ra-Plus-2| ("radium (ii)") (:|seq| (:|pair| 1 KM::|Ra|))
    (:|seq| (:|pair| 1 KM::|Ra|)) (:|seq| (:|pair| 1 KM::|Ra|))
    (:|pair| 2 KM::|*unity|) NIL NIL)
   (KM::|Rb-Plus| ("rubidium") (:|seq| (:|pair| 1 KM::|Rb|))
    (:|seq| (:|pair| 1 KM::|Rb|)) (:|seq| (:|pair| 1 KM::|Rb|))
    (:|pair| 1 KM::|*unity|) NIL NIL)
   (KM::|Sn-Plus-2| ("tin") (:|seq| (:|pair| 1 KM::|Sn|))
    (:|seq| (:|pair| 1 KM::|Sn|)) (:|seq| (:|pair| 1 KM::|Sn|))
    (:|pair| 2 KM::|*unity|) NIL NIL)
   (KM::|Sr-Plus-2| ("strontium") (:|seq| (:|pair| 1 KM::|Sr|))
    (:|seq| (:|pair| 1 KM::|Sr|)) (:|seq| (:|pair| 1 KM::|Sr|))
    (:|pair| 2 KM::|*unity|) NIL NIL)
   (KM::|V-Plus| ("vanadium") (:|seq| (:|pair| 1 KM::V))
    (:|seq| (:|pair| 1 KM::V)) (:|seq| (:|pair| 1 KM::V))
    (:|pair| 1 KM::|*unity|) NIL NIL)
   (KM::|Zn-Plus-2| ("zinc") (:|seq| (:|pair| 1 KM::|Zn|))
    (:|seq| (:|pair| 1 KM::|Zn|)) (:|seq| (:|pair| 1 KM::|Zn|))
    (:|pair| 2 KM::|*unity|) NIL NIL)
   (KM::|NH3CH3-Plus| ("methylammonium")
    (:|seq| (:|pair| 1 KM::N) (:|pair| 3 KM::H) (:|pair| 1 KM::C)
     (:|pair| 3 KM::H))
    (:|seq| (:|pair| 1 KM::N) (:|pair| 3 KM::H) (:|pair| 1 KM::C)
     (:|pair| 3 KM::H))
    (:|seq| (:|pair| 1 KM::N) (:|pair| 6 KM::H) (:|pair| 1 KM::C))
    (:|pair| 1 KM::|*unity|) NIL NIL)
   (KM::|NO2-Plus| ("nitronium")
    (:|seq| (:|pair| 1 KM::N) (:|pair| 2 KM::O))
    (:|seq| (:|pair| 1 KM::N) (:|pair| 2 KM::O))
    (:|seq| (:|pair| 1 KM::N) (:|pair| 2 KM::O))
    (:|pair| 1 KM::|*unity|) NIL NIL)))))